### ISSUE TITLE
dma-buf,Guest has not initialized the display(yet)

### ISSUE THREAD

**Issue by huzhiguang6000** [01org/gvt-linux#101]
ubuntu:18.04
gvt:gvt-stable-4.17
qemu:qemu 2.12.0
client cpu:6100u
gpu:intel HD Graphics 520
GTK:
/usr/bin/qemu-system-x86_64 \
    -m 2048 -smp 2 -M pc \
    -name local-display-vm \
    -hda /root/win7.qcow2 \
    -bios /usr/bin/bios.bin -enable-kvm \
    -vga none \
    -display gtk,gl=on \
    -k en-us \
    -machine kernel_irqchip=on \
    -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 \
    -cpu host -usb -usbdevice tablet \
    -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/59c57b6c-13ee-4055-846e-e4d3dc55d389,display=on,x-igd-opregion=on

When I installed the graphics driver, I set the parameters to VGA none, and then the following problems occurred “Guest has not initialized the display(yet)”.Then I set the parameters to VGA qxl, and Windows 7 will start up at this time, but will stay in the boot screen, and then choose vfio-pci from the View menu to enter the Windows 7 desktop.

**Comment by vasilypupkine656** [comment]
Same issue here, can see GVT output with with "-vga qxl" (selecting vfio-pci in View menu). with "-vga none" getting “Guest has not initialized the display(yet)”. Waited number of minutes for driver to load, still nothing. Tried different kernels - gvt-stable-4.17, upstrea, different Windows drivers, different qemu versions, same issue. Any ideas?

**Comment by TerrenceXu** [comment]
Share our validation status for gvt-staging code:
When set “-vga none”, guest will print “Guest has not initialized the display(yet)”, need to wait for about 200s and then will get the win7 desktop normally, it is a bug.
When set “-vga qxl”,need selecting vfio-pci in view menu,then will see the win7 desktop, but our win7 desktop get blurred and host got gpu hang once selecting vfio-pci, it is another bug.

gvt-stable-4.17 should without these 2 issues.

**Comment by huzhiguang6000** [comment]
> Share our validation status for gvt-staging code:
> When set “-vga none”, guest will print “Guest has not initialized the display(yet)”, need to wait for about 200s and then will get the win7 desktop normally, it is a bug.
> When set “-vga qxl”,need selecting vfio-pci in view menu,then will see the win7 desktop, but our win7 desktop get blurred and host got gpu hang once selecting vfio-pci, it is another bug.
> 
> gvt-stable-4.17 should without these 2 issues.

There is still this problem.Are there any other references?

**Comment by draplater** [comment]
I also encountered with this problem.
kernel: gvt-stable-4.17
qemu:both 2.12.0 and 4.0.0
client cpu: i5 6500
gpu:intel HD Graphics 520

**Comment by xiongzha** [comment]
Push try latest upstream kernel.

**Comment by TerrenceXu** [comment]
Issue not exist in the latest kernel, close it first.
