### ISSUE TITLE
kernel: gvt: vgpu 1: Invalid aperture offset 36864

### ISSUE THREAD

**Issue by rugubara** [01org/gvt-linux#102]
I have a working gentoo linux guest using iGVT-g mdev device. 
I'm trying to run a Windows10 guest now. 

The VM hangs at boot and my journal is full of 
мая 23 10:08:38 PF16W6Y2 kernel: gvt: vgpu 1: Invalid aperture offset 36864
мая 23 10:08:38 PF16W6Y2 kernel: gvt: vgpu 1: Invalid aperture offset 36864
мая 23 10:08:38 PF16W6Y2 kernel: gvt: vgpu 1: Invalid aperture offset 36864
мая 23 10:08:38 PF16W6Y2 kernel: gvt: vgpu 1: Invalid aperture offset 36864
мая 23 10:08:38 PF16W6Y2 kernel: gvt: vgpu 1: Invalid aperture offset 36864
мая 23 10:08:38 PF16W6Y2 kernel: gvt: vgpu 1: Invalid aperture offset 36864
мая 23 10:08:38 PF16W6Y2 kernel: gvt: vgpu 1: Invalid aperture offset 36864

Host: Linux PF16W6Y2 5.1.3-gentoo #1 SMP PREEMPT Sun May 19 16:33:52 MSK 2019 x86_64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GenuineIntel GNU/Linux
  
Guest: EFI based on i440FX windows 10 with QXL and MDEV.

**Comment by TerrenceXu** [comment]
I am not sure whether this issue still existed in your side with test the latest kernel code. This issue not happening in our side.

**Comment by rugubara** [comment]
Works OK for me too. Thanks!
