### ISSUE TITLE
Any chance of having GVT-g for Intel N4200? (Intel® HD Graphics 505) [Apollo Lake]

### ISSUE THREAD

**Issue by rkkoszewski** [01org/gvt-linux#103]
Hi, I'm unable to find what hardware features are required for GVT-g to be possible to run on an Intel chipset. From what I could see on my own hardware GVT-g is not supported with an Intel N4200 (Intel® HD Graphics 505) although the chip is newer than some older models that do support GVT-g. Is there any reason why that chip is not supported? Is there any chance that it will get support at some point?

**Comment by TerrenceXu** [comment]
GVT-g now is support the Apollo Lake platform for boot up Linux VM with the gvt-staging branch. You can chech whether the /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/ folder is existed after you already set i915.enable_gvt=1 in grub.

**Comment by rkkoszewski** [comment]
That are great news @TerrenceXu!! Is it only for Linux guests or does it also works with Windows VMs?

**Comment by dingzhc** [comment]
gvt-g supports both linux and windows. @TerrenceXu should be closed.

**Comment by TerrenceXu** [comment]
@rkkoszewski, though GVT-g support is for both Linux and Windows VM, but Windows is not recommended for Apollo Lake, so you can run Linux VM for Apollo Lake and run Windows VM on other platform. :)
