### ISSUE TITLE
GVT-g: VM crashed when rebooting after install Intel Graphics driver.

### ISSUE THREAD

**Issue by alandingbc** [01org/gvt-linux#106]
Host
OS:     Ubuntu 16.04 Server + kernel 4.17 + qemu-2.12 stable
CPU：I5 6700
GPU:   Intel® HD Graphics 530
Memory:  16G DDR4

Guest:
OS： Windows7
Driver Version: 15.45.23.4860

kernel arguments: 
intel_iommu=on,igfx_off  i915.enable_gvt=1 kvm.ignore_msrs=1

qemu arguments:
-global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 \
-device vfio-pci,sysfsdev=/sys/class/mdev_bus/0000:00:02.0/f6900664-7d46-11e9-bb43-c32a2d510343,rombar=0,display=off

First, following the wiki setup guides, and boot the VM with GVT-g. The guest os can recognize the PCI device (qxl and HP 530). 

Second, installing the  15.45.23.4860 driver, but it show the real version is 21.20.16.4860. The VM crashed when after installation.

![02-驱动（2）](https://user-images.githubusercontent.com/19187419/58397612-5ca70980-8084-11e9-8e65-e6b8988dd9f8.png)

The crash log: 
[ 3899.150964] vfio_pin_page_external: Task qemu-system-x86 (2818) RLIMIT_MEMLOCK (65536) exceeded
[ 3899.150964] gvt: vgpu 1: vfio_pin_pages failed for gfn 0x128239: -12
[ 3899.151658] gvt: vgpu 1: fail to populate guest ggtt entry

So, what's wrong here? I try the guest Windows10 which caused the same issue.

**Comment by alandingbc** [comment]
More info:
$ cat /sys/bus/pci/devices/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_4/available_instances
1
$ cat /sys/bus/pci/devices/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_4/description
low_gm_size: 128MB
high_gm_size: 512MB
fence: 4
resolution: 1920x1200
weight: 4

The vgpu was created by the i915-GVTg_V5_4.

**Comment by alandingbc** [comment]
fixed by myself.
close the issue

**Comment by TerrenceXu** [comment]
OK, we didn't reproduce this issue with the same configuration as your said. :)

**Comment by alandingbc** [comment]
> OK, we didn't reproduce this issue with the same configuration as your said. :)

Actually, I just switched to the Ubuntu 18.04 LTS which had to build the kvmgt.ko module. It couldn't work with the kernel 4.17 which was built as a debian package on Ubuntu 16.04 Server.

**Comment by alandingbc** [comment]
Actually, I just switched to the Ubuntu 18.04 LTS which had to build the
kvmgt.ko module. It couldn't work with my own building kernel 4.17 with
debian package installation on Ubuntu 16.04 Server.


Terrence Xu <notifications@github.com> 于2019年5月28日周二 下午4:17写道：
