### ISSUE TITLE
Info about Intel Core i9-9900K

### ISSUE THREAD

**Issue by adevur** [01org/gvt-linux#107]
Hello, I'm currently using Intel GVT-g technology with an Intel Core i7-7700 (with Intel UHD 630). I'm able to create only 1x virtual graphics device of type i915-GVTg_V5_4 or, alternatively, I can create up to 2x virtual graphics devices of type i915-GVTg_V5_8. Maybe someone can confirm to me that this is normal.

Anyway, my real question is: I'd like to buy an Intel Core i9-9900K (with Intel UHD 630) in order to better use Intel GVT-g technology, but I'm afraid that this CPU can only create 1x virtual device of type i915-GVTg_V5_4 (just like Intel Core i7-7700). Does anyone know how many virtual devices of type i915-GVTg_V5_4 I can create with i9-9900K?

OS INFO: I'm using CentOS 7.6 with stock kernel (i.e. 3.10.0-957.12.2.el7.x86_64).

**Comment by marcel-apf** [comment]
Hi @adevur,
My understanding is the i915-GVTg_V5_X your are able to use is also connected to the machine firmware (e.g. UEFI, BIOS) configuration, look for "video aperture" and allow 512MB+  for the integrated graphics card.

**Comment by adevur** [comment]
Hello, I've tried your suggestion: I have a Gigabyte GA-Z170X-Ultra Gaming motherboard, I went into BIOS settings and I set Intel DVMT up to 1024MB of VRAM. But still, I'm not able to create more than one virtual graphics device of type i915-GVTg_V5_4. This means that I'm not able to assign graphics to more than one virtual machine... Pretty useless, at the moment.
I checked Gigabyte website, and they say that this motherboard supports up to 1GB of shared RAM with Intel graphics card.

P.S.: if I run `lspci -v | grep -EA10 "3D|VGA" | grep 'prefetchable'`, I get `Memory at b0000000 (64-bit, prefetchable) [size=256M]` (i.e. lspci sees only 256MB of VRAM, but I read that this is somehow normal with Intel Graphics devices).

P.P.S.: just for clarity, in my case virtual devices of type i915-GVTg_V5_4 have a maximum resolution of 1920x1200, while virtual devices of type i915-GVTg_V5_8 have a maximum resolution of 1024x768.

**Comment by TerrenceXu** [comment]
@adevur It is depend on the aperture size, from your information, it only with 256M aperture size. So it only can create one VM with i915-GVTg_V5_4.
In BIOS the option named "aperture size" but not "Intel DVMT". The NUC machine can modify the aperture size.


	y	aperture memory size		hidden memory size		fence size

	-------------------------------------------------------------------------------------------------------------

	8	64				384				4

	4	128				512				4

	2	256				1024				4

	1	512				2048				4

**Comment by marcel-apf** [comment]
@adevur I agree with @TerrenceXu, even if you tweaked the "BIOS" you didn't get the right video aperture size. I suggest you upgrade your firmware (can be dangerous) and/or talk to your motherboard vendor regarding the right settings for the video aperture.
Regarding 256M VRAM to be "normal", I agree it seems to be the  default value, but is not enough for gvt-g.

**Comment by adevur** [comment]
Thank you all. I have been unable to find settings about "aperture size". The setting that is most similar to this is "DVMT Total Gfx Mem", but its maximum value is 256MB. It is quite strange that I cannot find a way to increase VRAM... especially since Gigabyte says on their website that this motherboard supports up to 1GB of shared Intel VRAM.
Now I contacted Gigabyte's technical support, I'll see what they say.

P.S.: where can I find a list of qualified motherboards which offer good support of Intel GVT-g technology? I mean, a list of motherboards that have been tested and work well enough with increasing Intel's VRAM etc. I'm looking for motherboards with chipset Z370 or Z390, especially.

**Comment by TerrenceXu** [comment]
@adevur, you should see the detail user guide for the motherboard.
We have tried the（SUPERMICRO）C7Z370-CG-IW motherboard which is support modify aperture size.

**Comment by adevur** [comment]
Thanks @TerrenceXu, I had a look at Supermicro C7Z370-CG-IW motherboard. I also found another Supermicro motherboard that perfectly fits my needs: Supermicro C9Z390-CG-O
It is an ATX motherboard with chipset Z390, and I'd like to use it with an Intel Core i9-9900K.

About the motherboard, I'll contact Supermicro in order to confirm that C9Z390-CG-O has the same functionality to increase Intel graphics aperture size just like C7Z370-CG-IW.

About the CPU, can you confirm to me that Intel Core i9-9900K (with Intel UHD 630) supports Intel GVT-g technology?

**Comment by adevur** [comment]
UPDATE: I contacted Intel support, and they confirmed that Intel Core i9-9900K supports Intel GVT-g technology.
I have no more questions, so I'll close this issue.
Thanks to all.

**Comment by eurodomenii** [comment]
> About the motherboard, I'll contact Supermicro in order to confirm that C9Z390-CG-O has the same functionality to increase Intel graphics aperture size just like C7Z370-CG-IW.
> 
Did Supermicro support confirmed? Thanks!

**Comment by adevur** [comment]
> > About the motherboard, I'll contact Supermicro in order to confirm that C9Z390-CG-O has the same functionality to increase Intel graphics aperture size just like C7Z370-CG-IW.
> 
> Did Supermicro support confirmed? Thanks!

Yes, Supermicro C9Z390-CG supports aperture size increase just like Supermicro C7Z370-CG-IW. However, I did not test it directly.

**Comment by eurodomenii** [comment]
Indeed https://www.supermicro.com/manuals/motherboard/Z390/MNL-2098.pdf 

> Use this feature to set the Aperture size, which is the size of system memory reserved by the BIOS for graphics device use. The options are 128MB, 256MB, 512MB, 1024MB, and 2048MB.
