### ISSUE TITLE
Need to create vGPU *after* X server started?

### ISSUE THREAD

**Issue by XeCycle** [01org/gvt-linux#108]
I managed to create a successful setup of GVT-g + DMA_BUF on i7 7700, with the vGPU as the only GPU inside guest.

During testing I created the vGPU manually, from a running X desktop, and things worked fine; after that I added a /etc/tmpfiles.d entry to create the vGPU --- but after reboot, the same qemu command failed.

With some trial-and-error, the problem seems to be that it cannot support resolution over 1920x1080; whenever I enter fullscreen (1920x1200) or maximize the GTK window, the guest hangs.  If qemu was started -full-screen, the guest never initializes display, and just hangs forever.  During that dmesg says (same as #29) "kernel: gvt: vgpu 1: invalid range gmadr 0x0 size 0x0" (but nowhere nere "flooded", just a few dozens).

If I remove tmpfiles.d entry and manually create the vGPU after X server started, everything goes fine, it runs happily at 1920x1200.

Looks like the X server did something and broke a previously created vGPU?

**Comment by cxdong** [comment]
@TerrenceXu do we see similar issue from our side?

**Comment by TerrenceXu** [comment]
@XeCycle Sorry, I am not sure this issue is still existed in your side, I just curious why you add a entry to /etc/tmpfiles.d？ Do you means the VM has error at the second time boot up with DMA-BUF enabling？

**Comment by XeCycle** [comment]
It's been more than a year, and now it works with 5.8.14.
