### ISSUE TITLE
DmaBuf not working on 16.04.3 with latest 4.14-stable kernel

### ISSUE THREAD

**Issue by newhacker1746** [01org/gvt-linux#11]
Have compiled the latest 4.14-stable cloned from here with the relevant i915 KVMGT driver bits set to "y" and I have a Broadwell GPU (MacBookAir6,2 a.k.a "Early 2015") that works with vgpu (if headless, it works fine, I mean.) however using kvmgt-dmabuf-example to show the guest's framebuffer does not work (no display output unless I specifically add another vga device like -vga qxl.) I also noticed that some firmware load failed in the syslog, which could be the cause of the problem:
```
$ dmesg | grep -i i915
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.14.0-newperson1746-test2-generic root=UUID=e5561bd9-6268-4883-83e5-aa521d59814b ro --verbose i915.enable_gvt=1 kvm.ignore_msrs=0 intel_iommu=igfx_off vt.handoff=7
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.14.0-newperson1746-test2-generic root=UUID=e5561bd9-6268-4883-83e5-aa521d59814b ro --verbose i915.enable_gvt=1 kvm.ignore_msrs=0 intel_iommu=igfx_off vt.handoff=7
[    1.874932] i915 0000:00:02.0: Direct firmware load for i915/gvt/vid_0x8086_did_0x1626_rid_0x09.golden_hw_state failed with error -2
[    1.886786] i915 0000:00:02.0: MDEV: Registered
[    1.886852] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    1.902343] [drm] Initialized i915 1.6.0 20170818 for 0000:00:02.0 on minor 0
[    4.469475] i915 0000:00:02.0: fb0: inteldrmfb frame buffer device
[    6.776064] snd_hda_intel 0000:00:03.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
```
From qemu:
```
$ qemu-system-x86_64 ... {long options}
qemu-system-x86_64: -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/20d78d8d-d2f1-416f-b49a-fc9a58171df0: vfio: get dmabuf mgr fd failed:-1

egl extensions found. Intel GVT-g indirect display will be enabled
Use dma-buf to get guest framebuffer
```
I am trying gvt-staging now, however that branch is older by 3 days and therefore my hopes aren't high.

**Comment by TerrenceXu** [comment]
Hello, which qemu branch you are used?

**Comment by newhacker1746** [comment]
I used intel/Igvtg-qemu:kvmgt_dmabuf_example.

**Comment by TerrenceXu** [comment]
Hello

Please use “gvt-staging” branch in kernel side, since the “gvt-stable-4.14’ just be created and without dma-buf feature be validated.

And use “qa_dma_buf” branch in qemu side, it with the dma-buf feature be validated.


Now dma-buf feature is still in experimental stage, we will provide the official guide when it is stable enough. ☺

Thanks
Terrence

**Comment by trevor403** [comment]
It seems that these two branches are not compatible at the moment. Using them at their current commit causes ioctl Invalid Argument for the VFIO GFX PLANE, sorry I can't copy and past I'm in a cab. Anyway are there any compatible dma-buf branches for gvt linux+qemu?

**Comment by TerrenceXu** [comment]
Hello, in order to use the the dma-buf feature, you can use the latest stable-4.14 kernel with the latest stable 2.10.0 qemu. ☺

Thanks
Terrence

**Comment by trevor403** [comment]
Do you know if the 15.60 guest driver will write to the VGPU PLANE, or is the dma-buf feature only functional under 15.45 guest drivers

**Comment by TerrenceXu** [comment]
The dma-buf is also working on 15.60 guest driver, but the 15.60 guest driver with the guest low performance issue and need to be fixed, so we still recommend use 15.45 driver, and after the issue be fixed we still recommend it in the Wiki page. ☺

Thanks
Terrence

**Comment by oscarbg** [comment]
@TerrenceXu @trevor403 do you know if with 15.65.3 drivers dma_buf performance is restored to 15.45 levels?
I mean 
"Intel HD Graphics Driver 15.65.3 for Windows 10 64-bit" win64_15.65.3.4944.exe
or new 23.20.16.4958
http://www.station-drivers.com/index.php?option=com_kunena&view=topic&catid=4&id=2016&Itemid=255&limitstart=92&lang=fr#16118

**Comment by TerrenceXu** [comment]
Hello, the 15.45 Driver without the performance issue but the 15.65 Driver with the performance regression issue, you can use the 15.45 Driver first. ☺
