### ISSUE TITLE
CPU/kernel/distribution support matrix

### ISSUE THREAD

**Issue by renne** [01org/gvt-linux#111]
Debugging KVM issues is always complicated as you never know which combination of CPU and distro kernel supports virtualization features (e.g. Coffee Lake-Gap in kernels < 5.1).

I suggest to add two support matrices to the Wiki:

1. CPU -> vanilla linux kernel source version -> supported features (e.g. GVT-d, GVT-g)
2. CPU -> distribution-specific linux kernel  binary version -> supported features (e.g. GVT-d, GVT-g)

e.g.

CPU | Vanilla kernel | GVT-d | GVT-g
:--- | :--- | :---: | :---:
Celeron G4900 | Linux 4.19.37 | x | x

CPU | Distro kernel | GVT-d | GVT-g
:--- | :--- | :---: | :---:
Celeron G4900 | Debian 10 4.19.37-5 | x | x

**Comment by TerrenceXu** [comment]
Good idea, I am plan to update the setup guide these days, and will consider to add some support matrix. :)
