### ISSUE TITLE
Unable install intel gpu driver in windows vm,error code 43

### ISSUE THREAD

**Issue by out0fmemory** [01org/gvt-linux#113]
As Title says, gpu pass to windows vms, can not run correctly, the driver error code is 43

My platform info is blew:
host：ubuntu18.04 with 5.20 kernel
libvirt：4.10
gpu: intel j3455 integrated gpu

**Comment by rkkoszewski** [comment]
I had the same issue with the default driver installed by Windows. You need to install another Intel GPU Driver (Try with the one for the Motherboard or Intel website).

**Comment by TerrenceXu** [comment]
@out0fmemory   j3455 is Apollo Lake platform, we are not support GVT-g Windows VM for Apollo Lake platform, you can try Broadwell, Skylake, Kabylake or Coffeelake.

**Comment by rkkoszewski** [comment]
@TerrenceXu are there any plans to support Apollo Lake properly (Linux without workarounds, and Windows)?

**Comment by out0fmemory** [comment]
@TerrenceXu Yes, you are right, j3455 not support gvt-g, but it support gvt-d, and I success used it ,but the performance is very pool ,and crashed frequently.

**Comment by out0fmemory** [comment]
@rkkoszewski  You can pass the j3455 gpu to vm directly(qemu or libvirt), And install windows10(windows7 will have code 43 problem),This works for me.

As this post said,
https://worthdoingbadly.com/gpupassthrough/

**Comment by rkkoszewski** [comment]
@out0fmemory I just tried to do the proper passtrough (non mediated - with the script) and I'm getting the code 43 (Device cannot be initiated) in Windows 10. Tried all kind of things. Rom seems unacessible in passtrough nor in gvt-g. Also with passtrough I get a DMAR exception (DMAR: [DMA Write] Request device [00:02.0] fault addr 0 [fault reason 02] Present bit in context entry is clear)

@TerrenceXu Do you know if Apollo Lake iGPU chip design is just bad or why is it impossible to passtrough or run gvt-g in a Windows Guest?

**Comment by out0fmemory** [comment]
@rkkoszewski  which linux kernel version you used? seems like the this need a high version of linux, i used 5.3.0 kernel

**Comment by rkkoszewski** [comment]
Tested with both kernel 5.0 and 5.3 with booth mediated and passtrough. With no working result.

**Comment by TinaZhangZW** [comment]
This issue cannot be reproduced with the recommended windows driver version.  Let's close the issue.
