### ISSUE TITLE
Black screen with cursor in Windows 10

### ISSUE THREAD

**Issue by linjunming** [01org/gvt-linux#116]
Hi, i found my vm **often** reboots to a black screen(not totally), while the cursor still works.
 
[system parameters]
CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
OS: ubuntu 18.04
Kernel: 4.17.0 (https://github.com/intel/gvt-linux.git, gvt-stable-4.17)
Qemu: 2.12.0
Guest: Win10 1809 (Win7 can also reproduce the issue)
vGPU: Intel HD 620 (26.20.100.7000)

[command]
qemu-system-x86_64 -bios /usr/bin/bios.bin \
-m 2048 -smp 2 -M pc -name gvt-g-guest \
-hda /var/lib/libvirt/images/win10_1809.qcow2 \
-enable-kvm \
-k en-us  \
-serial stdio  \
-machine kernel_irqchip=on  \
-global PIIX4_PM.disable_s3=1  \
-global PIIX4_PM.disable_s4=1  \
-cpu host  \
-usb  \
-device usb-tablet  \
-device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/f75fe82e-bd98-11e9-b2e1-7b6f028b78a3,rombar=0,display=on,x-igd-opregion=on  \
-net nic,macaddr=DE:AD:BE:EF:00:05  \
-net tap,script=/root/Downloads/qemu-ifup  \
-vga none  \
-display gtk,gl=on

[screenshot]
![2](https://user-images.githubusercontent.com/29030423/62924426-aaf5ba00-bde2-11e9-973f-536e70ddc90a.png)

------------------------
The issue also occurs in linux 5.2.0 generic, **sometimes but not so often**.

I have applied the patch below:
1e8b15a drm/i915/gvt: Add in context mmio 0x20D8 to gen9 mmio list
but it doesn't work.

**Comment by TerrenceXu** [comment]
I am not sure whether this issue still existed in your side with test the latest kernel code + Windows GFX driver. This issue not happening in our side.
