### ISSUE TITLE
Support for Whiskylake

### ISSUE THREAD

**Issue by stackcoder** [01org/gvt-linux#118]
As far as I got to this *Whiskylake* is a gen8 *Broadwell* follow up. So why gvt is [not supported](https://github.com/intel/gvt-linux/blob/17fd4f9f0c3f4edbb10ccfd5a2d5cba61df4d4fe/drivers/gpu/drm/i915/intel_gvt.c#L42) on this platform?

Is there more work to do than adding the missing defines?

**Comment by ivohulsman** [comment]
I am wondering about this too. I can seem to get it to work partially, but performance is terrible.

**Comment by stackcoder** [comment]
Terrible performance? Your software might fall back to cpu rendering. Looks for me like it's still just not implemented: https://github.com/intel/gvt-linux/blob/gvt-staging/drivers/gpu/drm/i915/intel_gvt.c

**Comment by NoSync** [comment]
I'm wondering too. The platform is extremely similar to Coffee Lake, which is supported, and it'd be great to receive support.

**Comment by stackcoder** [comment]
No reaction for almost one year. That's pretty bad. We might try fixing this by our own?

**Comment by TerrenceXu** [comment]
Whiskylake already be supported from 5.2 kernel.
