### ISSUE TITLE
Windows 10 hangs after changing EDID info

### ISSUE THREAD

**Issue by alexfs** [01org/gvt-linux#119]
Hello,
I have a display with 1920x1080 resolution.  Since the GPU reports 1920x1200 by default I applied the following patch to enable correct display settings:

        /*TODO: add more platforms support */
-       if (IS_SKYLAKE(gvt->dev_priv) || IS_KABYLAKE(gvt->dev_priv))
+       if (IS_COFFEELAKE(gvt->dev_priv) || IS_SKYLAKE(gvt->dev_priv) || IS_KABYLAKE(gvt->dev_priv))
                ret = intel_gvt_hypervisor_set_edid(vgpu, PORT_D);

Windows 10 starts correctly in a window with a lower resolution, however when I try to enter the full screen it hangs for a few seconds and then reboots. I have the latest driver installed in the guest. Also it seems that every other resolution lower than  1920x1200 works, I can resize the window just fine, only the full screen won't work. 
Any ideas?

GPU: UHD 620
Platform: Coffeelake
Kernel 5.3-rc6-mainline:

**Comment by dingzhc** [comment]
coffelake support has been merged. @TerrenceXu should be closed.

**Comment by TerrenceXu** [comment]
yes, @alexfs you can just tried the latest kernel.
