### ISSUE TITLE
If gvt support direct show

### ISSUE THREAD

**Issue by maqiangddb** [01org/gvt-linux#12]
Hi:
    I tested branch gvt-stable-4.14, all works fine. I want know if this support direct show vgpu in the screen?    
like "i915.hvm_boot_foreground" of project "Igvtg-kernel". Looking forward for reply!

**Comment by TerrenceXu** [comment]
No, we will not support the foreground display mode.
We will use local display / remote display mode by dma-buf in the next time release. ☺
