### ISSUE TITLE
On Windows 10 1903 guests, Control Panel and a few other applications are crashing

### ISSUE THREAD

**Issue by FurretUber** [01org/gvt-linux#121]
Some applications, as the Control Panel, are crashing when opened. The guest is Windows 10 1903 using Intel Driver version 25.20.100.6326. On Windows 10 Event Viewer, the following can be seen:

![image](https://user-images.githubusercontent.com/25434442/65826398-910d1b00-e25a-11e9-9295-363621d264d3.png)

![image](https://user-images.githubusercontent.com/25434442/65826406-a3875480-e25a-11e9-8bd8-e9edb2794329.png)

The host is Xubuntu 18.04, the kernel used is gvt-linux ef0f420c3771bdb6633170affe708f0dbc649500, QEMU version is 4.1.50 (v4.1.0-1188-gc6f5012ba5-dirty). The processor is Intel Core i3-6100U and the GPU is Intel HD Graphics 520.

QEMU command line:

```
/usr/local/bin/qemu-system-x86_64 -name "Windows 10" -nodefaults -M pc-i440fx-3.1,usb=true \
-machine kernel_irqchip=on \
-device qemu-xhci,id=qemu-xhci,addr=4,p2=127,p3=127 \
-global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 \
-hda redm.qcow2 -enable-kvm \
-cpu Skylake-Client,hv_time,hv_relaxed,hv_vapic,hv_spinlocks=0x1fff,hv_runtime \
-smp cores=2,threads=2 -m 3072M -bios "/usr/local/share/qemu/bios.bin" \
-device usb-tablet,id=tablet,bus=qemu-xhci.0,port=1 \
-device usb-audio,id=usbaudvir,buffer=6144,port=1,bus=usb-bus.0 \
-device usb-host,vendorid=0x0079,id=redragon,bus=qemu-xhci.0 \
-device usb-host,vendorid=0x0458,id=mousegenius,bus=qemu-xhci.0 \
-vga none -monitor vc -serial stdio -display gtk,gl=on \
-device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/20312cec-80f4-448a-9f09-7b93adbf672c,x-igd-opregion=on,rombar=0,display=on,addr=0x3,id=iHD520 \
-netdev user,id=net0 -device e1000,netdev=net0,id=n0,addr=0x8
```

**Comment by fred1gao** [comment]
sorry for the issue, it does not happen on our regular test. can u try the latest window gfx driver with the official configuration

**Comment by FurretUber** [comment]
Hi, using QEMU 4.2.1 (Debian 1:4.2-3ubuntu6.6) and 5.4.0-48-generic from Ubuntu 20.04, I no longer face this problem, Control Panel is opening normally.

**Comment by TerrenceXu** [comment]
@FurretUber glad to hear it.
