### ISSUE TITLE
Goldmont plus / Gemini Lake support

### ISSUE THREAD

**Issue by blablatros** [01org/gvt-linux#124]
Are there plans to support Goldmont plus / Gemini Lake platform?

**Comment by blablatros** [comment]
Any update on this?

**Comment by blablatros** [comment]
I bought a J4105 based board (goldmontplus).

`modprobe kvmgt` yields `modprobe: ERROR: could not insert 'kvmgt': No such device`

`dmesg | grep -i gvt` output:

`[    0.000000] Command line: initrd=\intel-ucode.img initrd=\initramfs-linux.img root=/dev/lvm_vg_0/lvm_lv_arch i915.enable_gvt=1
[    0.351602] Kernel command line: initrd=\intel-ucode.img initrd=\initramfs-linux.img root=/dev/lvm_vg_0/lvm_lv_arch i915.enable_gvt=1
[    1.936849] [drm] Unsupported device. GVT-g is disabled`

I suppose the J4105 is not supported. Are there plans to support it?

**Comment by struthio** [comment]
Its bad that J4105 is not supported. I see boards with this chip available too bad it doesn't have this virtualization. Such setup will be perfect for small homelab.

**Comment by BankaiNoJutsu** [comment]
You can check this file, I believe that from an arch point it shows the allowed/supported ones at load.

https://github.com/intel/gvt-linux/blob/gvt-staging/drivers/gpu/drm/i915/intel_gvt.c

Saddly my J5005 NUC doesn't work either.
https://github.com/intel/gvt-linux/issues/64 (I see you already asked there as well)

**Comment by TerrenceXu** [comment]
duplicate to #64
