### ISSUE TITLE
Ice Lake support?

### ISSUE THREAD

**Issue by inodentry** [01org/gvt-linux#126]
Hello, I have a new Dell XPS 2-in-1 7390 laptop with 10th gen Intel Ice Lake i7 1065G7 processor with Iris Plus graphics. This GPU is fast enough to play many games on Windows and I would love to be able to use it for such a virtual machine with GVT-g.

I cannot modprobe the `kvmgt` module. I get error: `modprobe: ERROR: could not insert 'kvmgt': No such device`. I guess that this is because of missing ice lake support. I am using the new Linux kernel 5.4.

Could you please confirm what is the status of support for Ice Lake with Iris Plus graphics? Will my hardware be supported soon?

**Comment by jasoryeh** [comment]
I'm on Ice Lake, but instead getting the drm error `[    1.048036] i915 0000:00:02.0: [drm] Unsupported device. GVT-g is disabled`.

On a Surface Book 3 testing things out, have same processor model as you. Looks like it's not supported yet https://github.com/intel/gvt-linux/blob/0d7a87ff900a58e298f65e710de69207a3d2c1aa/drivers/gpu/drm/i915/intel_gvt.c#L43

And is why I got the above error.

Any updates?

Edit: Oh, on 5.8.3 with linux-surface mods running Ubuntu 20.04

**Comment by LordRafa** [comment]
Be aware that one thing is the source tree on this page, that probably has the latest public upgrades and another thing is the kernel that you are using... upstream (linux) has not incorporated yet many changes present on this page. Probably you can check what is supported and in which version here:
https://elixir.bootlin.com/linux/v5.4.61/source/drivers/gpu/drm/i915/intel_gvt.c#L42

5.4 has not included yet the COMETLAKE, it will be hopefully added on 5.9....

What I am not 100% sure if adding comet lake would mean support ice lake straight forward even if both are 10th gen... Intel versioning is quite the hell nowadays....

**Comment by coxuintel** [comment]
Ice lake belongs to GEN11 which doesn't have GVT-g support yet.

**Comment by inodentry** [comment]
@coxuintel is it planned to ever be added?

**Comment by LordRafa** [comment]
@coxuintel  hum I thought that it was GEN10 at least is how it is described on the Wikipedia and it uses the GEN10 versioning.... As I say with this much refreshment and archs it is quite messy to follow Intel gens nowadays.... Thanks for the info anyway

**Comment by TerrenceXu** [comment]
@jamadazi, until now there is no plan on it.

**Comment by adrusi** [comment]
Is this due to a hardware limitation, or is it simply not prioritized?

**Comment by black-puppydog** [comment]
@adrusi the latter. if dell wanted to, they could make this happen. Or Intel too, of course.
