### ISSUE TITLE
Status of Thunderbolt support

### ISSUE THREAD

**Issue by eurodomenii** [01org/gvt-linux#129]
There a good related activity, in the commit queue,  https://github.com/intel/gvt-linux/search?q=thunderbolt&type=Commits 

Since  I found Ice lake Support, in the commits,  I guess latest Coffee Lake is pretty stable.

But, I  would love to hear some real world user stories.

I plan to get https://www.gigabyte.com/Motherboard/Z390-DESIGNARE-rev-10/sp#sp, having HDMI + Thunderbolt, which already has some issues http://forum.gigabyte.us/thread/6193/thunderbolt-bios-fix-z390-designare 

Thanks!

**Comment by xzhan34** [comment]
this issue looks like not related with GVT-g. so would like to close this one and please report the issue for intel gfx driver bucket.
