### ISSUE TITLE
Kaby lake vgpu not support for WIN7 ?

### ISSUE THREAD

**Issue by maqiangddb** [01org/gvt-linux#13]
Hi:
    gvt-linux branch: gvt-stable-4.14, 
    igvtg-qemu branch: stable-2.10.0 
    Hardware : Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    I create a vgpu for my win7 VM, but I can't install display driver for this vgpu, there is message in log file:

```
  [INF Info]
    INF = C:\Users\test\Downloads\win64_154519.4678\Graphics\igdlh64.inf
*   Section <PackageInfo> Key <Sequence> not found in INF
    Date = 05/17/2017
    Version = 21.20.16.4678
    ClassGUID = {4D36E968-E325-11CE-BFC1-08002BE10318}
    PackageInfo.Name = Graphics
    PackageInfo.Sequence = 0
    Manufacturer = IntelGfx,NTamd64.6.1,NTamd64.6.2,NTamd64.6.3,NTamd64.10.0,NTamd64.10.0...14393
    Resolved Manufacturer = IntelGfx.NTamd64.6.1
    Inf supports 64 bit.
    Description: Intel(R) HD Graphics 510
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1906
    Description: Intel(R) HD Graphics 520
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1916
    Description: Intel(R) HD Graphics 515
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_191E
    Description: Intel(R) HD Graphics 530
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1912
    Description: Intel(R) HD Graphics 520
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1921
    Description: Intel(R) Iris(TM) Graphics 540
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1926
    Description: Intel(R) HD Graphics 535
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1923
    Description: Intel(R) Iris(TM) Graphics 550
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1927
    Description: Intel(R) HD Graphics 510
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1902
    Description: Intel(R) HD Graphics 510
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_190B
    Description: Intel(R) Iris(TM) Pro Graphics 580
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_193B
    Description: Intel(R) Iris(TM) Graphics 555
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_192B
    Description: Intel(R) HD Graphics 530
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_191B
    Description: Intel(R) Iris(TM) Graphics P555
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_192D
    Description: Intel(R) Iris(TM) Pro Graphics P580
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_193A
    Description: Intel(R) HD Graphics P530
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_191D
    Description: Intel(R) Iris(TM) Pro Graphics P580
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_193D
  Removed C:\Users\test\Downloads\win64_154519.4678\DisplayAudio\10.22\IntcDAud.inf
  Removed C:\Users\test\Downloads\win64_154519.4678\DisplayAudio\6.16\IntcDAud.inf
  Removed C:\Users\test\Downloads\win64_154519.4678\Graphics\igdlh64.inf
  Checking 4 part DID's
  4ID check OK
!   Didn't find any INF's that match active hardware
IIF will NOT initiate reboot
Exit code = 0xA005
ResultCode = 40965
```

**Comment by Hartmon8** [comment]
i5-7400 is a KBL CPU,  the recent intel graphics driver doesn't support it on Win7.

you may need downgrade GPU driver or use win10 instead.




wangdan1600@163.com
 
From: sy-maqiang
Date: 2018-01-18 15:33
To: intel/gvt-linux
CC: Subscribed
Subject: [intel/gvt-linux] Kaby lake vgpu not support for WIN7 ? (#13)
Hi:
gvt-linux branch: gvt-stable-4.14,
igvtg-qemu branch: stable-2.9.0.
Hardware : Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
I create a vgpu for my win7 VM, but I can't install display driver for this vgpu, there is message in log file:
  [INF Info]
    INF = C:\Users\test\Downloads\win64_154519.4678\Graphics\igdlh64.inf
*   Section <PackageInfo> Key <Sequence> not found in INF
    Date = 05/17/2017
    Version = 21.20.16.4678
    ClassGUID = {4D36E968-E325-11CE-BFC1-08002BE10318}
    PackageInfo.Name = Graphics
    PackageInfo.Sequence = 0
    Manufacturer = IntelGfx,NTamd64.6.1,NTamd64.6.2,NTamd64.6.3,NTamd64.10.0,NTamd64.10.0...14393
    Resolved Manufacturer = IntelGfx.NTamd64.6.1
    Inf supports 64 bit.
    Description: Intel(R) HD Graphics 510
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1906
    Description: Intel(R) HD Graphics 520
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1916
    Description: Intel(R) HD Graphics 515
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_191E
    Description: Intel(R) HD Graphics 530
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1912
    Description: Intel(R) HD Graphics 520
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1921
    Description: Intel(R) Iris(TM) Graphics 540
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1926
    Description: Intel(R) HD Graphics 535
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1923
    Description: Intel(R) Iris(TM) Graphics 550
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1927
    Description: Intel(R) HD Graphics 510
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_1902
    Description: Intel(R) HD Graphics 510
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_190B
    Description: Intel(R) Iris(TM) Pro Graphics 580
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_193B
    Description: Intel(R) Iris(TM) Graphics 555
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_192B
    Description: Intel(R) HD Graphics 530
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_191B
    Description: Intel(R) Iris(TM) Graphics P555
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_192D
    Description: Intel(R) Iris(TM) Pro Graphics P580
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_193A
    Description: Intel(R) HD Graphics P530
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_191D
    Description: Intel(R) Iris(TM) Pro Graphics P580
    HardwareID = iSKLD_w7,PCI\VEN_8086&DEV_193D
  Removed C:\Users\test\Downloads\win64_154519.4678\DisplayAudio\10.22\IntcDAud.inf
  Removed C:\Users\test\Downloads\win64_154519.4678\DisplayAudio\6.16\IntcDAud.inf
  Removed C:\Users\test\Downloads\win64_154519.4678\Graphics\igdlh64.inf
  Checking 4 part DID's
  4ID check OK
!   Didn't find any INF's that match active hardware
IIF will NOT initiate reboot
Exit code = 0xA005
ResultCode = 40965
