### ISSUE TITLE
Code 43 on windows driver of VM on a slackware based build

### ISSUE THREAD

**Issue by springl0aded** [01org/gvt-linux#133]
I a z370+i5-8400 platform which works on Ubuntu 19.10. I installed virt-manager, added the i915.enable_gvt=1 to initramfs, created mediated devices and added them to two VMs and ran them successfully. I only used tightvnc to connect at the moment but it seemed pretty stable.

This was just a test run for me though, my goal was to run this in Unraid, which is based on slackware. So I built a custom kernel (5.3.12) for Unraid adding the required items to the config as modules (CONFIG_DRM_I915_GVT, CONFIG_DRM_I915_GVT_KVMGT, CONFIG_VFIO_MDEV and CONFIG_VFIO_MDEV_DEVICE) because these options were not enabled on unraid by default. Once I did that I was able to modprobe kvmgt and vfio-mdev after boot and created mediated devices as on ubuntu and add them to vms. The vms I use are always seabios based.

The problem is once I boot the Windows 10 VM on this platform the driver has a code 43 in Windows. I've tried reinstalling the driver a number of times and even copying the working vdisk from my ubuntu platform to no avail.

I've looked through both logs, and aside from an entry on the unraid/slackware based side for "[drm] vt-d active for gfx access" that doesn't appear on ubuntu there don't seem to be any real differences with regard to i915 or mdev. But I might be missing something there.

I'm basically out of ideas and don't know how to troubleshoot this further. 

I tried updating the ubuntu kernel to 5.3.12 to see if that would break ubuntu, it did not. 

The qemu versions are slightly different, 4.0 ubuntu versus 4.1.1 on unraid. I can update this but it seems like a longshot.

I don't see anything in the guides that suggest it shouldn't work. 

I use an nvidia card for primary but that is the same on both platforms. Unraid is pretty stripped down with regard to the way it loads video drivers, basically only needing text output. Is the i915 driver required to do things for this to be in a good state and is maybe not doing them on the unraid side?

**Comment by springl0aded** [comment]
I have solved this issue. It seems that I had to change the VM type to Q35-4.1. I had tried 4.0 before to match ubuntu but I believe this has to match the qemu version, at least in this case? Either way I have things works.

**Comment by cxdong** [comment]
Thanks @springl0aded 
Then I will close this issue.
