### ISSUE TITLE
Invalid FORCE_NONPRIV

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [01org/gvt-linux#134]
Running dma-buf + Ubuntu client + Uefi causes the following error sporadically

> vgpu(1) Invalid FORCE_NONPRIV write 10002349 at offset 24dc
> [...]
> INFO: task gvt workload 2:272 blocked for more than 122 seconds.

Files:
------------------
[Ubuntu 19.10 client ISO](https://ubuntu.com/download/desktop/thank-you/?version=19.10&architecture=amd64)
[Libvirt config](https://github.com/intel/gvt-linux/files/4023643/Win10Uefi.txt)
[dmesg attempt 1](https://github.com/intel/gvt-linux/files/4023639/dmesg.txt)
[dmesg attempt 2](https://github.com/intel/gvt-linux/files/4023640/dmesg2.txt)

Host System:
------------------
System: Thinkpad P72
OS: Arch Linux
CPU: Coffee Lake (i7-8750H)
GPU: Optimus system with UHD Graphics 630 + Quadro P600
Driver: xf86-video-intel (1:2.99.917+899+gf66d3954-1) nvidia-dkms (440.44-8)
Kernel: vanilla (5.4.7.arch1-1)

**Comment by blitz** [comment]
There is a commit (3faae9813b9c831356d457c0a5d847b7528bf97a) that seems relevant:

```
commit 3faae9813b9c831356d457c0a5d847b7528bf97a
Author: Tina Zhang <tina.zhang@intel.com>
Date:   Mon Mar 2 16:31:30 2020 +0800

    drm/i915/gvt: Add some regs to force-to-nonpriv whitelist
    
    Those regs are added in order to slove the following complains:
    
     [70811.201818] gvt: vgpu(1) Invalid FORCE_NONPRIV write 2341 at offset 24d8
     [70811.201825] gvt: vgpu(1) Invalid FORCE_NONPRIV write 2351 at offset 24dc
     [70811.201831] gvt: vgpu(1) Invalid FORCE_NONPRIV write 10000d82 at offset 24e0
     [70811.201837] gvt: vgpu(1) Invalid FORCE_NONPRIV write 10064844 at offset 24e4
    
    So solve them by adding the required regs to the whitelist.
    
    Signed-off-by: Tina Zhang <tina.zhang@intel.com>
    Acked-by: Zhenyu Wang <zhenyuw@linux.intel.com>
    Signed-off-by: Zhenyu Wang <zhenyuw@linux.intel.com>
    Link: http://patchwork.freedesktop.org/patch/msgid/20200302083130.17831-1-tina.zhang@intel.com

```

**Comment by fred1gao** [comment]
thanks @blitz .
@TitusLabienus does it works now?

**Comment by blitz** [comment]
@fred1gao Btw, do you know whether fixing these whitelist issues fix functional issues or is it mostly cosmetic?

**Comment by TerrenceXu** [comment]
@blitz, I think it is the latter one, since this issue will not block any function.
