### ISSUE TITLE
Random hangs for a few seconds to minutes with "Next page table ptr is invalid" error

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [01org/gvt-linux#136]
The system hangs at times for a few secs up to a few minutes. In the dmesg log I got the following errors:

> [27236.662644] DMAR: DRHD: handling fault status reg 3
> [27236.662650] DMAR: [DMA Write] Request device [00:02.0] PASID ffffffff fault addr fffffffef8004000 [fault reason 07] Next page table ptr is invalid
> [27242.739733] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0

Files
------------------
[dmesg.txt](https://github.com/intel/gvt-linux/files/4031307/dmesg.txt)
[Win10Uefi.txt](https://github.com/intel/gvt-linux/files/4031308/Win10Uefi.txt)

Client System:
------------------
OS: Windows 10
Firmware: Uefi

Host System:
------------------
System: Thinkpad P72
OS: Arch Linux
CPU: Coffee Lake (i7-8750H)
GPU: Optimus system with UHD Graphics 630 + Quadro P600
Driver: xf86-video-intel (1:2.99.917+899+gf66d3954-1) nvidia-dkms (440.44-8)
Kernel: vanilla (5.4.7.arch1-1)

**Comment by TerrenceXu** [comment]
Can you try the latest 5.5 kernel? it is much more stable than 5.4. 
BTW, suggest we use "intel_iommu=igfx_off" but not "intel_iommu=on" in host grub to avoid some DMAR errors.

**Comment by ChristophSchmidpeter** [comment]
@TerrenceXu 
Thank you, somehow I accidentally set intel_iommu=on instead of igfx_off. I will try it with the latter setting and see/report if it helps. I'll also test it with 5.5 when it will have been released. Or do you mean the latest release candidate?

**Comment by Azkali** [comment]
I also had this issue with linux5.4.18-1. 
Installing linux5.5.2-1 and using `intel_iommu=igfx_off` fixed it, no error show up in log.

CPU/iGPU : Intel m3 7y30 - Intel HD 615
Host: 5.5.2-1-Manjaro GNOME
Guest: Latest Windows 10
Drivers : Latest Intel gfx driver
