### ISSUE TITLE
Output directly to display from mediated device in VM

### ISSUE THREAD

**Issue by springl0aded** [01org/gvt-linux#138]
I gather this was at least a feature in an early version. Is this upstreamed into the kernel? Is there any way to get the virtual stream to output to a monitor currently?

**Comment by TerrenceXu** [comment]
Yes, direct display be supported in our early non-upstream version it support. But it still not be upstreamed until now, thanks. :)

**Comment by springl0aded** [comment]
Thanks for the the information. I'll keep an eye out.

I found that a USB displaylink device in mirror mode is a decent enough alternative for this feature, seems to work OK so far.

**Comment by marcel-apf** [comment]
> Thanks for the the information. I'll keep an eye out.
> 
> I found that a USB displaylink device in mirror mode is a decent enough alternative for this feature, seems to work OK so far.

Hi, the approach can be very handy, can you please explain more about how you made this work?
Thanks,
Marcel

**Comment by springl0aded** [comment]
> Hi, the approach can be very handy, can you please explain more about how you made this work?
> Thanks,
> Marcel

There's actually not a ton to it, once you have gvt-g working its basically just setting up displaylink like you would on a real machine.

I am passing through a pci-e USB 3.0 card in addition to the mdev gpu slice. I used a guest install VNC server to configure it. Then I installed a displaylink adapter to the USB card, installed the displaylink drivers and set the displays to mirror.

So far I'd say the result is very good to great, but I can tell its not perfect. I honestly can't see any quality loss in the image, but I suspect I'm dropping some frames occasionally when watching video. I'd prefer to directly output to one of the igpu outputs. I believe the USB adapter is using more cpu/gpu resources than direct output would, but its not horrible. One nice aspect is the device has its own sound so the hdmi output has sound now, which I wouldn't expect to work with direct display output.

**Comment by marcel-apf** [comment]
@springl0aded, appreciated!
I got it backwards :)
I thought  you actually passed the vgpu output to the guest as an emulated USB video card supporting display-link, e.g. found an alternative for gvt-g direct display.

**Comment by ChristophSchmidpeter** [comment]
> Yes, direct display be supported in our early non-upstream version it support. But it still not be upstreamed until now, thanks.

 Great to hear! That sounds very interesting to me, having a lot of stuttering/flickering/delay etc. via indirect mode.

@TerrenceXu What do you mean with _upstream_ in this context, though? Do you mean the Thorvalds repo, or the public gvt-g one? Is it possible at the moment to get it working with the public gvt-g repo (e.g. out-of the box or via patch)?

**Comment by solnyshok** [comment]
hi, any news on this?

**Comment by TinaZhangZW** [comment]
The upstream prefers the indirect display based on dma-buf.  And so far, no plan for upstreaming direct display.

**Comment by tristan-k** [comment]
Can someone explain how to set up the direct display non-upstream version?

**Comment by renne** [comment]
@TerrenceXu
@TinaZhangZW 
I'm also very interested in using the two IGD Displayport outputs in two different virtual machines and the DVI output for the Proxmox host.
