### ISSUE TITLE
Coffeelake 9000 series support

### ISSUE THREAD

**Issue by springl0aded** [01org/gvt-linux#139]
I know that at least 8000 series is supported in recent kernels, I believe 5.1 has been quoted as its introduction and I have it working on an i5-8400. Does this mean it is supported on 9 series iGPUs as well? I only ask because so far I have not found a report some one using it on that particular platform. I'm thinking of upgrading to an 8 core but if I lost this feature I probably wouldn't bother.

**Comment by TerrenceXu** [comment]
We support all Coffleeake related GPU generations, can you provide your PCIID on your 9 series machine? you can check it by "lspci" .

**Comment by springl0aded** [comment]
Thanks, I don't have the hardware yet. Just wanted to make sure of support before purchase. I'm looking at a 9700K most likely, it has a hardware id of 0x3E98 for the iGPU according to intel ark.
