### ISSUE TITLE
Supported Processor and NUC devices? 

### ISSUE THREAD

**Issue by incube8r** [01org/gvt-linux#145]
Which are the processor supported by GVT-g? 

1. Is Skylake-U supported? 
2. Are these architecture supported:
- Kaby Lake-U (Baby Canyon)
- Kaby Lake-U (Dawson Canyon)
- Kaby Lake-R (Dawson Canyon)

Also
- Broadwell-U
- Braswell

Are supported? 

For Intel NUC devices is there a comprehensive live of supported units?

**Comment by BankaiNoJutsu** [comment]
All arch's in this file (should) work:
https://github.com/intel/gvt-linux/blob/gvt-staging/drivers/gpu/drm/i915/intel_gvt.c

Others won't

**Comment by SunbrightShinobi** [comment]
Would it be possible to have that list added to repo wiki page and maintained or at least a call out to that file

**Comment by TerrenceXu** [comment]
@incube8r, Broadwell / Skylake / Kabylake / Coffeelake / Whiskey lake / Cometlake, and so on. :)
@binarylandscapes, no problem.
