### ISSUE TITLE
Windows 10 guest crashed after install Intel driver

### ISSUE THREAD

**Issue by RMTT** [01org/gvt-linux#147]
Host
OS: Archlinux + kernel 5.5.13-arch2-1 + libvirtd (libvirt) 5.10.0 + qemu/kvm
CPU：i7 6700HQ
GPU: Intel® HD Graphics 530
Memory: 16G DDR4 + 8G DDR4

Guest:
OS： Windows 10
Driver Version: Intel® Graphics - Windows® 10 DCH Drivers 26.20.100.7985

my win10.xml about the vgpu:
```xml
    <graphics type="spice" autoport="yes">
      <listen type="address"/>
    </graphics>
    <graphics type="egl-headless">
      <gl rendernode="/dev/dri/by-path/pci-0000:00:02.0-render"/>
    </graphics>
       <video>
      <model type="none"/>
    </video>

      <qemu:commandline>
    <qemu:arg value="-set"/>
    <qemu:arg value="device.hostdev1.x-igd-opregion=on"/>
    <qemu:arg value="-set"/>
    <qemu:arg value="device.hostdev1.romfile=/var/lib/libvirt/images/vbios_gvt_uefi.rom"/>
    <qemu:arg value="-set"/>
    <qemu:arg value="device.hostdev1.ramfb=on"/>
    <qemu:arg value="-set"/>
    <qemu:arg value="device.hostdev1.driver=vfio-pci-nohotplug"/>
  </qemu:commandline>

<hostdev mode="subsystem" type="mdev" managed="no" model="vfio-pci" display="on">
  <source>
    <address uuid="6a95852f-a912-4b6c-a171-9d34e7a86593"/>
  </source>
  <alias name="hostdev1"/>
  <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
</hostdev>

```

After install the intel driver, the guest autimatically reboot too many times and the into the recovery mode
![image](https://user-images.githubusercontent.com/20596599/78422360-4220c200-7691-11ea-8ab2-3ef489a48e17.png)

I find some errors via dmesg
```
[ 4327.633511] gvt: vgpu 1: scan wa ctx error
[ 4327.633516] GVT Internal error  for the guest
[ 4327.633516] Now vgpu 1 will enter failsafe mode.
[ 4327.633518] gvt: vgpu 1: failed to submit desc 0
[ 4327.633518] gvt: vgpu 1: fail submit workload on ring 0
[ 4327.633520] gvt: vgpu 1: fail to emulate MMIO write 00002230 len 4
```

But i cannot find some precise solution for those errors .Is this a configuration error, or a bug?

**Comment by mike-vivas** [comment]
Hi,
I have exactly the same problem. Can it be related to this known issue https://github.com/intel/gvt-linux/issues/130?
in dmesg there should be the "len is not valid" error just a couple of lines above those you posted.
Still hoping for another fix rather than changing the source code as proposed in the link above

**Comment by RMTT** [comment]
> Still hoping for another fix rather than changing the source code as proposed in the link above

I haven't find other solutions, just also dual boot instead. And it will cause other issues after enable the gvt-g, such like blinking screen, also haven't a precise solution.

**Comment by zhenyw** [comment]
does this happen with more recent stable kernel version? and better paste full dmesg log to know what might cause that wa ctx scan error.

**Comment by RMTT** [comment]
> does this happen with more recent stable kernel version? and better paste full dmesg log to know what might cause that wa ctx scan error.

sorry, i have give up the gvt so long :)

**Comment by TerrenceXu** [comment]
Close it since it is old Windows GFX driver issue.
