### ISSUE TITLE
Install Instructions Nonfunctional

### ISSUE THREAD

**Issue by quantum77** [01org/gvt-linux#15]
I have tried literally for years, many times to get KVMGT working, but have never succeeded.  I run CentOS 7.4 as host and most guests.  I've run Linux exclusively for 22 years, and work in enterprise infosec, so I don't think the problem is me.

Today I followed the instructions here:
https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide

I didn't compile KVM from scratch, I installed from the repo.  I did install the elrepo kernel-ml-nosrc and the matching source from kernel.org. (4.14.14)  It was necessary to compile the kernel as elrepo's kernel-ml config does not have the proper drivers turned on.

So I turned on all CONFIG_VFIO_* options, CONFIG_DRM_I915_GVT, and CONFIG_DRM_I915_GVT_KVMGT, compiled, installed, and booted the kernel.

There is nothing in the instructions about needing to load the drivers at boot, but I set them in Dracut anyway.  They were in ininitramfs, but they didn't survive the boot to be loaded in the running system for some reason. Then I entered those same modules in /etc/modules.conf.d/vfio.conf:
irqbypass
vfio
vfio_iommu_type1
vfio_virqfd
vfio-pci
mdev
vfio-mdev
kvmgt

... and they do load after boot.  But _there is no /sys/class/mdev_bus directory_!  What is wrong with this picture?  Clearly I can't go any further without this.

In BIOS I have Virtualization on, and VTd on.  The mobo is a new Asus Prime Z270M Plus, with the latest BIOS installed (v 102).  CPU is an Intel Xeon Core i7-6700T CPU @ 2.80GHz.

Also BTW, I can not get SR-IOV working on this mobo, whereas I could when I used the Intel 4-port ethernet card in a SuperMicro mobo.

Attached is the lshw and lspci -k

[lshw.tar.gz](https://github.com/intel/gvt-linux/files/1657779/lshw.tar.gz)
[lspci-k.tar.gz](https://github.com/intel/gvt-linux/files/1657781/lspci-k.tar.gz)

**Comment by TerrenceXu** [comment]
Hello, your machine is support KVMGT. Can you find vgpu type under  “/sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/”?, if still no, you can also provide your kernel build configuration and your grub. ☺

Thanks
Terrence
