### ISSUE TITLE
Not compiling Build Qemu & Xen for XenGT under Ubuntu 18.04.4 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by 65816** [01org/gvt-linux#151]
Following directions under 3.3.2:

make -j8 xen tools

Unable to get past this.

make[5]: Entering directory '/root/igvtg-xen/tools/qemu-xen-traditional-dir-remote/i386-dm'
=== PCI passthrough capability has been enabled ===
=== PCI passthrough capability has been enabled ===
/root/igvtg-xen/tools/../tools/cross-install -d -m0755 -p "/root/igvtg-xen/dist/install//usr/lib/xen/bin"
/root/igvtg-xen/tools/../tools/cross-install -d -m0755 -p "/root/igvtg-xen/dist/install//etc/xen/scripts"
/root/igvtg-xen/tools/../tools/cross-install -m0755 -p ../i386-dm/qemu-ifup-Linux "/root/igvtg-xen/dist/install//etc/xen/scripts/qemu-ifup"
/root/igvtg-xen/tools/../tools/cross-install -m0755 -p  qemu-dm "/root/igvtg-xen/dist/install/usr/lib/xen/bin"
make[5]: Leaving directory '/root/igvtg-xen/tools/qemu-xen-traditional-dir-remote/i386-dm'
make[4]: Leaving directory '/root/igvtg-xen/tools/qemu-xen-traditional-dir-remote'
make[3]: Leaving directory '/root/igvtg-xen/tools'
make[3]: Entering directory '/root/igvtg-xen/tools'
if test -d file://localhost/root/igvtg-xen/igvtg-qemu ; then \
        mkdir -p qemu-xen-dir; \
else \
        export GIT=git; \
        /root/igvtg-xen/tools/../scripts/git-checkout.sh file://localhost/root/igvtg-xen/igvtg-qemu origin/stable-2.10.0 qemu-xen-dir ; \
fi
Cloning into 'qemu-xen-dir-remote.tmp'...
remote: Counting objects: 361946, done.
remote: Compressing objects: 100% (66302/66302), done.
remote: Total 361946 (delta 294814), reused 361928 (delta 294803)
Receiving objects: 100% (361946/361946), 125.40 MiB | 43.07 MiB/s, done.
Resolving deltas: 100% (294814/294814), done.
fatal: 'origin/stable-2.10.0' is not a commit and a branch 'dummy' cannot be created from it
Makefile:197: recipe for target 'qemu-xen-dir-find' failed
make[3]: *** [qemu-xen-dir-find] Error 128
make[3]: Leaving directory '/root/igvtg-xen/tools'
/root/igvtg-xen/tools/../tools/Rules.mk:241: recipe for target 'subdirs-install' failed
make[2]: *** [subdirs-install] Error 2
make[2]: Leaving directory '/root/igvtg-xen/tools'
Makefile:68: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/root/igvtg-xen/tools'
Makefile:127: recipe for target 'install-tools' failed
make: *** [install-tools] Error 2

**Comment by 65816** [comment]
Found the fix:

`sed -i 's/\(QEMU_UPSTREAM_REVISION ?= \).*/\1origin\/stable-2.12.0/g' Config.mk
`

**Comment by TerrenceXu** [comment]
@65816, thank you!
