### ISSUE TITLE
Garbled screen for Win10 OVMF guest in GVT-g mode

### ISSUE THREAD

**Issue by rugubara** [01org/gvt-linux#152]
Hello. 
I'm running a VM that garbles the screen as soon as I move a mouse inside the guest window. I made a [video](https://youtu.be/IqksG-pARPY) as seeing is believing.

The garbled screen clears temporarly when I move or resize a window in the guest.

I run Linux home64 5.6.14-rt-rt7 #3 SMP PREEMPT_RT Tue Jun 2 15:11:48 MSK 2020 x86_64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz GenuineIntel GNU/Linux

**Comment by rugubara** [comment]
When I run the same guest on Linux home64 5.6.15-gentoo #4 SMP Mon Jun 1 13:17:12 MSK 2020 x86_64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz GenuineIntel GNU/Linux (with the same userland) I get normal guest display however the mouse cursor disappears as soon as it enters the guest window.

**Comment by rugubara** [comment]
And also I can see that the mouse cursor is rendered by the guest (it's white) and sometimes it is rendered by the host (it's black and it doesn't change the form when resizing windows and in other cases when windows cursor would change form). How can I control this behaviour?

**Comment by h1ghrise** [comment]
+1 have exactly the same issue.
Setup on an Matebook 13, Intel UHD 620 Graphics. According to the arch Wiki.
Have described this on reddit : https://www.reddit.com/r/VFIO/comments/gvetff/windows_10_vm_intel_uhd_graphics_artifacts_in/

**Comment by h1ghrise** [comment]
check #142 
<qemu:env name="MESA_LOADER_DRIVER_OVERRIDE" value="i965"/>

**Comment by rugubara** [comment]
Closing as a duplicate of #142
