### ISSUE TITLE
Test dmabuf failed

### ISSUE THREAD

**Issue by maqiangddb** [01org/gvt-linux#16]
Hi:
    I was test the dmabuf feature of gvt-g. 
    kernel branch :gvt-stable-4.14
    qemu branch : stable-2.10.0

    qemu command:
```
qemu-system-x86_64 -m 1024 -smp 2 \
    -bios /opt/qemu-kraxel/bin/bios.bin -enable-kvm \
    -debugcon file:/var/log/bios.log -global isa-debugcon.iobase=0x402 -monitor stdio \
    -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 \
    -M pc -machine kernel_irqchip=on \
    -vga qxl -k en-us -cpu host \
    -display sdl,gl=on \
    -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/9f83f7a5-823d-45dc-88b8-659c55cab487,rombar=0,x-display=on \
    -net nic,macaddr=00:A1:00:00:00:1A -net tap,script=/usr/bin/qemu-ifup \
    -hda /home/mq/vm-img/win10.qcow2 \
    -boot menu=on 
```

    VM running log:
```
sdl2_window_create:98: SDL_GL_CONTEXT_EGL 0
sdl2_window_create:98: SDL_GL_CONTEXT_EGL 0
sdl2_window_create:98: SDL_GL_CONTEXT_EGL 0
vfio_display_get_dmabuf: new dmabuf: id 1, res 1024x768, format XR24, plane primary, fd 23, hot +-14080+16777216
primary plane not initialized by guest
```

   When win10 start load IGD driver, "primary plane not initialized by guest " start print !
   If I missing something? 

   I check through the kernel source, found that the DSPCNTR register value is : 84000000, after win10 load IGD driver, the value is changed to : 04000000. And DSPSURF register is still 00000000. Why?

**Comment by maqiangddb** [comment]
By the way, I still can connect VM with vncviewer. And IGD running normally!

**Comment by TerrenceXu** [comment]
Close it and focus on the latest kernel.
