### ISSUE TITLE
fail to alloc high gm space from host 

### ISSUE THREAD

**Issue by nick-kvmhv** [01org/gvt-linux#164]
I tried to set up a multiple VM server on kernel version 5.7 where each VM has its own virtual GPU guid and those adapters are created dynamically via QEMU hooks. After a few virtual GPUs are allocated and destroyed I am starting getting the "fail to alloc high gm space from host" error:
```
[122432.080900] gvt: fail to alloc high gm space from host
[122432.081027] gvt: failed to create intel vgpu: -28
```
The error is reproducible with the python script below. It fails when trying to create the g2 adapter 2nd time. Is it something that can be fixed or do I have to create all adapters just once and then do some sort of VM to guid mapping?
```
#!/usr/bin/python
import os.path, time
from os import path
import datetime
import os
import json
import sys
import math

from xml.etree import ElementTree

create_path = "/sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create"
destroy_path = "/sys/bus/pci/devices/0000:00:02.0/"

def activate(guid_str):
	dev = os.open(create_path, os.O_WRONLY)
	os.write(dev,guid_str)
	os.close(dev)
	
def deactivate(guid_str):
	driverpath = destroy_path + guid_str + "/remove"
	print "deactivating in {}".format(driverpath)
	dev = os.open(driverpath, os.O_WRONLY)
	os.write(dev,"1")
	os.close(dev)

def main():
	g1 = "81c01daf-d7f7-4e9b-b794-3f9684c829ae"
	g2 = "92bf7f58-0e81-440f-9fcb-06cd082c3ab4"
	g3 = "6b274fc0-2ada-4938-81d9-6e40e9c677f0"
	activate(g1)
	activate(g2)
	activate(g3)

	deactivate(g1)
	deactivate(g2)
	activate(g1)
	activate(g2)


	deactivate(g3)

	deactivate(g2)
	deactivate(g1)


if __name__== "__main__":
   main()

```

CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz

**Comment by TerrenceXu** [comment]
@nick-kvmhv You can check https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide#53-create-vgpu-kvmgt-only, it due to the high gm size already not enough, you need to remove old vgpu first.

**Comment by nick-kvmhv** [comment]
I have enough ram for 3 VGPUs and my problem is that I have to remove all 3 before I can re-create them. I cannot leave one running, remove two and then re-create those two. They all have exactly the same vram size.
