### ISSUE TITLE
is Gvt-g migratable?

### ISSUE THREAD

**Issue by up0617** [01org/gvt-linux#166]
Hi, 
I'm trying to migrate mediated passthrough gpu enabled vm using libvirtd ans below error msg is shown. 
```
libvirtError: Requested operation is not valid: domain has assigned non-USB host devices
```
and found that in libvirt,  "Migration with USB host devices is allowed, all other devices are forbidden"

Is there any chance to migrate gvt-g enabled vm by other tools or it is not available now?

**Comment by TerrenceXu** [comment]
@up0617, only gvt-stable-4.17 code (https://github.com/intel/gvt-linux/tree/gvt-stable-4.17) support live migration, and you also need to use special qemu code (https://github.com/intel/Igvtg-qemu/tree/stable-2.12.0), the latest code not support it since this feature hasn't been upstreamed.

**Comment by oryair1** [comment]
Hi, I am using both a linux version and a qemu version which contain the code for the migration but I am still getting:
`Error: VFIO device doesn't support migration`
When I am trying to create a snapshot with qemu
