### ISSUE TITLE
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]

### ISSUE THREAD

**Issue by Marietto2008** [01org/gvt-linux#167]
I'm trying to Build Qemu & Xen for XenGT on Ubuntu 20.04. My hardware are : 

CPU I9-9900k ; 

00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 630 (Desktop 9 Series) (rev 02) ;

01:00.0 VGA compatible controller: NVIDIA Corporation TU102 [GeForce RTX 2080 Ti] (rev a1)
01:00.1 Audio device: NVIDIA Corporation TU102 High Definition Audio Controller (rev a1)
01:00.2 USB controller: NVIDIA Corporation TU102 USB 3.1 Host Controller (rev a1)
01:00.3 Serial bus controller [0c80]: NVIDIA Corporation TU102 USB Type-C UCSI Controller (rev a1)

I have reached this point :

root@ziomario-z390aoruspro:/etc/xen/igvtg-xen# make install-tools

......
make libs
make[5]: ingresso nella directory «/etc/xen/igvtg-xen/tools/libxc»
rm -f _paths.h.tmp;  echo "#define sbindir \"/usr/sbin\"" >>_paths.h.tmp;  echo "#define bindir \"/usr/bin\"" >>_paths.h.tmp;  echo "#define LIBEXEC \"/usr/lib/xen\"" >>_paths.h.tmp;  echo "#define LIBEXEC_BIN \"/usr/lib/xen/bin\"" >>_paths.h.tmp;  echo "#define libdir \"/usr/lib\"" >>_paths.h.tmp;  echo "#define SHAREDIR \"/usr/share\"" >>_paths.h.tmp;  echo "#define XENFIRMWAREDIR \"/usr/lib/xen/boot\"" >>_paths.h.tmp;  echo "#define XEN_CONFIG_DIR \"/etc/xen\"" >>_paths.h.tmp;  echo "#define XEN_SCRIPT_DIR \"/etc/xen/scripts\"" >>_paths.h.tmp;  echo "#define XEN_LOCK_DIR \"/var/lock\"" >>_paths.h.tmp;  echo "#define XEN_RUN_DIR \"/var/run/xen\"" >>_paths.h.tmp;  echo "#define XEN_PAGING_DIR \"/var/lib/xen/xenpaging\"" >>_paths.h.tmp;  echo "#define XEN_DUMP_DIR \"/var/lib/xen/dump\"" >>_paths.h.tmp;  echo "#define XEN_LOG_DIR \"/var/log/xen\"" >>_paths.h.tmp;  echo "#define XEN_LIB_DIR \"/var/lib/xen\"" >>_paths.h.tmp;  echo "#define XEN_RUN_STORED \"/var/run/xenstored\"" >>_paths.h.tmp; 	if ! cmp -s _paths.h.tmp _paths.h; then mv -f _paths.h.tmp _paths.h; else rm -f _paths.h.tmp; fi
gcc  -m64 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs   -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .xc_pm.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE  -I../../xen/common/libelf -Werror -Wmissing-prototypes -I. -I./include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/include -D__XEN_TOOLS__ -pthread -I/etc/xen/igvtg-xen/tools/libxc/../../tools/libs/toollog/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/libs/evtchn/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/libs/devicemodel/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/include -include /etc/xen/igvtg-xen/tools/libxc/../../tools/config.h -I/etc/xen/igvtg-xen/tools/libxc/../../tools/libs/call/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/libs/foreignmemory/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/libs/gnttab/include -I/etc/xen/igvtg-xen/tools/libxc/../../tools/include  -c -o xc_pm.o xc_pm.c 
In file included from /usr/include/string.h:495,
                 from xc_private.h:24,
                 from xc_pm.c:22:
In function ‘strncpy’,
    inlined from ‘xc_set_cpufreq_gov’ at xc_pm.c:308:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [/etc/xen/igvtg-xen/tools/libxc/../../tools/Rules.mk:222: xc_pm.o] Errore 1
make[5]: uscita dalla directory «/etc/xen/igvtg-xen/tools/libxc»
make[4]: *** [Makefile:184: build] Errore 2
make[4]: uscita dalla directory «/etc/xen/igvtg-xen/tools/libxc»
make[3]: *** [/etc/xen/igvtg-xen/tools/../tools/Rules.mk:246: subdir-install-libxc] Errore 2
make[3]: uscita dalla directory «/etc/xen/igvtg-xen/tools»
make[2]: *** [/etc/xen/igvtg-xen/tools/../tools/Rules.mk:241: subdirs-install] Errore 2
make[2]: uscita dalla directory «/etc/xen/igvtg-xen/tools»
make[1]: *** [Makefile:74: install] Errore 2
make[1]: uscita dalla directory «/etc/xen/igvtg-xen/tools»
make: *** [Makefile:127: install-tools] Errore 2

how can I fix this bug ?

**Comment by nevilad** [comment]
According to this https://stackoverflow.com/questions/56253996/why-does-gcc-9-1-0-sometimes-complain-about-this-use-of-strncpy, I would recommend to update your gcc to the latest one.

**Comment by Marietto2008** [comment]
yes,I've installed gcc 10 but I get the same error. I have also installed gcc 8. its the same.

**Comment by nevilad** [comment]
Please paste the first 110 lines of this file /usr/include/x86_64-linux-gnu/bits/string_fortified.h.

**Comment by Marietto2008** [comment]
```
/* Copyright (C) 2004-2020 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <https://www.gnu.org/licenses/>.  */

#ifndef _BITS_STRING_FORTIFIED_H
#define _BITS_STRING_FORTIFIED_H 1

#ifndef _STRING_H
# error "Never use <bits/string_fortified.h> directly; include <string.h> instead."
#endif

#if !__GNUC_PREREQ (5,0)
__warndecl (__warn_memset_zero_len,
	    "memset used with constant zero length parameter; this could be due to transposed parameters");
#endif

__fortify_function void *
__NTH (memcpy (void *__restrict __dest, const void *__restrict __src,
	       size_t __len))
{
  return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
}

__fortify_function void *
__NTH (memmove (void *__dest, const void *__src, size_t __len))
{
  return __builtin___memmove_chk (__dest, __src, __len, __bos0 (__dest));
}

#ifdef __USE_GNU
__fortify_function void *
__NTH (mempcpy (void *__restrict __dest, const void *__restrict __src,
		size_t __len))
{
  return __builtin___mempcpy_chk (__dest, __src, __len, __bos0 (__dest));
}
#endif


/* The first two tests here help to catch a somewhat common problem
   where the second and third parameter are transposed.  This is
   especially problematic if the intended fill value is zero.  In this
   case no work is done at all.  We detect these problems by referring
   non-existing functions.  */
__fortify_function void *
__NTH (memset (void *__dest, int __ch, size_t __len))
{
  /* GCC-5.0 and newer implements these checks in the compiler, so we don't
     need them here.  */
#if !__GNUC_PREREQ (5,0)
  if (__builtin_constant_p (__len) && __len == 0
      && (!__builtin_constant_p (__ch) || __ch != 0))
    {
      __warn_memset_zero_len ();
      return __dest;
    }
#endif
  return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
}

#ifdef __USE_MISC
# include <bits/strings_fortified.h>

void __explicit_bzero_chk (void *__dest, size_t __len, size_t __destlen)
  __THROW __nonnull ((1));

__fortify_function void
__NTH (explicit_bzero (void *__dest, size_t __len))
{
  __explicit_bzero_chk (__dest, __len, __bos0 (__dest));
}
#endif

__fortify_function char *
__NTH (strcpy (char *__restrict __dest, const char *__restrict __src))
{
  return __builtin___strcpy_chk (__dest, __src, __bos (__dest));
}

#ifdef __USE_GNU
__fortify_function char *
__NTH (stpcpy (char *__restrict __dest, const char *__restrict __src))
{
  return __builtin___stpcpy_chk (__dest, __src, __bos (__dest));
}
#endif


__fortify_function char *
__NTH (strncpy (char *__restrict __dest, const char *__restrict __src,
		size_t __len))
{
  return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
}

/* XXX We have no corresponding builtin yet.  */
extern char *__stpncpy_chk (char *__dest, const char *__src, size_t __n,
			    size_t __destlen) __THROW;
extern char *__REDIRECT_NTH (__stpncpy_alias, (char *__dest, const char *__src,
					       size_t __n), stpncpy);

__fortify_function char *
__NTH (stpncpy (char *__dest, const char *__src, size_t __n))
{
  if (__bos (__dest) != (size_t) -1
      && (!__builtin_constant_p (__n) || __n > __bos (__dest)))
    return __stpncpy_chk (__dest, __src, __n, __bos (__dest));
  return __stpncpy_alias (__dest, __src, __n);
}


__fortify_function char *
__NTH (strcat (char *__restrict __dest, const char *__restrict __src))
{
  return __builtin___strcat_chk (__dest, __src, __bos (__dest));
}


__fortify_function char *
__NTH (strncat (char *__restrict __dest, const char *__restrict __src,
		size_t __len))
{
  return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));
}

#endif /* bits/string_fortified.h */
```

**Comment by Marietto2008** [comment]
I'm also in contact with https://github.com/marxin that he is helping me. He suggests to try this :

Anyway one workaround can be removal of the always_inline attribute from the problematic functions.

**Comment by nevilad** [comment]
Yes, this can help. Or to use gcc before version 8.

**Comment by Marietto2008** [comment]
is complicated for you to remove the "always_inline" attribute from the problematic functions ?

**Comment by Marietto2008** [comment]
I've installed GCC 7. I have re tried the compilation. this is what happened : 

make -C x86_instruction_emulator install
make[6]: ingresso nella directory «/etc/xen/igvtg-xen/tools/fuzz/x86_instruction_emulator»
[ -L x86-emulate.c ] || ln -sf /etc/xen/igvtg-xen/tools/fuzz/x86_instruction_emulator/../../../tools/tests/x86_emulator/x86-emulate.c
gcc  -m64 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs   -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .x86-emulate.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE   -I/etc/xen/igvtg-xen/tools/fuzz/x86_instruction_emulator/../../../tools/include -D__XEN_TOOLS__ -I.  -c -o x86-emulate.o x86-emulate.c 
ar rc x86-insn-fuzzer.a fuzz-emul.o x86-emulate.o
gcc  -m64 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs   -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .afl-harness.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE   -I/etc/xen/igvtg-xen/tools/fuzz/x86_instruction_emulator/../../../tools/include -D__XEN_TOOLS__ -I.  -c -o afl-harness.o afl-harness.c 
gcc -m64 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs   -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .afl-harness.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE   -I/etc/xen/igvtg-xen/tools/fuzz/x86_instruction_emulator/../../../tools/include -D__XEN_TOOLS__ -I. afl-harness.o fuzz-emul.o x86-emulate.o -o afl-harness
fuzz-emul.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status

**Comment by nevilad** [comment]
The erroneous function has no __attribute__((always_inline)). It is inlined due to gcc flags. Try to add `-fno-inline-small-functions` option to gcc command line.
This is your gcc command line from the log above:
`gcc -m64 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs -O2 -fomit-frame-pointer -`

Try to find build scripts which contain these flags, for example `-Wno-unused-local-typedefs` and add after it a space and `-fno-inline-small-functions`.

**Comment by Marietto2008** [comment]
I gave this command :

root@ziomario-z390aoruspro:/etc/xen/igvtg-xen/tools/fuzz/x86_instruction_emulator# gcc  -m64 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs   -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .fuzz-emul.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE   -I/etc/xen/igvtg-xen/tools/fuzz/x86_instruction_emulator/../../../tools/include -D__XEN_TOOLS__ -I.  -c -o fuzz-emul.o fuzz-emul.c -fno-inline-small-functions

root@ziomario-z390aoruspro:/etc/xen/igvtg-xen/tools

nothing happened. anyway,I didn't see errors. I re tried to make install-tools and I saw progress. The error of before is gone and the compilation goes further. now this is the new situation :

make[11]: ingresso nella directory «/etc/xen/igvtg-xen/tools/firmware/rombios/32bit/tcgbios»
gcc   -m32 -march=i686 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs   -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .tcgbios.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -mno-tls-direct-seg-refs  -DNDEBUG -Werror -fno-stack-protector -fno-exceptions -fno-builtin -msoft-float -I/etc/xen/igvtg-xen/tools/firmware/rombios/32bit/tcgbios/../../../../../tools/include -I.. -I../.. -I../../../../libacpi -fno-pic -fno-PIE  -c -o tcgbios.o tcgbios.c 
In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9:0,
                 from ../../../../libacpi/acpi2_0.h:17,
                 from ../util.h:4,
                 from tcgbios.c:26:
/usr/include/stdint.h:26:10: fatal error: bits/libc-header-start.h: File o directory non esistente
 #include <bits/libc-header-start.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by Marietto2008** [comment]
from my ignorance,I presume that I should change the gcc compiler from 7 to 9 ? :D

**Comment by nevilad** [comment]
Yes, sure )) To any gcc that compiles the code with `error: ‘__builtin_strncpy’ specified bound 16 equals destination size [-Werror=stringop-truncation]`

**Comment by Marietto2008** [comment]
with GCC 9 :

make[11]: ingresso nella directory «/etc/xen/igvtg-xen/tools/firmware/rombios/32bit/tcgbios»
gcc   -m32 -march=i686 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs   -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .tcgbios.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -mno-tls-direct-seg-refs  -DNDEBUG -Werror -fno-stack-protector -fno-exceptions -fno-builtin -msoft-float -I/etc/xen/igvtg-xen/tools/firmware/rombios/32bit/tcgbios/../../../../../tools/include -I.. -I../.. -I../../../../libacpi -fno-pic -fno-PIE  -c -o tcgbios.o tcgbios.c 
In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9,
                 from ../../../../libacpi/acpi2_0.h:17,
                 from ../util.h:4,
                 from tcgbios.c:26:
/usr/include/stdint.h:26:10: fatal error: bits/libc-header-start.h: File o directory non esistente
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by Marietto2008** [comment]
fixed with this : sudo apt-get install gcc-multilib

this is the new situation : 

gcc   -m32 -march=i686 -DBUILD_ID -fno-strict-aliasing -std=gnu99 -Wall -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-but-set-variable -Wno-unused-local-typedefs   -O2 -fomit-frame-pointer -D__XEN_INTERFACE_VERSION__=__XEN_LATEST_INTERFACE_VERSION__ -MMD -MF .tcgbios.o.d -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -mno-tls-direct-seg-refs  -DNDEBUG -Werror -fno-stack-protector -fno-exceptions -fno-builtin -msoft-float -I/etc/xen/igvtg-xen/tools/firmware/rombios/32bit/tcgbios/../../../../../tools/include -I.. -I../.. -I../../../../libacpi -fno-pic -fno-PIE  -c -o tcgbios.o tcgbios.c 
tcgbios.c: In function ‘TCGInterruptHandler’:
tcgbios.c:1519:33: error: taking address of packed member of ‘struct <anonymous>’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1519 |                                 &regs->u.r32.edx);
      |                                 ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

**Comment by Marietto2008** [comment]
the solution seems to be here : 

https://bugs.gentoo.org/689082

and here : 

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c58b86194ce19d54a2f47d4712cb237b1f880ebb

but it is too much complicated for me to apply the patches suggested. can u help me ?

**Comment by Marietto2008** [comment]
Since you have fixed the previous error and now we have a different error,we can continue here :

https://github.com/intel/gvt-linux/issues/168

**Comment by TerrenceXu** [comment]
duplicate to #168
