### ISSUE TITLE
../../libacpi/build.c:384:49: error: ‘ssdt_pm’ undeclared (first use in this function); did you mean ‘ssdt’?

### ISSUE THREAD

**Issue by Marietto2008** [01org/gvt-linux#169]
I would like to pass the integrated gpu from the host os (ubuntu 20.04) to the windows 10 guest os with xen. This is because xen works great for me,better than qemu-kvm for my specific needs and because I have only two graphic cards. The nvidia rtx 2080 ti that I have already passed to the guest,and the intel UHD 630,that can be duplicated from the host to the guest so that it can be used in both places without interruptions. So I'm trying to build this repository :

https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide#332-build-qemu--xen-for-xengt

but at some point,I get these errors :

../../libacpi/build.c: In function ‘construct_secondary_tables’:
../../libacpi/build.c:384:49: error: ‘ssdt_pm’ undeclared (first use in this function); did you mean ‘ssdt’?
384 | ssdt = ctxt->mem_ops.alloc(ctxt, sizeof(ssdt_pm), 16);
| ^~~~~~~
| ssdt
../../libacpi/build.c:384:49: note: each undeclared identifier is reported only once for each function it appears in
../../libacpi/build.c:392:49: error: ‘ssdt_s3’ undeclared (first use in this function); did you mean ‘ssdt’?
392 | ssdt = ctxt->mem_ops.alloc(ctxt, sizeof(ssdt_s3), 16);
| ^~~~~~~
| ssdt
../../libacpi/build.c:402:49: error: ‘ssdt_s4’ undeclared (first use in this function); did you mean ‘ssdt’?
402 | ssdt = ctxt->mem_ops.alloc(ctxt, sizeof(ssdt_s4), 16);
| ^~~~~~~
| ssdt
../../libacpi/build.c:412:49: error: ‘ssdt_laptop_slate’ undeclared (first use in this function); did you mean ‘ssdt
_laptop_slate_aml_code’?
412 | ssdt = ctxt->mem_ops.alloc(ctxt, sizeof(ssdt_laptop_slate), 16);
| ^~~~~~~~~~~~~~~~~
| ssdt_laptop_slate_aml_code
../../libacpi/build.c:426:49: error: ‘ssdt_tpm’ undeclared (first use in this function)
426 | ssdt = ctxt->mem_ops.alloc(ctxt, sizeof(ssdt_tpm), 16);
| ^~~~~~~~

do u know if there is a patch ? where I can get it ? how can I fix these errors ? very thanks.

This is the content of the file build.c

https://pastebin.com/sUFp4N8V

**Comment by TerrenceXu** [comment]
duplicate to #168.
