### ISSUE TITLE
[Success] GVT-g w/ dmabuf works on Archlinux

### ISSUE THREAD

**Issue by XaeroVincent** [01org/gvt-linux#17]
This isn't an issue report. Just reporting that GVT-g appears to be working on my Dell i7 Skylake laptop with Intel HD 520 graphics. Pretty exciting stuff.

This is with the gvt 4.15 kernel and qvt qemu 2.10 and I compiled into Archlinux PKGBUILD packages for easy installation and removal. It works, although it is a bit unstable and sometimes causes the guest and/or host to freeze for several seconds or graphics corruption. More baking is needed on the dmabuf framebuffer redirection stuff but fun stuff. I'm going to try running some 3D tests soon as it appears to expose DirectX 11 & 12.

<img src="https://steamuserimages-a.akamaihd.net/ugc/940559895201371968/912F19AFC055C3AECD75537D52A9F32380299B4B/" style="max-width:100%" alt="GVT-g">

**Comment by DocMAX** [comment]
Could you please provide everything needed to build this setup? Cant wait to see it work here.
Can you provide the PKGBUILD?

**Comment by TerrenceXu** [comment]
Hello, you can follow below guide,

https://github.com/intel/gvt-linux/wiki/Dma_Buf_User_Guide

**Comment by DocMAX** [comment]
The guide doesnt describe how to compile on arch linux.

**Comment by teknoman117** [comment]
any idea on how to get a resolution >1920x1200?

**Comment by TerrenceXu** [comment]
We are not support resolution >1920x1200 for now.
