### ISSUE TITLE
[Benchmark] Unigine Tropics w/ Intel GVT-g

### ISSUE THREAD

**Issue by XaeroVincent** [01org/gvt-linux#18]
This is a benchmark testing the performance of an Intel HD 520 found on my Core i7 6500U based laptop. The kernel is 4.15 patched w/ GVT+dmabuf and QEMU 2.10 w/ GVT+dmabuf. All configurations are tested with the same Unigine benchmark settings: high quality textures and shaders, No AA, full-screen, and 1920x1080 resolution. Vsync is enabled in all benchmark tests to avoid frequent frame rendering pauses in vfio passthrough mode.

Host: Archlinux w/ Mesa 17.3.3 + Intel v1:2.99.917+811+g5c7e4e0e video driver
Guest: Windows 10 Pro 1709 (all updates installed) + Intel v15.60.2.4901 video driver

As we can see with this particular benchmark, GVT-g shared passthrough is offering better performance than the native Linux OpenGL version of the benchmark. Very nice!

Results:

Linux host + Windows 10 Guest w/ GVT-g passthrough + dmabuf
--------------------------------------------------------------------------------------
**[OpenGL]** Score: 456 | FPS: 18.1
**[Direct3D 11]** Score: 424 | FPS: 16.8
**[Direct3D 9]** Score: 413 | FPS: 16.4

Linux (Linux version)
----------------------------
**[OpenGL]** Score: 342 | FPS: 13.6

Linux + Wine 3.1 (Windows version)
------------------------------------------------
**[Direct3D 9]** Score: 245 | FPS 9.7
**[OpenGL]** Invalid results. Extensive rendering issues and missing textures
**[Direct3D 11]** Score: 307 | FPS: 12.2 (Likely invalid due to bad shader rendering)

<img src="https://steamuserimages-a.akamaihd.net/ugc/940560276597295020/A050D249E685275E751DE55A2688C29A62E5461D/" style="max-width:100%" alt="GVT-g">

**Comment by DocMAX** [comment]
How did you compile and install the linux kernel on arch?

**Comment by TerrenceXu** [comment]
Good news, glad to hear that!
