### ISSUE TITLE
Not Working on i5 6360U ? 

### ISSUE THREAD

**Issue by qy2009** [01org/gvt-linux#186]
it looks like not working on U series CPUs? I have an i5 6360U.
I got the error message when adding it into my VM :

VM creation error
XML error: 'model' attribute in <hostdev> is only supported when type='pci'" .  

please see the complete disussion here:
https://forums.unraid.net/topic/108650-plugin-intel-gvt-g/page/5/

thanks!

**Comment by tpressure** [comment]
This is a CPU with Intel Iris Graphics. which is not supported AFAIK.

**Comment by qy2009** [comment]
Intel GVT-g supports CPUs from Broadwell.  6360U is Skylake, two generations after Broadwell. so it should be supported, right?

**Comment by tpressure** [comment]
Correct, Skylake is supported, but only __without__ Iris Pro Graphics, e.g. i5-6300U will work since it has an Intel UHD 520 GPU.

I am not a dev so I can't tell you for certain, but I have a fair amount of experience with GVT-g and have not seen any supported system with Iris Pro in the field.

**Comment by qy2009** [comment]
Ic. I think that explains. I tried with my Unraid, and it failed quite a few times. I will give up... 
thanks so much for your info @tpressure  :)
