### ISSUE TITLE
Bad dual VM performance with GVT-g

### ISSUE THREAD

**Issue by tpressure** [01org/gvt-linux#187]
Hi,

I am doing some experiments around GVT-g performance and found the following issue:

When running a single VM with KVMGT, all is fine and the performance is really good. However, as soon as I start a second VM the performance degrades quite rapidly. For this issue to happen, it is not important for the second VM to run any workload. It appears as soon as the second guest has initialized the gpu, i.e. renders the framebuffer on the pci-vfio display.

Here are some numbers of Unigine Heaven running with 2 Fedora 33 guests (only 1 VM is executing the benchmark):

- 1 VM: 66.3fps average
- 2 VMs: 13.3fps average

As I said, in the 2 VM case the second VM is idle. No workload is running. When looking at the first VM during the boot of the second VM, one can see that the degradation happens as soon as the second VM initializes the screen.

Another observation is that the CPU load inside VM 1 drops by about 50% as soon as the second VM starts rendering.

This issue does not happen when booting the second VM without GVT-g.
It does not seem to be guest OS related as I can see the same issue with Windows VMs, too.

Is there any way to get a better 2 VM performance with GVT-g?

**Comment by xlkgh** [comment]
the same thing happened to me。
when I run emby transcoding alone, there is 60fps
but when VM win10 is running, the transcoding will fall to less than 20fps

**Comment by xlkgh** [comment]
I found something interesting
when i transcode alone, the power of GPU can reach 5W
![only](https://user-images.githubusercontent.com/14752195/144589917-87a48946-cb1b-456c-a559-4dc384c5c087.png)
When I turn on vm win10 at the same time, the power consumption is limited to 1W
![both](https://user-images.githubusercontent.com/14752195/144589925-397a0148-b67d-43d2-9520-a9559d2b1b97.png)

**Comment by f0re1gnKey** [comment]
I have this problem too, using Iris plus 655 ( intel i7 8559u )
Addition, heavy load in 1 VM and then start the second VM will cause random kernel panic, without any dmesg output

**Comment by recallmenot** [comment]
Can confirm power limit using intel_gpu_top on linux 6.4.14 + mesa 23.1.6-3 with HD5500:
GPU power stays ~< 1W while GVT-g VM is running (QEMU GTK display, gl=es).

**Comment by tpressure** [comment]
Closing this because GVT-g is dead technology and Intel will never update or fix a thing. What a sad story.

**Comment by zhenyw** [comment]
Sorry that we've put gvt-g as archived mode, as new xe driver would just move onto SRIOV HW based solution. GVT-g is only for legacy platform user with limited usage now.

**Comment by hertrste** [comment]
> Sorry that we've put gvt-g as archived mode, as new xe driver would just move onto SRIOV HW based solution. GVT-g is only for legacy platform user with limited usage now.

Unfortunately, SR-IOV is not as feature complete as GVT-g currently.

**Comment by tpressure** [comment]
@zhenyw unfortunately, GVT-g was never production ready and it is kinda sad that noone fixed the remaining issue to make it a great technology. See #153
