### ISSUE TITLE
1165g7 - kvmgt no such device.

### ISSUE THREAD

**Issue by Soldy** [01org/gvt-linux#195]
Do I have any chance to make it work with 1165g7 CPU ???

**Comment by rahulc07** [comment]
Nope no tiger lake support

**Comment by Soldy** [comment]
> Nope no tiger lake support

What is the problem with the tiger lake ?

**Comment by rahulc07** [comment]
Intel dropped support for gvt  for iris xe

**Comment by Soldy** [comment]
> Intel dropped support for gvt for iris xe

I find it :
https://dgpu-docs.intel.com/devices/iris-xe-max-graphics/index.html


Thank you for the info.
