### ISSUE TITLE
Does i7-11800h support gvt-g?

### ISSUE THREAD

**Issue by cathaysia** [01org/gvt-linux#201]
Hi, I am using i7-11800h, but it seems this cpu does not support gvt-g?

I just get 

> Unsupported device. GVT-g is disabled

and when I try `modpprobe kvmgt`, I get:

```
modprobe kvmgt 
modprobe: ERROR: could not insert 'kvmgt': No such device
```

But it support sriov:

```
# lspci -v | grep -A30 'VGA compatible controller'
00:02.0 VGA compatible controller: Intel Corporation TigerLake-H GT1 [UHD Graphics] (rev 01) (prog-if 00 [VGA controller])
	...
	Capabilities: [320] Single Root I/O Virtualization (SR-IOV)
	Kernel driver in use: i915
	Kernel modules: i915
```

However, while I follow https://liaoph.com/sr-iov/ to set SR-IOV, a error happend:

```
# LANG=C echo 4 > /sys/class/drm/card0/device/sriov_numvfs
echo: write error: no such file or directory
```

So, can anyone tell me what's the right way to virtual my graphics card?

**Comment by TerrenceXu** [comment]
i7-11800h is Tiger Lake, it not support GVT-g. You can use GVT-d in first.

**Comment by rahulc07** [comment]
Good Luck With GVT-d if you get it working please post and link back(if on a a different platform).  Many people have been trying to get it to work on Tiger Lake/Comet Lake

**Comment by cathaysia** [comment]
Sorry, I don't have any interest on gvt-d. gvt-d is not a good choice for me

**Comment by rayzorben** [comment]
> Sorry, I don't have any interest on gvt-d. gvt-d is not a good choice for me

I think I am going to encounter the same thing with Alder Lake, that GVT-g is not supported by the chip, and thus have to use GVT-d which I understand is full device passthrough which makes it unavailable to the host? Honestly, I am not sure how GVT-d is any different than doing full passthrough of the PCI-E device to the guest that has been around for years. Seems like GVT-g was a step forward.

**Comment by rayzorben** [comment]
> Sorry, I don't have any interest on gvt-d. gvt-d is not a good choice for me

After much research, it sounds like Intel has moved to SR-IOV which is supported on Intel Iris Xe : https://www.reddit.com/r/VFIO/comments/o7l2zr/sriov_on_intel_xe_graphics/

The problem is that I don't think there is much Linux support at the moment. This is really the answer for all virtualization - providing multiple virtual devices for each physical device that can be attached to any virtual machine. This includes graphics cards, network cards, and even SSDs!

**Comment by cathaysia** [comment]
yes, intel switch sriov for card virtuallization, but it's driver does not support at this time.
________________________________
