### ISSUE TITLE
No dma-buf output, Cursor plane not initialized by guest, ubuntu 16.04

### ISSUE THREAD

**Issue by newhacker1746** [01org/gvt-linux#22]
![screenshot from 2018-02-18 13-16-48](https://user-images.githubusercontent.com/19787725/36355205-003a8548-14ae-11e8-8df5-da87fb9bbf7a.png)
(1440x900 is the resolution of my macbookair7,2 with hd 6000) Ubuntu 16.04.3. stable-4.14 gvt-linux and igvtg-qemu 2.10.0 stable compiled and working. Using the command line options as stated in [the dma-buf user guide.](https://github.com/intel/gvt-linux/wiki/Dma_Buf_User_Guide#1-introduction.) Using gtk with gl=on. Booting with only the GVTg card available results in a black window with the message (#times) cursor plane not initialized by guest. No graphics output is available. This is under Ubuntu 16.04.3, and I am not sure how the folks running arch linux have it working perfectly, but not for ubuntu. This is with the pc-bios/bios.bin supplied with the qemu I compiled, and OVMF-code.fd from the debian apt repositories. This is also with both q35 and i440fx. No combination of machines and bios' made it work.

**Comment by newhacker1746** [comment]
Update: After a reboot, it appears like this may be the underlying issue:
`qemu-system-x86_64: -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/a297db4a-f4c2-11e6-90f6-d3b88d6c1337,x-display=on,x-igd-opregion=on: IGD device a297db4a-f4c2-11e6-90f6-d3b88d6c1337 cannot support legacy mode due to existing devices at address 1f.0`
I am booting with seabios, maybe this 'legacy' mode has something to do with it? After that message it goes back to the (#times) cursor plane not initialized by guest... Any ideas?

**Comment by elewarr** [comment]
I'm experiencing the same issue:
![screenshot from 2018-02-27 19-06-54](https://user-images.githubusercontent.com/3652890/36746182-f11cc710-1bf1-11e8-98a2-dfe976048b12.png)

UUID registered before:
![screenshot from 2018-02-27 18-50-37](https://user-images.githubusercontent.com/3652890/36746205-fcdbf56c-1bf1-11e8-8e6b-be8735993cc6.png)

And qemu launched:
```
#! /bin/bash -x
    /usr/bin/qemu-system-x86_64 \
    -m 2048 -smp 2 -M pc \
    -name local-display-vm \
    -hda ubuntu.img \
    -bios /usr/bin/bios.bin -enable-kvm \
    -vga none \
    -display gtk,gl=on \
    -k en-us \
    -machine kernel_irqchip=on \
    -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 \
    -cpu host -usb -usbdevice tablet \
    -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/a297db4a-f4c2-11e6-90f6-d3b88d6c9525,x-display=on,x-igd-opregion=on \
    -cdrom ubuntu-17.10.1-desktop-amd64.iso
```

Additional info:

1. lspci: `00:02.0 VGA compatible controller: Intel Corporation Sky Lake Integrated Graphics (rev 06)`
1. qemu configured with: `./configure --prefix=/usr  --enable-kvm --disable-xen  --enable-debug-info --enable-debug  --enable-sdl --enable-vhost-net --enable-spice --disable-debug-tcg  --enable-opengl --enable-gtk --enable-vgt --target-list=x86_64-softmmu`
1. grub: `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i915.enable_gvt=1 intel_iommu=on"`
1. /proc/cmdline: `BOOT_IMAGE=/vmlinuz-4.14.15-custom root=/dev/mapper/ubuntu--vg-root ro quiet splash i915.enable_gvt=1 intel_iommu=on vt.handoff=7`
1. uname: `Linux citan-pc 4.14.15-custom #1 SMP Tue Feb 27 01:16:28 CET 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by TerrenceXu** [comment]
Hello, from the logs you captured is no problem, it should be working.

Have you tried the “Spice”? with dma-buf?

Thanks
Terrence

**Comment by elewarr** [comment]
@TerrenceXu, with Spice I got white screen but it changed the size eventually, so I tried `-display gtk,gl=on` one more time and voila! It worked. I think I just wasn't patient enough. Slow HDD needed a lot of time to boot Ubuntu guest. And when it eventually started desktop environment then I got the screen.
Thank you for your help.

**Comment by rzk** [comment]
I have exactly the same problem as in the first post, waiting for DE start, unfortunately, does not help.

**Comment by elewarr** [comment]
@rzk, beside my problems with Spice client white screen and GTK window cursor plane initially, I also noticed a weird behaviour when I tried to prepare virtualization environment on a laptop (with Intel integrated and AMD dedicated GPU). Regardless of /sys/bus/pci/devices/0000:00:02.0/ mode selected the qemu windows had always full screen dimension and was black (and the cursor plane was not initialized).
I'm just guessing it may be related to the Intel/AMD mix. I didn't dig it yet, I'm not even sure which one was used by the X server.
In my previous comment, when it eventually worked for me, I used desktop PC and connected my display to HDMI port on motherboard, leaving dedicated GPUs unused (as display source).

Do you have only integrated GPU?

**Comment by rzk** [comment]
> qemu windows had always full screen dimension and was black (and the cursor plane was not initialized).

Thats exactly what I see. I have i5-7440HQ Kabylake laptop with NV 930MX, gvt-g test were done with 930MX disabled with bbswitch. I also tried intel_iommu=igfx_off.

**Comment by newhacker1746** [comment]
The issue is that there is no framebuffer output/svga basic driver support. dma-buf only works once a dma-buf aware driver is loaded, meaning that i915 in a VERY recent kernel must be loaded, or the cutting edge intel graphics windows drivers must be loaded. The windows installer will NOT work since it does not have those drivers. YOu need to install windows first. Ubuntu's latest LTS livecd also will not work. You need to install ubuntu, apt-get update, apt dist-upgrade, and make sure you have a self-compiled latest kernel (4.16 at least). Until OVMF gets patched for gvt-g framebuffer output, you will have to wait until the OS drivers initialize.

Also see XaeroVincent's comment (third comment) on this issue: 
[issue #21 ](https://github.com/intel/gvt-linux/issues/21)

**Comment by newhacker1746** [comment]
Please let me know if I can close this issue.

**Comment by elewarr** [comment]
Works for me.

**Comment by rzk** [comment]
>The windows installer will NOT work since it does not have those drivers. YOu need to install windows first. Ubuntu's latest LTS livecd also will not work. You need to install ubuntu, apt-get update, apt dist-upgrade, and make sure you have a self-compiled latest kernel (4.16 at least).

>Until OVMF gets patched for gvt-g framebuffer output, you will have to wait until the OS drivers initialize.

This has to be clearly stated in the wiki/README so others wont get confused seeing black screen instead of ouput.

Thanks for the help, I'll try again with Win10 and latest drivers preinstalled.
