### ISSUE TITLE
Gemini Lake support

### ISSUE THREAD

**Issue by akdevservices** [01org/gvt-linux#225]
Intel Celeron J4125, Gemini Lake, UHD 600.

```i915 0000:00:02.0: [drm] Unsupported device. GVT-g is disabled```

Does this CPU support GVT-g?

**Comment by rahulc07** [comment]
No, intel axed GVT-g recently, so the ONLY CPU's that support it are 14nm Core Series chips from Broadwell - Comet Lake.  (Intel Core i3/5/7 5xxx-10xxx).  And some xeons, specifically the ones in those generations ending with a 5 if they are an E3 sku
