### ISSUE TITLE
GVT-g, qemu: eglCreateImageKHR failed

### ISSUE THREAD

**Issue by redderraw12** [01org/gvt-linux#230]
Hi, I am getting the code `qemu: eglCreateImageKHR failed
` on qemu version 8.1.0-2 continuously when running through command line qemu. Here is the qemu command:
 ```
#!/bin/bash

#export MESA_LOADER_DRIVER_OVERRIDE=i965
export PIPEWIRE_RUNTIME_DIR=/run/user/1000
export PIPEWIRE_LATENCY=512/48000

qemu-system-x86_64 \
    -enable-kvm \
    -m 6G \
    -smp cores=4,threads=2,sockets=1,maxcpus=8 \
    -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
    -machine type=q35,accel=kvm,kernel_irqchip=on \
    -name windows-gvt-g-guest \
    -usb -device usb-tablet \
    -display gtk,gl=es \
    -vga none \
    -audiodev alsa,id=snd0 \
    -drive file=/home/stratz/VM/tiny11b1.iso,index=0,media=cdrom \
    -drive file=/home/stratz/VM/win10_disk,index=2,media=disk,if=virtio \
    -drive file=/home/stratz/VM/virtio-win-0.1.229.iso,index=3,media=cdrom \
    -device ich9-intel-hda \
    -device hda-output,audiodev=snd0 \
    -boot menu=on \
    -nic user,model=virtio-net-pci \
    -device ivshmem-plain,memdev=ivshmem,bus=pcie.0 \
    -object memory-backend-file,id=ivshmem,share=on,mem-path=/dev/shm/looking-glass,size=32M \
    -device vfio-pci,sysfsdev=/sys/bus/mdev/devices/af5972fb-5530-41a7-0000-fd836204445b,display=on,x-igd-opregion=on,ramfb=on,driver=vfio-pci-nohotplug \
 ```

The ramfb display comes online, and show the windows logo loading but shortly after it goes black and the errors start popping up. I am using the `i915-GVTg_V5_4` option to create the vgpu. This error did not come up 2 days ago, but downgrading the package `qemu-ui-gtk` didnt seem to resolve the issue. Running the same vm with a linux vm does not work either. However, the vgpu does provide output in virt-manager, however is laggy and no cursor shows up.

**Comment by recallmenot** [comment]
issue and temporary solution:
https://gitlab.com/qemu-project/qemu/-/issues/1891

**Comment by redderraw12** [comment]
Can confirm that using the solution in the bug tracker works. Thank you.
