### ISSUE TITLE
Something Wrong？ only 2 dir list in  /sys/class/mdev_bus/0000\:00\:02.0/mdev_supported_types/

### ISSUE THREAD

**Issue by syshack** [01org/gvt-linux#24]
Something Wrong？ only 2 dirs list in /sys/class/mdev_bus/0000\:00\:02.0/mdev_supported_types/

i915-GVTg_V5_4 and  i915-GVTg_V5_8

kernel: 4.16.0-rc5 
branch: qa/dma_buf 
Graphic: 00:02.0 VGA compatible controller: Intel Corporation Sky Lake Integrated Graphics (rev 06)

**Comment by TerrenceXu** [comment]
It is depends on your host aperture size


If your machine only with 256MB aperture size, you only can create one vgpu with vgpu type4.


You can check your machine totally aperture size by “lspci –vv –s 0:00:02”



For example, my machine aperture is configured to 1G.

   ...

   Region 0: Memory at c0000000 (64-bit, non-prefetchable) [size=16M]

   Region 2: Memory at 80000000 (64-bit, prefetchable) [size=1G]

   Region 4: I/O ports at 3000 [size=64]

**Comment by syshack** [comment]
@TerrenceXu Thanks，I'll try to change the  aperture size
