### ISSUE TITLE
[Question] Procedure of setting up an intel nuc (kaby lake) with xen-server

### ISSUE THREAD

**Issue by thommyho** [01org/gvt-linux#25]
Hello,
I just started using my nuc as low cost and efficient vm host and stumpled over the feature gvt-g. I read your wiki, but I couldn't wrap my head around, how to use it with xenserver.

So far I installed the free xen-server image, created some vms, etc ...

I followed the wiki and compiled xengt withing in a fresh ubuntu 16.04.4 or should I do this in the xenserver distro?

I am a little confused right now and it would be great if someone could resolve my issue 👍 
Thank you very much. 
BTW great work!!!

Greetings, Thomas

**Comment by TerrenceXu** [comment]
Close it and focus on the latest kernel.
