### ISSUE TITLE
Q35 Support?

### ISSUE THREAD

**Issue by jscinoz** [01org/gvt-linux#26]
Is GVT-g expected to work with the Q35 machine type? All current documentation refers only to the older i440fx machine type.

**Comment by jscinoz** [comment]
After some testing, GVT-g (including DMA-BUF) support does appear to work with Q35; but does not work with OVMF with either machine type at present. Closing this in favour of #23

**Comment by TerrenceXu** [comment]
We just tried OVMF again in Ubuntu 16.04 with the gvt-stable-4.14 code, it is working.
The referenced create VM command as below:

/usr/bin/qemu-system-x86_64 -m 2048  -hda /home/ubuntu-16.04-uefi.img -enable-kvm -bios /usr/share/ovmf/OVMF.fd -net nic,model=e1000,macaddr=00:53:8B:51:CC:08 -net tap,script=/etc/kvm/qemu-ifup -vga cirrus -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/b323e53e-782f-41bb-a7b8-3538d76fc73a -serial stdio

BTW, you must make sure your guest image was made by UEFI mode.
