### ISSUE TITLE
[Question] Does dma-buf work after live migrations? 

### ISSUE THREAD

**Issue by trevor403** [01org/gvt-linux#27]
I was wondering if dma-buf works on a target system after a live migration. Also as it is my understanding that a Guest Driver restart is not required unless you are migrating to a target with a different iGPU, is this correct?

I might setup a test jig to see if this works imperially but I wanted to see if anyone has the answer readily available before I go setup a system to build and test.

**Comment by TerrenceXu** [comment]
We didn’t validate this case, since dma-buf is still in experiment stage.

**Comment by TerrenceXu** [comment]
Close it and focus on the latest kernel.
