### ISSUE TITLE
System logs being flooded with GVT messages

### ISSUE THREAD

**Issue by chriscjs** [01org/gvt-linux#29]
I have GVT with dmabuf working but my system logs are being flooded by

kernel: gvt: vgpu 1: invalid range gmadr 0x0 size 0x0
kernel: gvt: vgpu 1: invalid gma address: 0

Is there any way to turn these messages off?  I am using qemu 2.12rc3 and kernel 4.16.2.

**Comment by TerrenceXu** [comment]
Close it and focus on the latest kernel and qemu.
