### ISSUE TITLE
Kernel

### ISSUE THREAD

**Issue by helladen** [01org/gvt-linux#3]
I modprobe the kernel and can't seem to get it to work.

Kernel is 4.1. Qemu is 2.9. Using Virt-Manager. Modules and initram all built and ran as instructed. I modprobe and get outputs for both VFIO and KVMGT. The virtual machine does not allow me to install Intel HD drivers.

I am using Arch Linux.

**Comment by zhenyw** [comment]
kernel 4.1 looks old for either host or guest. Pls check wiki page on setup guide.

**Comment by helladen** [comment]
I followed the guide completely, the Intel GPU wasn't being passthroughed into the VM.

**Comment by koleann** [comment]
I have the same problem, could you tell me how to solve

**Comment by face2nirvana** [comment]
I followed the guide completely, the Intel GPU wasn't being passthroughed into the VM. There is not the mdev_suppot_types in /sys/bus/pci/devices/0000:00:02.0/.   I need your help!
--

**Comment by TerrenceXu** [comment]
Hello, which platform you are using?

**Comment by face2nirvana** [comment]
CPU: Intel i7 7700
OS : ubuntu 17.04
kernel: I tried by  2 versions as follow : gvt-linux-gvt-stable-4.10 / gvt-linux-gvt-stable-4.11 
Qemu: Igvtg-qemu-stable-2.9.0
@TerrenceXu 
my email：haopeng@vanxum.com
Thanks!
Waiting Reply on line

**Comment by TerrenceXu** [comment]
Your machine is the Kabylake client platform.

Until now the gvt-stable-4.10 and gvt-stable-4.11 branch are only support Broadwell & Skylake platforms.
The gvt-staging branch now support the Broadwell & Skylake & Kabylake Server platforms, and will support Kabylake client platform soon.

But until now there is no branch support Kabylake client platform.

Thanks!

**Comment by face2nirvana** [comment]
ok！thank u！ I will try on another pc！ @TerrenceXu

**Comment by face2nirvana** [comment]
@TerrenceXu thanks very much！ i can  get the "mdev_support_types" on intel i5 6500. but there is another question: i want to create vgpu by the command as follow:
> "sudo echo "a297db4a-f4c2-11e6-90f6-d3b88d6c9525" > "/sys/bus/pci/devices/0000:00:02.0/ mdev_supported_types/i915-GVTg_V5_4/create" 
It can not work by the result:
> bash: /sys/bus/pci/devices/0000:00:02.0/ mdev_supported_types/i915-GVTg_V5_4/create: Permission denied
And , it doesnot work by using "hmod 644 create"
Thanks

**Comment by TerrenceXu** [comment]
You must use the root to create the vgpu. ☺

**Comment by face2nirvana** [comment]
yes. i use by  sudo! but  Permission  @TerrenceXu 
--

**Comment by face2nirvana** [comment]
yes! must be root! it is can not create vgpu by sudo !!!  Thanks @TerrenceXu

**Comment by face2nirvana** [comment]
@TerrenceXu Hi，I have another question：  Do you modify the i915 driver on guest vm for supporting the new “upstream” GVT-g ？？  Looking forward your reply! Thanks ！

**Comment by zhenyw** [comment]
We do have some modification for i915 in guest. So you need to use new enough kernel for guest e.g 4.8+, otherwise gvt-g host might fallback to failsafe if detect bad guest behavior.

**Comment by face2nirvana** [comment]
@zhenyw @TerrenceXu Thanks very much!
but there is a new question:
 I created 2 files in guest :  xorg.conf and lightdm_display.sh like the “GVTg_Setup_Guide” . 
then I reboot the qemu. I can not see anything, and can not connect to the guest by vnc. But i can connect the guest by ftp!  I need your help! 
By the way , i can connect the guest by vnc before creating the xorg.conf & lightdm_display.sh!
Looking forward your reply! Thanks 
--

**Comment by TerrenceXu** [comment]
Since if the Linux guest use the Intel GFX card well, you cannot see guest desktop in Qemu.
Suggest you follow “4.1.3” to start x11vnc service in guest. (make sure you have installed the “x11vnc” package in it, with make sure the “x11vnc” service running well by check the “ps”.

And then try to connect to guest by vnc.

**Comment by face2nirvana** [comment]
@TerrenceXu Hi，I succeeded in the GVT-g upstream with the ubuntu OS in guest！but there is another question： when the guest os is windows7，I can not log in the guest，and stop the boot screen after reboot the guest os with the intel graphic driver。 Looking forward your reply！ Thanks！

**Comment by face2nirvana** [comment]
@zhenyw @TerrenceXu there is a very important question：Do you modify the windows driver in guest for supporting the new upstream GVT-g? if yes， is the modify of win driver for new upstream GVT-g or someting else? In my opinoin, there is no modify in guest for A Full GPU Virtualization Solution!
再用中文表达一下：两位好！请问一下，你们在guest中是否修改了windows显卡驱动，这种修改是为了支持基于mdev的GPU虚拟化吗？我理解对于全虚拟化解决方案，是不应该修改guest中的驱动的，请两位帮忙解答一下，非常感谢！

**Comment by face2nirvana** [comment]
@TerrenceXu 

Do you modify the windows driver in guest for supporting the new upstream GVT-g? if yes? is the modify of win driver for new upstream GVT-g or someting else? In my opinoin, there is no modify in guest for A Full GPU Virtualization Solution!
Looking forward your reply！Thanks！
--

**Comment by TerrenceXu** [comment]
Hello,

Yes, we did some modification for Windows GFX driver, but it is not means it is not full GPU virtualization, since this change is included in the newest Windows GFX driver, not GVG-g need any extra modification manually.

Because for the Windows system in native and the Windows in GVT-G VM, we still install the same Windows GFX driver.

Thanks
Terrence

**Comment by face2nirvana** [comment]
@TerrenceXu you mean：the modification for windows driver in the newest version is in order to support GVT-g virtualization, is right? 

Looking forward your reply! Thanks!

**Comment by TerrenceXu** [comment]
Yes, you are right.

**Comment by face2nirvana** [comment]
@TerrenceXu Thanks! From the “A Full GPU Virtualization Solution with Mediated Pass-Through.pdf”，I think the modification in win driver in guest is mainly the address space balloon，is right?  and It is easy to accomplish address mapping from vm to host by using  the address space balloon .
Looking forward your reply! Thanks!

**Comment by face2nirvana** [comment]
@TerrenceXu I find a new branch that is the gvt-stable-4.12. Does the gvt-stable-4.12 support the Kabylake client platform?
Looking forward your reply! Thanks!

**Comment by TerrenceXu** [comment]
@face2nirvana , yes, it support Kabylake platform, but until now it is not very stable in Kabylake platform, we are working on enhance it.

**Comment by jo-erlend** [comment]
I try to create a device using the command:
# echo "83b8f4f2-509f-382f-3c1e-e6bfe0fa1001" > /sys/devices/pci0000\:00/0000\:00\:02.0/mdev_supported_types/i915-GVTg_V5_4/create

I get no error message, but I also don't get a device. 
# dmesg | grep -i gvt
[    2.678635] i915 0000:00:02.0: Direct firmware load for i915/gvt/vid_0x8086_did_0x5912_rid_0x04.golden_hw_state failed with error -2

Can someone explain what's happening? Google can't find a single reference to this at all. I'm entirely stuck.

**Comment by zhiwang1** [comment]
Can you upload the full dmesg? The error message you provided is not a critical error. Thanks so much for the feedback.

Thanks,
Zhi.
