### ISSUE TITLE
gvt can't work when multi gpu card inserted 

### ISSUE THREAD

**Issue by elkmil** [01org/gvt-linux#31]
gvt can't work when multi gpu card inserted.
[devs@localhost ]$ lspci 
00:00.0 Host bridge: Intel Corporation Intel Kaby Lake Host Bridge (rev 05)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (rev 05)
00:02.0 Display controller: Intel Corporation HD Graphics 630 (rev 04)
00:14.0 USB controller: Intel Corporation 200 Series PCH USB 3.0 xHCI Controller
00:14.2 Signal processing controller: Intel Corporation 200 Series PCH Thermal Subsystem
00:16.0 Communication controller: Intel Corporation 200 Series PCH CSME HECI #1
00:17.0 SATA controller: Intel Corporation 200 Series PCH SATA controller [AHCI mode]
00:1c.0 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #5 (rev f0)
00:1f.0 ISA bridge: Intel Corporation 200 Series PCH LPC Controller (B250)
00:1f.2 Memory controller: Intel Corporation 200 Series PCH PMC
00:1f.3 Audio device: Intel Corporation 200 Series PCH HD Audio
00:1f.4 SMBus: Intel Corporation 200 Series PCH SMBus Controller
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Turks PRO [Radeon HD 7570]

[devs@localhost ]$ uname -a
Linux localhost.localdomain 4.16.1 #4 SMP Sun Apr 15 18:20:14 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
==========
vfio_display_get_dmabuf: new dmabuf: id 1, res 1920x1200, format XR24, plane primary, fd 11, hot +0+20480

only one new dmabuf printed

**Comment by memegauste** [comment]
Seems I have similar issue but not sure about the same error :)

**Comment by TerrenceXu** [comment]
I've checked the latest 5.9.0 code with 3 gpu card existed at the same time, kvmgt is works well. So you can check the latest code for a try. :)
root@gvt-cfl:~# lspci|grep VGA
00:02.0 VGA compatible controller: Intel Corporation HD Graphics P630 (rev 04)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV710 [Radeon HD 4350/4550]
03:00.0 VGA compatible controller: Matrox Electronics Systems Ltd. MGA G200e [Pilot] ServerEngines (SEP1) (rev 05)
