### ISSUE TITLE
Mdev_supported_types does not exist  ，why?

### ISSUE THREAD

**Issue by yahuishi** [01org/gvt-linux#32]
ll /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/
ls: cannot access /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/: No such file or directory

**Comment by melyux** [comment]
How did you solve this? I have the same issue.

**Comment by TerrenceXu** [comment]
Make sure "i915.enable_gvt=1" existed in your grub.

**Comment by melyux** [comment]
Haha just solved it! Had re-compiled the kernel, but forgot to switch to it, so I was still using the old kernel without mdev support. Now running into a new problem... “opengl not available” when you try to start the VM. This road has many roadblocks.

**Comment by TerrenceXu** [comment]
please follow https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide#561-create-kvmgt-vm, make sure "display=off" existed if you not use dma-buf.

**Comment by melyux** [comment]
Ah, that fixed it! Gave me a bunch of BSODs right after booting, but reinstalling Windows 10 fixed that. Whew. Everything works. Took a while but got there.

**Comment by iamSlightlyWind** [comment]
> Haha just solved it! Had re-compiled the kernel, but forgot to switch to it, so I was still using the old kernel without mdev support. Now running into a new problem... “opengl not available” when you try to start the VM. This road has many roadblocks.

@TerrenceXu 
If you don't mind, could you tell me how to add mdev support to the kernel source code and recompile it? I've yet to find a single bit of info anywhere else. I don't have the `Mdev_supported_types` file nor could I enable the kernel module `kvmgt` which is not present, maybe they have something to do together
