### ISSUE TITLE
-bash: /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/: No file or directory

### ISSUE THREAD

**Issue by yahuishi** [01org/gvt-linux#33]
root@KL30:/sys/bus/pci/devices/0000:00:02.0# echo "a297db4a-f4c2-11e6-90f6-d3b88d6c9525" > "/sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create"
-bash: /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create: No file or directory
root@KL30:cd  /sys/bus/pci/devices/0000:00:02.0mdev_supported_types
-bash: /sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/: No file or directory
root@KL30:/sys/bus/pci/devices/0000:00:02.0# uname -r
4.14.15+
root@KL30:/sys/bus/pci/devices/0000:00:02.0# ls
backlight             consistent_dma_mask_bits  dma_mask_bits    firmware_node  index          max_link_speed  numa_node  resource      revision          uevent
boot_vga              current_link_speed        driver           graphics       irq            max_link_width  power      resource0     rom               vendor
broken_parity_status  current_link_width        driver_override  i2c-0          label          modalias        remove     resource2     subsystem
class                 d3cold_allowed            drm              i2c-1          local_cpulist  msi_bus         rescan     resource2_wc  subsystem_device
config                device                    enable           i2c-2          local_cpus     msi_irqs        reset      resource4     subsystem_vendor
root@KL30:/sys/bus/pci/devices/0000:00:02.0#

**Comment by TerrenceXu** [comment]
You should make sure whether the i915.enable_gvt=1 is existed in your host grub and whether the kvmgt related modules are existed. ☺

**Comment by yahuishi** [comment]
thanks，
