### ISSUE TITLE
xengt module cannot be added

### ISSUE THREAD

**Issue by The-Wind** [01org/gvt-linux#34]
Running `sudo modprobe xengt` gives me this: `modprobe: ERROR: could not insert 'xengt': Invalid argument`.

Tried on Linux Mint 18.3 on gvt-stable-4.14 branch

**Comment by TerrenceXu** [comment]
Hi, you want to run XenGT or KVMGT?

Can you provide your /boot/config-4.14.15+?

Make sure XenGT or KVMGT related modules are existed.

**Comment by The-Wind** [comment]
[Here you go](https://github.com/intel/gvt-linux/files/1945621/config-4.14.15.txt)

I merely just followed the guide as I don't have an in-depth Linux knowledge. I want to run XenGT as I have a 4th gen (Haswell) CPU.

I did do something wrong though; I was not booting Xen in EFI properly. I used `multiboot` `linux` `initrd` instead of `multiboot` `module` `module` because I think that doesn't work in EFI.

I'm apparently supposed to use `multiboot2` `module2` `module2` but that still didn't work. Someone claimed the fix is to upgrade the grub bootloader at least 2.02 beta 3 (I have beta 2). So I will try that. 

Anyways, could not booting Xen properly be the issue for why the XenGT module doesn't load?

**Comment by TerrenceXu** [comment]
GVT-g only support 5, 6, 7th gen, not support Haswell. ☺

**Comment by The-Wind** [comment]
I was under the impression that 4th gen was supported in XenGT according to [this](https://01.org/igvt-g/blogs/wangbo85/2017/intel-gvt-g-xengt-public-release-q32017):

> Intel GVT-g is a full GPU virtualization solution with mediated pass-through, starting from 4th generation Intel Core(TM) processors with Intel processor graphics. A virtual GPU instance is maintained for each VM, with part of performance critical resources directly assigned. The capability of running native graphics driver inside a VM, without hypervisor intervention in performance critical paths, achieves a good balance among performance, feature, and sharing capability. GVT-g for Xen hypervisor is XenGT.

I suppose the GVT-g Setup Guide says otherwise but I figured I take a shot at it.

**Comment by The-Wind** [comment]
The module now loads. I confirm that I needed to boot Xen gz properly with `multiboot2` `module2` `module2` in the grub menuentry. I had to build grub from source because the one in Mint's repo is outdated.

**Comment by TerrenceXu** [comment]
Hello, only our old 4.3 kernel XenGT branch support 4th gen, which without upstream. The upstream  code start from 5th gen. ☺
