### ISSUE TITLE
vga std and gvt error

### ISSUE THREAD

**Issue by elkmil** [01org/gvt-linux#37]
===================== gust dmesg===============================
[    6.152430] [drm] Virtual GPU for Intel GVT-g detected.
[    6.152913] [drm] Replacing VGA console driver
[    6.162349] Console: switching to colour dummy device 80x25
[    6.162408] [drm] iGVT-g active, disabling use of stolen memory
[    6.166568] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    6.166569] [drm] Driver supports precise vblank timestamp query.
[    6.166576] i915 0000:00:04.0: BAR 6: can't assign [??? 0x00000000 flags 0x20000000] (bogus alignment)
[    6.166577] [drm] Failed to find VBIOS tables (VBT)
[    6.166821] i915 0000:00:04.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=io+mem
[    6.169103] [drm:drm_calc_timestamping_constants [drm]] *ERROR* crtc 37: Can't calculate constants, dotclock = 0!
[    6.169189] WARNING: CPU: 0 PID: 337 at drivers/gpu/drm/drm_vblank.c:612 drm_calc_vbltimestamp_from_scanoutpos+0x2cb/0x320 [drm]
[    6.169189] Modules linked in: bochs_drm(+) ttm i915(+) video i2c_algo_bit drm_kms_helper crc32c_intel serio_raw drm e1000 ata_generic pata_acpi qemu_fw_cfg
[    6.169196] CPU: 0 PID: 337 Comm: systemd-udevd Not tainted 4.16.3-200.fc27.x86_64 #1
[    6.169197] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.11.1-0-g0551a4be2c-prebuilt.qemu-project.org 04/01/2014
[    6.169203] RIP: 0010:drm_calc_vbltimestamp_from_scanoutpos+0x2cb/0x320 [drm]
[    6.169203] RSP: 0018:ffffbe16408cf8c0 EFLAGS: 00010082
[    6.169204] RAX: ffffffffc06547c0 RBX: ffff9d8273840000 RCX: 0000000000000000
[    6.169205] RDX: ffffffffc0466ce8 RSI: 0000000000000001 RDI: ffffffffc0464cf4
[    6.169205] RBP: ffffbe16408cf928 R08: 0000000000000000 R09: ffffffffc0447ea0
[    6.169206] R10: ffff9d827a50a878 R11: ffffffffc05519b0 R12: 0000000000000000
[    6.169206] R13: ffff9d827a50a800 R14: ffffbe16408cf93c R15: ffffbe16408cf960
[    6.169208] FS:  00007f80a4f571c0(0000) GS:ffff9d827fc00000(0000) knlGS:0000000000000000
[    6.169208] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    6.169209] CR2: 00007f5849c03218 CR3: 0000000136292001 CR4: 0000000000360ef0
[    6.169211] Call Trace:
[    6.169219]  ? drm_calc_timestamping_constants+0x15a/0x170 [drm]
[    6.169224]  drm_get_last_vbltimestamp+0x54/0x90 [drm]
[    6.169229]  drm_reset_vblank_timestamp+0x54/0xc0 [drm]
[    6.169234]  drm_crtc_vblank_on+0x83/0xe0 [drm]
[    6.169266]  intel_modeset_setup_hw_state+0xb8f/0x1000 [i915]
[    6.169289]  ? gen2_write16+0x110/0x110 [i915]
[    6.169311]  intel_modeset_init+0x7eb/0x1970 [i915]
[    6.169334]  ? intel_setup_gmbus+0x2a5/0x2b0 [i915]
[    6.169352]  i915_driver_load+0xb5d/0x17c0 [i915]
[    6.169378]  ? acpi_dev_found+0x5f/0x70
[    6.169380]  local_pci_probe+0x42/0xa0
[    6.169388]  ? pci_assign_irq+0x27/0x130
[    6.169389]  pci_device_probe+0x141/0x1b0
[    6.169397]  driver_probe_device+0x30b/0x480
[    6.169402]  __driver_attach+0xb8/0xe0
[    6.169404]  ? driver_probe_device+0x480/0x480
[    6.169405]  bus_for_each_dev+0x76/0xc0
[    6.169408]  ? klist_add_tail+0x3b/0x60
[    6.169410]  bus_add_driver+0x161/0x260
[    6.169411]  ? 0xffffffffc0733000
[    6.169412]  driver_register+0x57/0xc0
[    6.169414]  ? 0xffffffffc0733000
[    6.169416]  do_one_initcall+0x4e/0x18d
[    6.169423]  ? _cond_resched+0x15/0x40
[    6.169428]  ? kmem_cache_alloc_trace+0xa8/0x1c0
[    6.169431]  ? do_init_module+0x22/0x201
[    6.169432]  do_init_module+0x5b/0x201
[    6.169439]  load_module+0x259b/0x2c40
[    6.169441]  ? SYSC_init_module+0x162/0x190
[    6.169442]  ? _cond_resched+0x15/0x40
[    6.169443]  SYSC_init_module+0x162/0x190
[    6.169444]  do_syscall_64+0x74/0x180
[    6.169448]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[    6.169455] RIP: 0033:0x7f80a48639ba
[    6.169455] RSP: 002b:00007ffc0b098b48 EFLAGS: 00000246 ORIG_RAX: 00000000000000af
[    6.169456] RAX: ffffffffffffffda RBX: 000055e92f812d20 RCX: 00007f80a48639ba
[    6.169457] RDX: 00007f80a41251ad RSI: 00000000003c206b RDI: 000055e9300973d0
[    6.169458] RBP: 00007f80a41251ad R08: 0000000000000005 R09: 00007ffc0b096a4b
[    6.169458] R10: 0000000000000005 R11: 0000000000000246 R12: 000055e9300973d0
[    6.169459] R13: 000055e92f810c70 R14: 0000000000020000 R15: 000055e92e10c7fc
[    6.169459] Code: e1 48 c7 c2 e8 6c 46 c0 be 01 00 00 00 48 c7 c7 f4 4c 46 c0 e8 b7 eb ff ff 48 8b 83 98 03 00 00 48 83 78 20 00 0f 84 69 fd ff ff <0f> 0b 45 31 ed e9 62 fd ff ff 48 c7 c2 b0 6c 46 c0 31 f6 48 c7 
[    6.169481] ---[ end trace 50c05b3bbf99f65a ]---

===================== gust uname -a ===================
Linux localhost.localdomain 4.16.3-200.fc27.x86_64 #1 SMP Thu Apr 19 19:33:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

===================host =======================
linux-4.17.0-rc2  gvt-staging branch 
qemu command line 
-vga std and kvm gvt

**Comment by TerrenceXu** [comment]
Close it and focus on the latest kernel and qemu.
