### ISSUE TITLE
Dosn't work on rhel 7.5 with kernel 4.17.0-rc1 

### ISSUE THREAD

**Issue by syshack** [01org/gvt-linux#39]
![image](https://user-images.githubusercontent.com/376407/39680822-94e47864-51d7-11e8-918f-003c97214fde.png)

![image](https://user-images.githubusercontent.com/376407/39680859-f2e867e0-51d7-11e8-8b38-0033e9488e95.png)

Nothing  found in /sys/bus/mdev/devices/ ，something wrong?

**Comment by TerrenceXu** [comment]
Hi, RHEL7.5 is also supported for GVT-g.
You can add (add_drivers+="kvmgt vfio-iommu-type1 vfio-mdev") into /etc/dracut.conf, and regenerate initrd, and try again. :)

**Comment by alanxie1129** [comment]
@TerrenceXu 
Did you mean rhel does not need to install a new kernel? Just add add_drivers+="kvmgt vfio-iommu-type1 vfio-mdev" in /etc/dracut.conf? Can you tell us the detailed steps?

**Comment by alanxie1129** [comment]
edit /etc/dracut.conf
add_drivers+="kvmgt vfio-iommu-type1 vfio-mdev"

dracut -f /boot/initramfs-3.10.0-862.el7.x86_64.img
or
dracut -f /boot/initramfs-4.17.0-1.el7.elrepo.x86_64.img

Kernel startup failed

**Comment by alanxie1129** [comment]
@syshack how to enable gvt-g forom rhel 7.5 Can you tell us the detailed steps?
