### ISSUE TITLE
The Centos7.5 can not support

### ISSUE THREAD

**Issue by alanxie1129** [01org/gvt-linux#42]
git clone https://github.com/intel/gvt-linux.git

cd gvt-linux

git checkout gvt-stable-4.14

echo ""|make oldconfig

vi .config 

change y for CONFIG_DRM_I915_GVT, CONFIG_DRM_I915_GVT_KVMGT and CONFIG_DRM_I915_GVT_XENGT CONFIG_VFIO_MDEV and CONFIG_VFIO_MDEV_DEVICE.

make -j8 && make modules_install && make install

vi /boot/grub2/grub.cfg

menuentry 'CentOS Linux (4.14.15+) 7 (Core)' --class centos --class gnu-linux --class gnu --class os --unrestricted $menuentry_id_option 'gnulinux-3.10.0-862.el7.x86_64-advanced-dacc0767-4de5-45f5-a580-3d7cfa65073d' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_msdos
        insmod xfs
        set root='hd0,msdos1'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 --hint='hd0,msdos1'  0216cf0f-102e-41e8-b562-ce6d35d06fc1
        else
          search --no-floppy --fs-uuid --set=root 0216cf0f-102e-41e8-b562-ce6d35d06fc1
        fi
        linux16 /vmlinuz-4.14.15+ root=/dev/mapper/centos-root ro crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet LANG=en_US.UTF-8 i915.enable_gvt=1 kvm.ignore_msrs=1 
        initrd16 /initramfs-4.14.15+.img
}

done 

reboot os from new kernel boot

no this /sys/class/mdev_bus

but same practice for ubuntu 18.04 is good ,Centos7.5 is not support

**Comment by TerrenceXu** [comment]
Hi, Centos7.5 is also supported for GVT-g.
You can add (add_drivers+="kvmgt vfio-iommu-type1 vfio-mdev") into /etc/dracut.conf, and regenerate initrd, and try again. :)

**Comment by alanxie1129** [comment]
@TerrenceXu 
Did you mean rhel does not need to install a new kernel? Just add add_drivers+="kvmgt vfio-iommu-type1 vfio-mdev" in /etc/dracut.conf? Can you tell us the detailed steps?

**Comment by alanxie1129** [comment]
edit /etc/dracut.conf
add_drivers+="kvmgt vfio-iommu-type1 vfio-mdev"

dracut -f /boot/initramfs-3.10.0-862.el7.x86_64.img
or
dracut -f /boot/initramfs-4.17.0-1.el7.elrepo.x86_64.img

Kernel startup failed

**Comment by TerrenceXu** [comment]
Close it and focus on the latest centos.
