### ISSUE TITLE
vGPU resolution

### ISSUE THREAD

**Issue by bilBob430** [01org/gvt-linux#44]
Hi,
I'm currently using intel GVT with a Windows guest and displaying it with gtk.

When looking at the resolutions (i915-GVTg_V5_4 and i915-GVTg_V5_8 in the mdev_supported_types folder) of the virtual GPU, I can only choose between 1024x768 and 1920x1200.

When setting my output on the correct mode for the lower resolution, I have no issues.

On the other hand, the higher resolution (1920x1200) is above the current mode I'm using, therefore the VM goes off screen. Setting the QEMU windows as fullscreen gives me unexpected behavior (guest randomly going off screen and the mouse cursor is off from its real position).

Is there a way to get a vGPU with a resolution of 1920x1080? I tried adding a new mode with xrandr (for a resolution of 1920x1200) to no CPU is i7-7700K (8th generation)

**Comment by bilBob430** [comment]
Hi,
I fixed the mouse offset and resolution problem by adding the EDID of my specific display in the driver source.
I'm still having the graphic glitches though,
it happens when Windows first boots and whenever my cursor moves a windows by selecting it

**Comment by Confucij** [comment]
@bilBob430 I think I have the exact the same issue on my laptop. Can you please point the place in the code where you've changed EDID?

**Comment by Confucij** [comment]
@bilBob430  Just to answer to myself - I've fixed my problem via this utility: https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU
I found it via this thread: https://github.com/intel/gvt-linux/issues/21

**Comment by ghost** [comment]
Just some extra, can use the Intel Graphics Control Panel as well.
Go into Display and set it to 1920x1080, then at the botton select "Maintain Display Scaling"

**Comment by zhangchn** [comment]
@RtzLi which version of Intel driver was installed?

**Comment by zhangchn** [comment]
Hi, I have tested Ubuntu 18.04 desktop as guest. It seems that the guest i915 does support a scaled resolution other than 1920x1080 and the host dmabuf scales great. Perhaps the cause of issue is in the Windows guest driver.

**Comment by gnattu** [comment]
Just add to this. When using egl-headless with VNC/SPICE, the resolution of the remote session never changes with the guest resolution change, it stays at 1920x1200, which is causing problems.
