### ISSUE TITLE
Can't boot successfully after installing the Intel Graphics Driver 15.45.23.4860

### ISSUE THREAD

**Issue by alandingbc** [01org/gvt-linux#46]
cpu：I5 6500
Host OS: Ubuntu 16.04 server
Qemu: 2.12 
kernel: 4.14
The Qemu and the Kernel are build following the https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide.

After creating the virtual card by mdev, I create and run a new vm by QEMU with a script.
I can see the two GFX cards "qxl" and "vga"(not the full name). After installing the latest Intel Graphics Driver 15.45.23.4860(64 bit), the device manager shows "Intel HD Graphics 530" which was shown as "vga" and another one is also the "qxl". Everything is ok until now, however, it always keep at the "start Windows" when I reboot the vm to make it effective.
I try to comment the vfio device in the script, it could start okay with it, but false again when I un-comment it.
I don't know what's wrong with it?

Append:
I use spice for the remote client.

Here is kernel log:

[  390.511764] Graphics resource is not enough for the guest
[  390.514952] Now vgpu 1 will enter failsafe mode.
[  698.070855] gvt: vgpu 1: untracked MMIO 00000000 len 1

**Comment by alandingbc** [comment]
I try to install a Win10 vm and install the driver 'win64_15.60.2.4901'.
Does that mean there is the problem with the driver '15.45.23.4860' on Win7?

**Comment by TerrenceXu** [comment]
> I try to install a Win10 vm and install the driver 'win64_15.60.2.4901'.
> Does that mean there is the problem with the driver '15.45.23.4860' on Win7?

You can check our release note in mail thread, Win7 only support GPU type1,2,4 but not support type8, due to it needs more GPU resource.

**Comment by alandingbc** [comment]
Thanks for your answer. I will do check it after now.
