### ISSUE TITLE
qemu process defunct immediately after starting VM

### ISSUE THREAD

**Issue by alex3kov** [01org/gvt-linux#47]
I'm on Arch, libvirt 4.6.0, QEMU 2.12.1, Linux 4.17.18, CPU i5-5300U, `kvmgt` module is loaded and `i915` module is loaded with `enable_gvt=1` option. Guest is Windows 7, using q35 and OVMF.  
Creating mdev device seems to be working fine:
```sh
$ ls -l /sys/class/mdev_bus/0000\:00\:02.0/741be43f-601a-456e-94ef-9547e713f3e2/
total 0
lrwxrwxrwx 1 root root    0 Aug 22 11:01 driver -> ../../../../bus/mdev/drivers/vfio_mdev
drwxr-xr-x 2 root root    0 Aug 22 14:53 intel_vgpu
lrwxrwxrwx 1 root root    0 Aug 22 12:10 iommu_group -> ../../../../kernel/iommu_groups/0
lrwxrwxrwx 1 root root    0 Aug 22 12:10 mdev_type -> ../mdev_supported_types/i915-GVTg_V4_4
drwxr-xr-x 2 root root    0 Aug 22 14:53 power
--w------- 1 root root 4096 Aug 22 14:53 remove
lrwxrwxrwx 1 root root    0 Aug 22 11:01 subsystem -> ../../../../bus/mdev
-rw-r--r-- 1 root root 4096 Aug 22 11:01 uevent
```
Relevant bits from VM .xml definition:
```xml
    <graphics type='spice'>
      <listen type='none'/>
      <clipboard copypaste='yes'/>
      <filetransfer enable='yes'/>
      <gl enable='yes'/>
    </graphics>
    <video>
      <model type='none'/>
    </video>
    <hostdev mode='subsystem' type='mdev' managed='no' model='vfio-pci' display='on'>
      <source>
        <address uuid='741be43f-601a-456e-94ef-9547e713f3e2'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x09' slot='0x00' function='0x0'/>
    </hostdev>
```
Immediately after issuing `virsh start vm` qemu process goes defunct:
```sh
$ ps -efc |grep qemu
username  3439     1 TS   19 14:47 ?        00:00:00 [qemu-system-x86] <defunct>
```
And it hangs indefinitely (well, I tried like 15 minutes). The only way to kill it is to issue `virsh destroy vm`, I tried adding `<graphics type='egl-headless'/>` element - doesn't help.  
Please point out if my configuration is wrong or how should I research this further.

**Comment by coxuintel** [comment]
Did you update the kernel and QEMU on host according to?
https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide

It's suggested to fetch and compile both host kernel and QEMU repo as suggested, instead of use the generic version.

**Comment by alex3kov** [comment]
> Did you update the kernel and QEMU on host according to?
> https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide
> It's suggested to fetch and compile both host kernel and QEMU repo as suggested, instead of use the generic version.

According to https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide, this is not necessary:
> NOTICE: For KVMGT, you also can use the current upstream Linux kernel and QEMU directly since all the enabling patches have been upstreamed.  

I added kernel version (4.17.18) to top post. Will try it on 4.18 as well soon.

**Comment by ghost** [comment]
1. Ovmf is not supported, use bios
2. Update qemu to 3.0.0, 2.12.1 hangs with libvirt for igvt-g
3. You need to pass additional arguments to qemu https://nixos.wiki/wiki/IGVT-g#Configure_KVM
4. You'll need to connect via `virt-viewer --attach` to see igvt-g display

**Comment by alex3kov** [comment]
@gnidorah 
> Ovmf is not supported, use bios  

Source? Is this stated explicitly anywhere?

**Comment by ghost** [comment]
> Source? Is this stated explicitly anywhere?

Only in mail list
1. Detected by users https://lists.01.org/pipermail/igvt-g/2018-April/001403.html
2. Confirmed by Intel https://lists.01.org/pipermail/igvt-g/2018-July/001431.html

**Comment by alex3kov** [comment]
Thanks. I can't use BIOS in my VM, so it's goodbye GVT for me :) (until OVMF is implemented, if ever).

**Comment by chriscjs** [comment]
Same thing happened to me.  The fix was to disable qemu sandboxing which is enabled by default by libvirt.  Edit /etc/libvirt/qemu.conf and make sure the following line reads
seccomp_sandbox = 0
Uncomment the line if its commented.  After the change restart libvirtd.

Edit:
I am using BIOS and not OVMF so your VM may still not boot.

**Comment by gnidorah** [comment]
@alex3kov However, you could boot EFI/GPT windows disk on BIOS VM, that worked for me with gvt-g. Here's the guide: https://gist.github.com/gnidorah/2951b1f8bebeac899623fd67694ed47b
