### ISSUE TITLE
Is newest linux and qemu supported out of box - I use Arch?

### ISSUE THREAD

**Issue by memegauste** [01org/gvt-linux#48]
I ask because I get this error using qemu vfio-pci view:
![obraz](https://user-images.githubusercontent.com/21007545/44947634-1fbd2780-ae10-11e8-8c55-a4d119b9eb39.png)
I don't compiled anything and used packages from repo, also tutorial from here:
https://www.reddit.com/r/VFIO/comments/8h352p/guide_running_windows_via_qemukvm_and_intel_gvtg/
I use i5-6600 and rx480 on host, I want to pass an HD530 iGPU.
Thanks.

**Comment by oscarbg** [comment]
I also have same error..
what kernel/qemu version do you use..

**Comment by memegauste** [comment]
![obraz](https://user-images.githubusercontent.com/21007545/44948418-4fbef780-ae1d-11e8-8866-cc25a7a8f879.png)

**Comment by oscarbg** [comment]
same as me..
might be worth giving a try with Qemu 2.12 and/or kernel 4.17 to at least know which of the two is guilty..

**Comment by memegauste** [comment]
I switched from OVMF to Seabios (default QEMU bios) and I get freeze when I install drivers of skylake iGPU:
![obraz](https://user-images.githubusercontent.com/21007545/44950181-b9e99380-ae41-11e8-8904-f7c98b9173c3.png)
Just joking, I will go sleep and check if something changed, because why not. Good night.

**Comment by memegauste** [comment]
Ok, I was running qemu with root rights. Now I tried to run without root, but QEMU window does not appear. Also changed OVMF to SeaBios.
My /etc/udev/rules.d/10-qemu.rules
```SUBSYSTEM=="vfio", OWNER="root", GROUP="kvm"```
My daemon:
```
[Unit]
Description=Create Intel GVT-g vGPU

[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo '68fe893a-6ae6-4e8f-b0f6-376e1b0ffec6' > /sys/devices/pci0000:00/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create"
ExecStop=/bin/sh -c "echo '1' > /sys/devices/pci0000:00/0000:00:02.0/68fe893a-6ae6-4e8f-b0f6-376e1b0ffec6/remove"
RemainAfterExit=yes

[Install]
WantedBy=graphical.target
```

My QEMU run.sh file:
```
#!/bin/sh

# QEMU
qemu-system-x86_64 \
        -enable-kvm \
        -m 4G \
        -smp cores=2,threads=2,sockets=1,maxcpus=4 \
        -machine type=pc,accel=kvm,kernel_irqchip=on \
        -global PIIX4_PM.disable_s3=1 \
        -global PIIX4_PM.disable_s4=1 \
        -name windows10-gvt-g \
        -soundhw ac97 \
        -usb \
        -device usb-tablet \
        -display gtk,gl=on \
        -device vfio-pci,sysfsdev=/sys/devices/pci0000:00/0000:00:02.0/68fe893a-6ae6-4e8f-b0f6-376e1b0ffec6,x-igd-opregion=on,display=on \
        -drive file=/home/hoshi/windows10/win10.qcow2,format=qcow2,l2-cache-size=8M \
        -cdrom /home/hoshi/windows10/win_install.iso \
        -vga qxl \
```

**Comment by HoshiYamazaki** [comment]
Ok, I was running qemu with root rights. Now I tried to run without root, but QEMU window does not appear. Also changed OVMF to SeaBios.
My /etc/udev/rules.d/10-qemu.rules
```SUBSYSTEM=="vfio", OWNER="root", GROUP="kvm"```
My daemon:
```
[Unit]
Description=Create Intel GVT-g vGPU

[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo '68fe893a-6ae6-4e8f-b0f6-376e1b0ffec6' > /sys/devices/pci0000:00/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create"
ExecStop=/bin/sh -c "echo '1' > /sys/devices/pci0000:00/0000:00:02.0/68fe893a-6ae6-4e8f-b0f6-376e1b0ffec6/remove"
RemainAfterExit=yes

[Install]
WantedBy=graphical.target
```

My QEMU run.sh file:
```
#!/bin/sh

# QEMU
qemu-system-x86_64 \
        -enable-kvm \
        -m 4G \
        -smp cores=2,threads=2,sockets=1,maxcpus=4 \
        -machine type=pc,accel=kvm,kernel_irqchip=on \
        -global PIIX4_PM.disable_s3=1 \
        -global PIIX4_PM.disable_s4=1 \
        -name windows10-gvt-g \
        -soundhw ac97 \
        -usb \
        -device usb-tablet \
        -display gtk,gl=on \
        -device vfio-pci,sysfsdev=/sys/devices/pci0000:00/0000:00:02.0/68fe893a-6ae6-4e8f-b0f6-376e1b0ffec6,x-igd-opregion=on,display=on \
        -drive file=/home/hoshi/windows10/win10.qcow2,format=qcow2,l2-cache-size=8M \
        -cdrom /home/hoshi/windows10/win_install.iso \
        -vga qxl \
```

**Comment by memegauste** [comment]
Wait. This \ at QEMU endline was unnecessary. I was doing it at 2 AM. Sorry lol.

**Comment by oscarbg** [comment]
Have you solved it?

**Comment by memegauste** [comment]
As I said - Arch packages are supporting it probably, but gvt-g is buggy for me and causes that:
https://github.com/intel/gvt-linux/issues/49
Freeze on driver install.
