### ISSUE TITLE
Sound problem in windows VM

### ISSUE THREAD

**Issue by franklee1973** [01org/gvt-linux#50]
I use GVT on a 7th i3 7100u system. The host OS is CENTOS 7.5, and I install a windows 7 as a KVM virtual machine on CENTOS, with intel GVT technology, the win7 VM can share GPU with host CENTOS.
Everything is okay, but the sound from windows is bad, I hear something like crackles in sound.

Windows 7 VM use AC97 virtual sound adapter, qemu-kvm uses pulse audio as its sound infrastructure. 
I use Igvtg-qemu stable 2.10.0 and GVT-linux kernel 4.14.

The same configuration works at spice mode, the sound are prefect. 

Any one can response me are appreciate.

**Comment by TerrenceXu** [comment]
> I use GVT on a 7th i3 7100u system. The host OS is CENTOS 7.5, and I install a windows 7 as a KVM virtual machine on CENTOS, with intel GVT technology, the win7 VM can share GPU with host CENTOS.
> Everything is okay, but the sound from windows is bad, I hear something like crackles in sound.
> 
> Windows 7 VM use AC97 virtual sound adapter, qemu-kvm uses pulse audio as its sound infrastructure.
> I use Igvtg-qemu stable 2.10.0 and GVT-linux kernel 4.14.
> 
> The same configuration works at spice mode, the sound are prefect.
> 
> Any one can response me are appreciate.

You can consider pass-through host audio device to you Windows 7 VM.

**Comment by franklee1973** [comment]
After passing-through host audio device to Windows 7 VM, sound quality can is even worse.
It seems CPU in win7 VM can not decode sound data in time in GVT mode.

**Comment by ghost** [comment]
I have good sound quality using the following:

    QEMU environment:
    export QEMU_AUDIO_DRV=pa (may need to compile QEMU with pulseaudio)
    export QEMU_PA_SERVER=/run/user/1000/pulse/native
    QEMU command line:
    -soundhw hda
    /etc/pulse/daemon.conf:
    default-sample-rate = 44100
    alternate-sample-rate = 48000

If QEMU is unable to connect to pulse then you will need to copy

    /home/user/.config/pulse/cookie -> /root/.config/pulse

Then in Windows guest set sample rate to "16 bit, 44100 Hz (CD Quality)"
![image](https://user-images.githubusercontent.com/30946735/47985204-06489c80-e12d-11e8-998b-b2bc41d6b4b4.png)

**Comment by franklee1973** [comment]
Hi RtzLi, 
   What Kernel version and Qemu version did you use?
