### ISSUE TITLE
Pentium support

### ISSUE THREAD

**Issue by gvtgwanderer** [01org/gvt-linux#51]
The Pentium G4600/G4620 have HD 630 as integrated GPU and it is also featured in Kaby Lake Core series. Does this mean that GVT-g can be used on G4600/G4620?

**Comment by TerrenceXu** [comment]
> The Pentium G4600/G4620 have HD 630 as integrated GPU and it is also featured in Kaby Lake Core series. Does this mean that GVT-g can be used on G4600/G4620?

It should be yes since GVT always detect the GPU version.
