### ISSUE TITLE
i3-8100 CPU support

### ISSUE THREAD

**Issue by zlxing** [01org/gvt-linux#53]
Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz support or not?

**Comment by hyuan3** [comment]
Can you copy the result of 'lspci -nn' here? Need to check gpu's pid.

**Comment by zlxing** [comment]
![Uploading image.png…]()

**Comment by zlxing** [comment]
00:00.0 Host bridge [0600]: Intel Corporation Device [8086:3e1f] (rev 08)
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:3e91]
00:12.0 Signal processing controller [1180]: Intel Corporation Device [8086:a379] (rev 10)
00:14.0 USB controller [0c03]: Intel Corporation Device [8086:a36d] (rev 10)
00:14.2 RAM memory [0500]: Intel Corporation Device [8086:a36f] (rev 10)
00:16.0 Communication controller [0780]: Intel Corporation Device [8086:a360] (rev 10)
00:17.0 SATA controller [0106]: Intel Corporation Device [8086:a352] (rev 10)
00:1b.0 PCI bridge [0604]: Intel Corporation Device [8086:a32c] (rev f0)
00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:a33c] (rev f0)
00:1c.5 PCI bridge [0604]: Intel Corporation Device [8086:a33d] (rev f0)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:a308] (rev 10)
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:a348] (rev 10)
00:1f.4 SMBus [0c05]: Intel Corporation Device [8086:a323] (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Device [8086:a324] (rev 10)
01:00.0 Non-Volatile memory controller [0108]: Device [1c5c:1327]
02:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 15)
03:00.0 Parallel controller [0701]: SUNIX Co., Ltd. Multiport serial controller [1fd4:1999]

**Comment by hyuan3** [comment]
It's CFL platform. Not supported yet.

**Comment by zlxing** [comment]
when this cpu can be supported? Thanks.

**Comment by hyuan3** [comment]
No plan right now.

**Comment by zlxing** [comment]
OK,Thanks!

**Comment by flopon** [comment]
> It's CFL platform. Not supported yet.
> No plan right now.

OK, hope it will be planned soon, I just canceled an order for a new NUC to upgrade my homelab after viewing that !

**Comment by hyuan3** [comment]
Here is the latest update on CFL support. We have the patch under testing. Will submit it to upstream soon.

**Comment by slis** [comment]
@hyuan3 Thank you for your support! Great news!

**Comment by klausenbusk** [comment]
> Here is the latest update on CFL support. We have the patch under testing. Will submit it to upstream soon.

Is it a host or guest change? I have a i7-8550U and and right now I just get a black screen when running Win10 in a VM (egl-headless, mdev, spice).

**Comment by hyuan3** [comment]
It will have some changes on host.

**Comment by zlxing** [comment]
@hyuan3 When we can get the test version? thanks!

**Comment by hyuan3** [comment]
It still has some issues with dmabuf based display. Hope we can submit the first version this month.

**Comment by zlxing** [comment]
@hyuan3 Thanks very much! Great news!

**Comment by TerrenceXu** [comment]
@zlxing , tell you a good news, the first Coffee Lake test version is ready, the tag is: gvt-staging-2019y-01m-10d-11h-40m-01s, you can check out to the latest gvt-staging branch code for a try.

**Comment by zlxing** [comment]
@TerrenceXu Thanks, i will try it soon.

**Comment by jamescassell** [comment]
Is there an updated tag or branch that has this support?  (the one referenced above seems to be gone)

**Comment by TerrenceXu** [comment]
@jamescassell, you can use the latest gvt-staging-xxx tag.

**Comment by uKev** [comment]
Looks like Coffee Lake Support (CFL) will be in Linux 5.1 (expected in May 2019).

**Comment by TerrenceXu** [comment]
@uKev , yes, suppose it will be. :)

**Comment by rombert** [comment]
Is this ticket also tracking other 8th gen CPUs? I have the same "unsupported device" message on Kernel 5.0.3 with

```
00:00.0 Host bridge [0600]: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers [8086:3ec4] (rev 07)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 07)
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 630 (Mobile) [8086:3e9b]
00:04.0 Signal processing controller [1180]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem [8086:1903] (rev 07)
00:08.0 System peripheral [0880]: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model [8086:1911]
00:12.0 Signal processing controller [1180]: Intel Corporation Cannon Lake PCH Thermal Controller [8086:a379] (rev 10)
00:14.0 USB controller [0c03]: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller [8086:a36d] (rev 10)
00:14.2 RAM memory [0500]: Intel Corporation Cannon Lake PCH Shared SRAM [8086:a36f] (rev 10)
00:14.3 Network controller [0280]: Intel Corporation Wireless-AC 9560 [Jefferson Peak] [8086:a370] (rev 10)
00:15.0 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH Serial IO I2C Controller #0 [8086:a368] (rev 10)
00:16.0 Communication controller [0780]: Intel Corporation Cannon Lake PCH HECI Controller [8086:a360] (rev 10)
00:16.3 Serial controller [0700]: Intel Corporation Cannon Lake PCH Active Management Technology - SOL [8086:a363] (rev 10)
00:1b.0 PCI bridge [0604]: Intel Corporation Cannon Lake PCH PCI Express Root Port #17 [8086:a340] (rev f0)
00:1b.4 PCI bridge [0604]: Intel Corporation Cannon Lake PCH PCI Express Root Port #21 [8086:a32c] (rev f0)
00:1c.0 PCI bridge [0604]: Intel Corporation Cannon Lake PCH PCI Express Root Port #1 [8086:a338] (rev f0)
00:1c.7 PCI bridge [0604]: Intel Corporation Cannon Lake PCH PCI Express Root Port #8 [8086:a33f] (rev f0)
00:1d.0 PCI bridge [0604]: Intel Corporation Cannon Lake PCH PCI Express Root Port #9 [8086:a330] (rev f0)
00:1e.0 Communication controller [0780]: Intel Corporation Device [8086:a328] (rev 10)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:a30e] (rev 10)
00:1f.3 Audio device [0403]: Intel Corporation Cannon Lake PCH cAVS [8086:a348] (rev 10)
00:1f.4 SMBus [0c05]: Intel Corporation Cannon Lake PCH SMBus Controller [8086:a323] (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH SPI Controller [8086:a324] (rev 10)
00:1f.6 Ethernet controller [0200]: Intel Corporation Ethernet Connection (7) I219-LM [8086:15bb] (rev 10)
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP107GLM [Quadro P2000 Mobile] [10de:1cba] (rev a1)
01:00.1 Audio device [0403]: NVIDIA Corporation GP107GL High Definition Audio Controller [10de:0fb9] (rev a1)
03:00.0 Wireless controller [0d40]: Intel Corporation Device [8086:7360] (rev 01)
70:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS525A PCI Express Card Reader [10ec:525a] (rev 01)
71:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981 [144d:a808]
```

**Comment by Ashark** [comment]
Seems working now in Arch with my i7-8700.

**Comment by dynek** [comment]
Do we now have a 5.x kernel supporting Coffee Lake?
Still have to a dependency on Proxmox though to update the kernel.

**Comment by TerrenceXu** [comment]
Use latest kernel from 5.2 all support Coffeelake.
