### ISSUE TITLE
Fails with CONFIG_TRIM_UNUSED_KSYMS

### ISSUE THREAD

**Issue by bepvte** [01org/gvt-linux#57]
When  CONFIG_TRIM_UNUSED_KSYMS is enabled, the KVMGT "MPT module" is not detected. This is not visible in the documentation and was hard to diagnose.

**Comment by TerrenceXu** [comment]
Good finding! Thank you for your notification, we also can reproduce it when enable CONFIG_TRIM_UNUSED_KSYMS enabled though we never enable it previously.
