### ISSUE TITLE
sdl display output not working

### ISSUE THREAD

**Issue by warsier** [01org/gvt-linux#58]
I firstly followed the wiki tutorial to install gvt-g. Although I figured out that the virtual machines can correctly identify the virtual graphic card (tested with OpenCL), the GUI of Ubuntu 16.03 did not show correctly. I feel like there is some problem with the sdl display mode of QEMU, even connecting with a remote X11 display as suggested in wiki did not solve the problem.
However, after I tried to display directly with gtk, it actually works. I feel like it may be better to just recommend users to try gtk first, which is also much easier to install.

**Comment by TerrenceXu** [comment]
Do you means show VM directly in gtk, it needs dma-buf feature.
https://github.com/intel/gvt-linux/wiki/Dma_Buf_User_Guide

**Comment by warsier** [comment]
Hi, thank you for the reply.

I have enabled dma_buf and can show VM directly in gtk without any issue.

What I am having problem with is the suggested sdl display mode (remote access with X11VNC). After setting intel graphic card as the display card, the GUI (tty-7) did not show correctly. Because I can normally login through tty-1, I suspect that there may be some conflict between QEMU sdl display mode and the intel graphic card so that it does not render the GUI correctly.

Also, I feel using sdl and remote protocol is less intuitive than directly using gtk, so I think it may be better to recommend trying gtk first in your tutorial.

**Comment by TerrenceXu** [comment]
@warsier ,did you still have any problem about gtk?

**Comment by cxdong** [comment]
@warsier, did still have any issue? I am going to close this issue,  as long time no update. Please feel free to re-open or create new one. Thanks!
