### ISSUE TITLE
Intel 7th Generation Core

### ISSUE THREAD

**Issue by maqiangddb** [01org/gvt-linux#6]
Hi:
   If Intel 7th Generation Core will support this feature?

**Comment by jiaochuandong** [comment]
I have an error in Intel 7th Generation Core(i5 7500) 

#echo "78a289f9-6004-4de3-9fdc-37f3e2ba69b6" > "/sys/bus/pci/devices/0000:00:02.0/
mdev_supported_types/i915-GVTg_V5_4/create"
bash: echo: write error: Invalid argument


detail: 
ubuntu 16.04.3
uname -r 
4.12.0+
lsmod | grep kvm
kvm_intel             200704  0
kvmgt                  24576  1
mdev                   20480  2 kvmgt,vfio_mdev
vfio                   28672  3 vfio_iommu_type1,kvmgt,vfio_mdev
kvm                   585728  2 kvm_intel,kvmgt
irqbypass              16384  1 kvm
drm                   344064  6 kvmgt,i915,drm_kms_helper
cat /boot/grub/grub.cfg
...
linux   /boot/vmlinuz-4.12.0+ root=UUID=33b0a2ea-7ee0-45c7-bb60-96192194838e ro  quiet splash $vt_handoff i915.enable_gvt=1 kvm.ignore_msrs=1 intel_iommu=on
....

can you gave me some advices?

**Comment by TerrenceXu** [comment]
Hello

Is is the opergion virtualization issue with special platform. You can use the gvt-staging code for instead now, it is working.

Thanks
Terrence

**Comment by jiaochuandong** [comment]
Thanks for your help 
now i can create vgpu in my device(i5 7500). kernel is 4.15.0-rc4+.
But I don't found skl_dmc_ver1_27.bin and  kbl_dmc_ver1_04.bin on https://01.org/linuxgraphics/downloads/firmware

- sudo dpkg -i linux-image-4.15.0-rc4+_4.15.0-rc4+-7_amd64.deb 
...
W: Possible missing firmware /lib/firmware/i915/skl_dmc_ver1_27.bin for module i915
W: Possible missing firmware /lib/firmware/i915/kbl_dmc_ver1_04.bin for module i915
I am not sure if this warns influence the final result?

-  i  had  created  vgpu and new.img before  I used comment line:
sudo qemu-system-x86_64 -m 2048 -smp 2 -M pc -name gvt-g-guest -hda new.img -bios /usr/bin/bios.bin -enable-kvm -k en-us -serial stdio -vnc :1 -machine kernel_irqchip=on -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -cpu host -usb -usbdevice tablet -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/56f07026-e611-11e7-81b4-f36d1cecf706,rombar=0
select_vgahw vga is std
set vendor id(8086) for devfn(0)
set vendor id(8086) for devfn(8)
set vendor id(1234) for devfn(10)
set vendor id(8086) for devfn(18)
set vendor id(8086) for devfn(9)
set vendor id(8086) for devfn(a)
set vendor id(8086) for devfn(b)
set vendor id(0) for devfn(20)
qemu-system-x86_64: vfio: Failed to start device
I don't know how to solve this error.

After that 
vncviewer :1
I use lspci on guest's terminal, I can see my VGA:
00:02:0 VGA ....
00:04:0 VGA compatible controller: Intel Corporation Device 5912 
I changed xrog.conf
cat /etc/X11/xorg.conf 
Section "Device" 
Identifier "intel" 
Driver "intel" 
BusID "PCI:0:4:0" # Sample: "PCI:0:2:0" 
EndSection

Section "Screen" 
Identifier "intel" 
Device "intel" 
EndSection
then I reboot ,I can't enter the graphic
![screenshot from 2017-12-21 16-58-58](https://user-images.githubusercontent.com/12129969/34252955-944a04c2-e680-11e7-9744-a08e4e95e5ae.png)
![screenshot from 2017-12-21 17-03-03](https://user-images.githubusercontent.com/12129969/34252969-a1899116-e680-11e7-955c-cd2bde744b22.png)
![screenshot from 2017-12-21 18-57-18](https://user-images.githubusercontent.com/12129969/34253010-cb69f2a0-e680-11e7-8ea9-cd06015c88f5.png)

**Comment by TerrenceXu** [comment]
Miss the related dmc bin file is make sense, not a problem.

Can you add “-vga qxl” into Qemu boot up VM command and try again?

Thanks
Terrence

**Comment by jiaochuandong** [comment]
I have added "-vga qxl"
sudo qemu-system-x86_64 -m 2048 -smp 2 -M pc -name gvt-g-guest -hda new.img -bios /usr/bin/bios.bin -enable-kvm -vga qxl -k en-us -serial stdio -vnc :1 -machine kernel_irqchip=on -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -cpu host -usb -usbdevice tablet -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/56f07026-e611-11e7-81b4-f36d1cecf706,rombar=0
![screenshot from 2017-12-21 21-18-57](https://user-images.githubusercontent.com/12129969/34257367-93dc6c78-e694-11e7-9dc3-a971c6ef8552.png)

But I just want to use intel's video card rather than virtual video card to play 3D video game or deep learning. I have to modify /etc/X11/xorg.conf
Section "Device"
Identifier "intel"
Driver "intel"
BusID "PCI:0:4:0" # Sample: "PCI:0:2:0"
EndSection

Section "Screen"
Identifier "intel"
Device "intel"
EndSection

use the same command line 
unfortunately, I can't see my Desktop.
![screenshot from 2017-12-21 21-44-05](https://user-images.githubusercontent.com/12129969/34258252-1964bb5e-e698-11e7-9707-0c458ca9049b.png)

Thanks
Chuandong

**Comment by TerrenceXu** [comment]
After you enable the Intel Graphics driver in Linux VM

You should connect VM by X11vnc, follow the guide as below:

https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide#413-linux-remote-protocol-support


You must connect vm by vm IP address, it will show the desktop.

**Comment by jiaochuandong** [comment]
when I reboot my host I found I could not find vgpu's uuid in that path(/sys/bus/pci/devices/0000:00:02.0/)   
How could I save vgpu device after I create them? 

when I  create them again I discover an error
echo "4b22bf63-cd51-4b91-9573-b95812783b54" > "/sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create"
bash: echo: write error: No space left on device

Thanks 
Chuandong

**Comment by TerrenceXu** [comment]
Yes the vgpu uuid path will not be saved after reboot machine.

Looks due to your host desktop occupied too much aperture size resource, you can try to restart the lightdm and try to create the vgpu again.

Thanks
Terrence

**Comment by jiaochuandong** [comment]
Hello TerrenceXu
Thanks for your help. I think I can connect to guest by vncviewer 192.168.31.5(vm's ip)
I can not use vncviewer :1 to connect the guest. is it true?

But I have two question 

1.   when i enter the guest I found two VGA card (02.00 and 04.00). can you give me command  which one is working in my guest? I just use glxgears to show value.
![screenshot from 2017-12-23 15-10-59](https://user-images.githubusercontent.com/12129969/34317866-868a27b2-e7f3-11e7-9af1-9a2a9ce14777.png)

2.  In my host. I create two or more vgpu. I want to know if I can set dynamic gpu memory?if ture How to set ?

Thanks
Chuandong

**Comment by jiaochuandong** [comment]
I restarted  the pc  before I create three uuid 
#uuid -n 3 
I want to create 3 vgpu ,but only one can be created
# echo "a23c05e4-e90f-11e7-92a8-4fde5fa8e7b7" > "/sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create"
# echo "a23c0666-e90f-11e7-92a9-4be30e41841e" > "/sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create"
bash: echo: write error: No space left on device
#  echo "a23c0684-e90f-11e7-92aa-d7f4ad5f3750" > "/sys/bus/pci/devices/0000:00:02.0/mdev_supported_types/i915-GVTg_V5_4/create"
bash: echo: write error: No space left on device

pc's memory: 16G
I want to know Why I can not create 3 vcpus?

**Comment by TerrenceXu** [comment]
My reply inline.:)

**Comment by TerrenceXu** [comment]
Maybe the aperture size (low gm size) is not enough for you.

Host always occupy 128MB aperture size. And each vgpu with vgpu type4 will occupy 128MB aperture size (you can reference to chapter 5.1)

If your machine only with 256MB aperture size, you only can create one vgpu with vgpu type4.


You can check your machine totally aperture size by “lspci –vv –s 0:00:02”



For example, my machine aperture is configured to 1G.

   ...

   Region 0: Memory at c0000000 (64-bit, non-prefetchable) [size=16M]

   Region 2: Memory at 80000000 (64-bit, prefetchable) [size=1G]

   Region 4: I/O ports at 3000 [size=64]


Thanks
Terrence
