### ISSUE TITLE
linux 4.19 regression: graphic artifacts, invalid tiling mode

### ISSUE THREAD

**Issue by tinywrkb** [01org/gvt-linux#61]
I noticed this with linux 4.19.4, downgraded to linux 4.18.7 to confirm that this is a kernel regression.  
Attached video demonstrates the graphical artifacts: [gvt_regression.tar.gz](https://github.com/intel/gvt-linux/files/2616719/gvt_regression.tar.gz)

Error message in kernel:

    gvt: vgpu 1: invalid tiling mode: 1

Tested with qemu 3.0.0, mesa 18.2.5.  
CPU: E3-1265L v4

**Comment by TerrenceXu** [comment]
Thank you for your good finding, we will fix it ASAP.

**Comment by TerrenceXu** [comment]
@tinywrkbee , can you try the Commit b244ffa for a try? Thanks!

**Comment by tinywrkb** [comment]
Seems to be resolved. Tested with a build of gvt-staging-2018y-12m-03d-17h-06m-10s tag (4.20rc4), didn't try to patch a stable 4.19 release.

Guests tested: Windows 10 RS5 and Linux 4.19 based desktop.  

Thanks @TerrenceXu

**Comment by tinywrkb** [comment]
I had some time to test the official 4.19.4 release with patch applied on top and it looks fine.

**Comment by TerrenceXu** [comment]
OK, thank you for your testing @tinywrkbee !
