### ISSUE TITLE
Any plan to support Gemini Lake / Pentium Silver like J5005/N5000 with UHD 605 ?

### ISSUE THREAD

**Issue by BankaiNoJutsu** [01org/gvt-linux#64]
Any plan to support Gemini Lake / Pentium Silver like J5005/N5000 with UHD 605 ?

Is the GPU arch difference of UHD 620/630 that much different from smaller like 605?

Just wondering, if any plans are there, and if the maintain of such would not be too time intensive.

At the moment simply get:
`root@proxmox5:~# dmesg | grep -i gvt
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.15.18-9-pve root=UUID=683c774e-05ea-486a-bd4b-4ca8ad85f97e ro quiet intel_iommu=on i915.enable_gvt=1
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.15.18-9-pve root=UUID=683c774e-05ea-486a-bd4b-4ca8ad85f97e ro quiet intel_iommu=on i915.enable_gvt=1
[    4.855045] [drm] Unsupported device. GVT-g is disabled`

I found the project [https://github.com/projectacrn/acrn-kernel](https://github.com/projectacrn/acrn-kernel) which seems to implement some kind of support of gvt for apollo lake [https://projectacrn.github.io/latest/hardware.html#intel-apollo-lake-nuc](https://projectacrn.github.io/latest/hardware.html#intel-apollo-lake-nuc) Promising?

**Comment by hyuan3** [comment]
We have no plan to add Gemini Lake support right now. The code change might be small. But some efforts are needed to make it pass all graphics test and work stable.

**Comment by BankaiNoJutsu** [comment]
Okay, thank you for the reply.

**Comment by blablatros** [comment]
Any update on this? Thanks

**Comment by coxuintel** [comment]
No plan yet. You may have a quick try to modify intel_gvt.c() to add the support, also need do similar change all around gvt codes to add the support. However it's not guaranteed to work. As @hyuan3 mentioned, more work is required to make GPU work stable.

**Comment by tristan-k** [comment]
Did someone modify `intel_gvt.c()` as suggested and achieved this?

**Comment by gavgav11** [comment]
> Did someone modify `intel_gvt.c()` as suggested and achieved this?

I tried but got error when modprobing kvmgt (#191)

**Comment by clippsly** [comment]
any updates?

**Comment by theexx** [comment]
i would like to installios on a gemni lake n5000 pentiumbased notebook

any suggestion ?

thanks guys
