### ISSUE TITLE
Support for Dynamic Resolutions?

### ISSUE THREAD

**Issue by CuriousTommy** [01org/gvt-linux#65]
With most virtual machines, there is a feature that [automatically changes the resolution based on the size of the VM window](https://youtu.be/ekV-Ebl0U54?t=220). I was wondering if there are plans to add support for this feature on the windows guest driver.

**Comment by hyuan3** [comment]
Thanks for your comment. We will take a look.

**Comment by zhangchn** [comment]
With the latest QEMU patches (EDID for VFIO vgpu), it could be confirmed that Windows 10 guest can now dynamically adapt to virtual GTK screen resolution changes.

**Comment by CuriousTommy** [comment]
Besides adding the patches to QEMU, what are the argument needed to enable the dynamic resolution?

Also do you have a link to the EDID for VFIO patches, or are those patches already upstreamed to qemu-git?

Edit: Oh, I misread your statement. You are saying that someone could implement support.

**Comment by zhangchn** [comment]
@CuriousTommy As I tested today, the guest configuration used to show up only at highest resolution could work dynamically, i.e. the guest updated its resolution automatically after host window size changes.

Kernel built from a late February 2019 staging tag was used. The qemu from the latest origin/master was used.

**Comment by CuriousTommy** [comment]
@zhangchn Would you be able to post the QEMU commands (or the .xml libvirt file) you used to enable dynamic resolution scaling?

**Comment by zhangchn** [comment]
The command parameter was like:
    -machine pc,accel=kvm -vga none -display gtk,gl=on -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/{UUID},x-igd-opregion=on,display=on -cpu host

For the guest, graphics driver version was 25.20.100.6519.
Host kernel was staging-2019y-03m-25d-11h-02m-53s.

**Comment by TinaZhangZW** [comment]
As this feature is supported by qemu upstream, I'm going to close the issue.

**Comment by nikp123** [comment]
What iGPU driver do I need, as dynamic resizing doesnt work for me (partially).

I've checked that the EDID of the guest gets updated, but the iGPU driver only recognizes changes from the initial startup (bootup). Even Ctrl+Shift+Win+B does not update the recommended resolution.

So I guess this is more of a issue with the Intel driver in the guest than the kernel driver or qemu. Guest operating system is Windows 10 1809.
