### ISSUE TITLE
[SOLVED] VGPU hangs with kernel 5.0-rc2 (staging branch)

### ISSUE THREAD

**Issue by nick1132** [01org/gvt-linux#67]
Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
It is called Whiskey Lake i think, I am not sure if it is included along with other 8th gen intel processors you recently gave support to.  

I only after 30 to 60 seconds of booting windows 10 guest (not running any other programs), the host freezes and here is the log related to crash.
Host ram:32GB 
Guest ram :16GB
vm seems ok if I don't enable vgpu device
Am I missing anything?

```
Jan 21 03:59:05 userpc kernel: [  226.612494] vfio_pin_page_external: Task qemu-system-x86 (3086) RLIMIT_MEMLOCK (16777216) exceeded
Jan 21 03:59:05 userpc kernel: [  226.612495] gvt: vgpu 1: vfio_pin_pages failed for gfn 0x11489b, ret -12
Jan 21 03:59:05 userpc kernel: [  226.612496] gvt: vgpu 1: fail: spt 0000000002e0dacf guest entry 0x11489b007 type 1
Jan 21 03:59:05 userpc kernel: [  226.612497] gvt: vgpu 1: fail: shadow page 0000000002e0dacf guest entry 0x11489b007 type 1.
Jan 21 03:59:05 userpc kernel: [  226.612498] gvt: guest page write error, gpa 10ef3a778
Jan 21 03:59:12 userpc kernel: [  234.063237] [drm] GPU HANG: ecode 9:0:0x85dffffb, reason: hang on rcs0, action: reset
Jan 21 03:59:12 userpc kernel: [  234.063238] [drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
Jan 21 03:59:12 userpc kernel: [  234.063238] [drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
Jan 21 03:59:12 userpc kernel: [  234.063238] [drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
Jan 21 03:59:12 userpc kernel: [  234.063256] [drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
Jan 21 03:59:12 userpc kernel: [  234.063257] [drm] GPU crash dump saved to /sys/class/drm/card0/error
Jan 21 03:59:12 userpc kernel: [  234.064267] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
```

GPU crash dump at /sys/class/drm/card0/error  has one line content "No error state collected".

**Comment by hyuan3** [comment]
What's the Intel graphics driver version in your Win 10 guest?

**Comment by nick1132** [comment]
It freezes before I can manually download the drivers from intel site.

Device manager shows two Display adapters 
I think intel one has the default microsoft driver software installed.

I also have QXL configured on vm and installed spice qxl drivers.

**Comment by zhangchn** [comment]
Also on 5.0-rc2.
First the Windows 10 guest froze, and then the host got frozen, too.
Managed to get some log from system journal.
[error1.txt](https://github.com/intel/gvt-linux/files/2781173/error1.txt)

**Comment by nick1132** [comment]
000

**Comment by TerrenceXu** [comment]
@nick1132  @zhangchn , what the commit you are using, gvt-staging-2019y-01m-15d-19h-05m-28s?

**Comment by nick1132** [comment]
@terrencexu Yes gvt-staging: 2019y-01m-15d-19h-05m-28s

**Comment by zhangchn** [comment]
cod/tip/drm-tip/2019-01-17 (145226f65c3959d9809210935ea437d6cd164c05) from https://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/2019-01-17/

**Comment by TerrenceXu** [comment]
The coffee lake enabling patch hasn't been checked to drm-intel branch, but it existed in 2019y-01m-15d-19h-05m-28s.
Until now we haven't Whiskey Lake platform, our validated coffee lake platform CPU is 
"cpu：Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz", it passed 2019y-01m-15d-19h-05m-28s nightly testing.
@nick1132, what win10 windows gfx driver version you used?

**Comment by nick1132** [comment]
@TerrenceXu The crash happens before I could install the driver version dch_win64_25.20.100.6519 while I was still on default microsoft display driver.  The processor's integrated gpu is UHD 620

i created a new win 10 guest - this time I got blue screen crash with message:   "SYSTEM THREAD EXCEPTION NOT HANDLED"   - host did not freeze, i guess blue screen prevents it.

This is how  I  invoke the vgpu device
  <qemu:commandline>
    <qemu:arg value='-device'/>
    <qemu:arg value='vfio-pci,sysfsdev=/sys/devices/pci0000:00/0000:00:02.0/c6cc6c40-1d44-11e9-bb9a-8fde851f9ab0,rombar=0,display=off,x-igd-opregion=on'/>
  </qemu:commandline>



Here are some logs from the host:
```
Jan 22 03:48:37 userpc kernel: [  112.902263] vfio_pin_page_external: Task qemu-system-x86 (2849) RLIMIT_MEMLOCK (16777216) exceeded
Jan 22 03:48:37 userpc kernel: [  112.902263] gvt: vgpu 1: vfio_pin_pages failed for gfn 0x16d9c1, ret -12
Jan 22 03:48:37 userpc kernel: [  112.902264] gvt: vgpu 1: fail to populate guest ggtt entry
Jan 22 03:48:37 userpc /usr/lib/gdm3/gdm-x-session[1323]: (II) modeset(0): EDID vendor "AUO", prod id 9197
Jan 22 03:48:37 userpc /usr/lib/gdm3/gdm-x-session[1323]: (II) modeset(0): Printing DDC gathered Modelines:
Jan 22 03:48:37 userpc /usr/lib/gdm3/gdm-x-session[1323]: (II) modeset(0): Modeline "1920x1080"x0.0  142.00  1920 2028 2076 2100  1080 1090 1100 1126 +hsync -vsync (67.6 kHz eP)
Jan 22 03:48:37 userpc /usr/lib/gdm3/gdm-x-session[1323]: (II) modeset(0): Modeline "1920x1080"x0.0  113.60  1920 2028 2076 2100  1080 1090 1100 1126 +hsync -vsync (54.1 kHz e)
Jan 22 03:48:37 userpc /usr/lib/gdm3/gdm-x-session[1323]: (II) config/udev: removing GPU device /sys/devices/pci0000:00/0000:00:02.0/drm/card0 /dev/dri/card0
Jan 22 03:48:37 userpc /usr/lib/gdm3/gdm-x-session[1323]: xf86: remove device 0 /sys/devices/pci0000:00/0000:00:02.0/drm/card0
Jan 22 03:48:37 userpc /usr/lib/gdm3/gdm-x-session[1323]: failed to find screen to remove
Jan 22 03:48:51 userpc gnome-shell[1721]: Some code accessed the property 'WindowPreviewMenu' on the module 'windowPreview'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

```

**Comment by TerrenceXu** [comment]
@nick1132 , it due to the default microsoft display driver cannot support GVT-g, you can boot up VM with same mode and try to install the 25.20.100.XXX driver.

**Comment by nick1132** [comment]
@TerrenceXu As you suggested booted in safe mode and installied dch_win64_25.20.100.6519.exe for the internal graphics  Intel UHD Graphics 620 GPU successfully. 

It asked me to reboot. 

When rebooted in normal mode, I get the same blue screen crash with message: "SYSTEM THREAD EXCEPTION NOT HANDLED" - host did not freeze.

Attaching details - see the [syslog.txt](https://github.com/intel/gvt-linux/files/2785904/syslog.txt)

**Comment by TerrenceXu** [comment]
@nick1132, got it, we will borrow a Whiskey Lake for a try and update it.

**Comment by TerrenceXu** [comment]
@nick1132 , @zhangchn 
The 25.20.100.6519 driver with a regression issue which will occurs guest boot up with BSOD
You can use tan older version, like 25.20.100.6448, as below:
https://downloadcenter.intel.com/download/28435/Intel-Graphics-Windows-10-DCH-Drivers

@nick1132 
We can install this driver on our Whiskey lake (Intel(R) Core(TM) i7-8565U) well, I think it also can works on your machine.

**Comment by nick1132** [comment]
@terrencexu Thanks for looking into it. Let me try with older version. I will get back to you. 

Are you able to post you vm command l start up command line or xm configuration, just in case it is the way I start up the vm?

**Comment by TerrenceXu** [comment]
@nick1132 , this is just a example:

/usr/bin/qemu-system-x86_64 -m 2048 -smp 2 -M pc -name vwin10-1 -hda /home/img/win10-1.qcow2 -hdb /home/img/lucas-1.qcow2 -bios /usr/bin/bios.bin -enable-kvm -net nic,macaddr=00:a2:25:06:11:5C -net tap,script=/etc/qemu-ifup -vga cirrus -k en-us -serial stdio -vnc :10 -machine kernel_irqchip=on -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 -cpu host -usb -usbdevice tablet -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/b323e53e-782f-41bb-a7b8-3538d76fc73a,display=off,x-igd-opregion=on

**Comment by nick1132** [comment]
@TerrenceXu,  the driver version you suggested worked, thank you!  I was able to install the intel graphics driver.

After installing intel drivers on the guest i can see 2 displays are available. However defaults to qxl.

I followed the dma buf guide with vnc https://github.com/intel/gvt-linux/wiki/Dma_Buf_User_Guide

I can only see display 1 if qxl is enabled on vnc client, if vga is set to none, the vnc client complains graphics on the guest not initialized yet with the black screen.

What am i missing there?

with the setting
vfio-pci,sysfsdev=.........................,display=**off**,x-igd-opregion=on

If I make display=on it says open gl is not available. How do I get to connect to the display that is connected to the GVT?

**Comment by TerrenceXu** [comment]
@nick1132 ,if you want to boot up vm with dma-buf, you should use display=on.
Looks it related to your host environment, first make you boot up Qemu with enabled OpenGL environment. Then you should make sure your host environment X environment works well before you boot up guest.

**Comment by nick1132** [comment]
@TerrenceXu I confirm now my X environment and opengl is available on the host.  
I can install the older version of the intel driver and boot up the guest with Intel 620 UHD installed properly. All good for a few minutes but host gets this error and crashes:


**vfio_pin_page_external: Task qemu-system-x86 (1892) RLIMIT_MEMLOCK (16777216) exceeded**


I set limits to "unlimited" for the memlock, not sure where it is getting this number from.

Any ideas?

**Comment by nick1132** [comment]
@TerrenceXu 
IT IS WORKING NOW!  - I changed my desktop environment, switched to a clean X11 KDE environment.   Also recompiled the kernel latest staging branch (as of today) 

I am not sure what exactly fixed it but it looks like I had issues with OpenGL in my previous desktop GNOME + Wayland 


Thanks for patiently helping me and thanks for the 8th Gen support!

Cheers

**Comment by TerrenceXu** [comment]
@nick1132 , cool!
What the Wayland issue you met? I guess it is a native issue.

**Comment by nick1132** [comment]
@TerrenceXu 
Fonts were randomly blacking out and coming back when I was on Wayland. Also got random "segmentation fault core dumped" crashes on host.  I am not sure, but root cause can be something else and manifested on Gnome+Wayland.

**Comment by TerrenceXu** [comment]
@nick1132 
Does your issue same as https://github.com/intel/gvt-linux/issues/63? This is a known issue which related to some special host compositor and still under debugging.

**Comment by nick1132** [comment]
@terrencexu Yep. Exactly the same. I can confirm if I disable the compositor, fonts look normal.
