### ISSUE TITLE
[SOLVED] BSOD Page Fault In Nonpaged Area

### ISSUE THREAD

**Issue by XaeroVincent** [01org/gvt-linux#68]
Solved the crashing / BSOD problem by downgrading to previous 25.20.100.6471 driver.

<img src="https://i.postimg.cc/Pq5xPfk0/gvt.png">

**Comment by nick1132** [comment]
The same happening with Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   internal graphics Intel UHD Graphics 620 GPU, when I am installing dch_win64_25.20.100.6519.exe in Win 10 safe mode

**Comment by nick1132** [comment]
Try to increase ulimit for memlock

ulimit -a

Also lbvirtd.service has its own memory limit config. Increase that too and restart the service.. See
https://www.reddit.com/r/VFIO/comments/aiwrzr/12_qemu_hardware_error_vfio_dma_mapping_failed

**Comment by zhangchn** [comment]
@XaeroVincent 
Try upgrading Windows 10 to latest release.

**Comment by TerrenceXu** [comment]
The 25.20.100.6519 driver with a regression issue which will occurs guest boot up with BSOD
You can use an older version, like 25.20.100.6448, as below:
https://downloadcenter.intel.com/download/28435/Intel-Graphics-Windows-10-DCH-Drivers

**Comment by XaeroVincent** [comment]
Thanks. The 25.20.100.6471 driver works. Hopefully the GVT regression gets fixed in the upcoming Intel DCH Windows driver release. :)

**Comment by TerrenceXu** [comment]
@XaeroVincent , yes, the regression will be fixed in the next Intel DCH Windows driver release. :)
