### ISSUE TITLE
Is it possible to use Intel GVT-g as normal user?

### ISSUE THREAD

**Issue by FurretUber** [01org/gvt-linux#69]
I am trying to use Intel GVT-g as a normal user. I set a udev rule to change the group of `/dev/vfio/[0-999]` to `kvm`, which my user is in. When I tried to run the guest errors related to `RLIMIT_MEMLOCK` appeared as the maximum was 16 MB. In response, I increase the limit 160 MB on `/etc/security/limits.d/`.

As the virtual GPUs that can be created on this machine have 64 MB and 128 MB, both values smaller than 160 MB, I expected it would have no problems then. However, an Ubuntu 18.04 guest set with a 64 MB vGPU started to blink constantly and the same error messages started to appear. The guest recovered but this was unexpected.

The messages were like (this is for a 64 MB guest with 128 MB limit):
```
[ 3519.030647] vfio_pin_page_external: Task qemu-system-x86 (17861) RLIMIT_MEMLOCK (134217728) exceeded
[ 3519.030651] gvt: vgpu 1: vfio_pin_pages failed for gfn 0x310e8, ret -12
[ 3519.030657] gvt: vgpu 1: fail: spt 00000000610f441d guest entry 0x310e8083 type 1
[ 3519.030659] gvt: vgpu 1: fail: shadow page 00000000610f441d guest entry 0x310e8083 type 1.
[ 3519.030660] gvt: guest page write error, gpa 3d3c10c0
[ 3519.030675] vfio_pin_page_external: Task qemu-system-x86 (17861) RLIMIT_MEMLOCK (134217728) exceeded
[ 3519.030677] gvt: vgpu 1: vfio_pin_pages failed for gfn 0x310e9, ret -12
[ 3519.030678] gvt: vgpu 1: fail: spt 00000000610f441d guest entry 0x310e9083 type 1
[ 3519.030680] gvt: vgpu 1: fail: shadow page 00000000610f441d guest entry 0x310e9083 type 1.
[ 3519.030682] gvt: guest page write error, gpa 3d3c10c8
```

This is the QEMU command:
```
qemu-system-x86_64 -global PIIX4_PM.disable_s4=1 -M pc,usb=true \
-machine kernel_irqchip=on -global PIIX4_PM.disable_s3=1 \
-name "Ubuntu Bionic" -k pt-br -nodefaults -accel kvm -m 2G -cpu host \
-smp cores=2,threads=1 -netdev user,id=net0 -device e1000,netdev=net0,addr=8 \
-device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/84de1200-c340-48fc-ba40-62f54c76f3ad,rombar=0,display=on,addr=0x3,id=iHD520 \
-device qemu-xhci,id=xhcihub -device usb-audio,id=usbaudio,buffer=6144  \
-device usb-tablet,id=usbtablet -bios /usr/share/ovmf/OVMF.fd \
-display gtk,gl=on -hda "/home/usuario/ubuntu.qcow2" -monitor vc -serial vc 
```

The following image shows the corruption on the guest. This terminal is somewhat beautiful:

![captura de tela_2019-02-03_19-04-44](https://user-images.githubusercontent.com/25434442/52182958-5eee0b00-27ea-11e9-9fdd-289cb903820c.png)

This is a GPU hang when the guest from the screenshot above rebooted: 
[gpuhangigvtg.txt](https://github.com/intel/gvt-linux/files/2826015/gpuhangigvtg.txt)

It is strangely locking much more memory than what I expected: the 64 MB vGPU needs to lock more than 160 MB?

If there is a way to use Intel GVT-g without the need to lock memory, maybe it could allow VMs as  a normal user to work properly.

Host OS: Xubuntu 18.04.1 64-bits;
Kernel: 5.0.0-rc4-drm-tip-543c074ff6a401b2bca5333234a9c13c4b0a5152+;
QEMU version: 3.1.50 (v3.1.0-1407-gb3fc0af1ff-dirty);
CPU: Intel Core i3-6100U;
GPU: Intel HD Graphics 520;
RAM: 8 GB.

**Comment by FurretUber** [comment]
Thank you for the suggestion, setting it to unlimited works, there are no error messages appearing. Probably setting to some other high value would probably work too. As `i915-GVTg_V5_4/description` has:
```
low_gm_size: 128MB
high_gm_size: 512MB
fence: 4
resolution: 1920x1200
weight: 4
```
I suppose 640 MB would be enough. However, increasing the limit so much causes some programs to have problems. Setting the `memlock` limit to a value above 209831 kB makes LightDM enter in a crash loop, making the user unable to log in a graphical session using LightDM. And, as my user is on the group `kvm`, all programs executed by my user have these very high limits, which is undesired.

I would like to know if it is possible to use Intel GVT-g as a normal user with no need to change memlock limits.

**Comment by TerrenceXu** [comment]
Thanks @FurretUber  and @nick1132, we will have a look after Chinese new year.

**Comment by hyuan3** [comment]
VFIO will ping more system memory than low_gm plus high_gm.

**Comment by xiongzha** [comment]
Beside low_gm and high_gm, vGPU should more memory for rendering.
