### ISSUE TITLE
Errors on Skylake/4.13

### ISSUE THREAD

**Issue by Unb6rn** [01org/gvt-linux#7]
After enabling kvmgt I see some errors in log:
`kernel: [drm:new_mmio_info.constprop.17 [i915]] *ERROR* gvt: dup mmio definition offset 22040
kernel: [drm:new_mmio_info.constprop.17 [i915]] *ERROR* gvt: dup mmio definition offset 138124
kernel: [drm:new_mmio_info.constprop.17 [i915]] *ERROR* gvt: dup mmio definition offset 1a028
kernel: [drm:new_mmio_info.constprop.17 [i915]] *ERROR* gvt: dup mmio definition offset 940c
kernel: [drm:new_mmio_info.constprop.17 [i915]] *ERROR* gvt: dup mmio definition offset 4ab0
kernel: [drm:new_mmio_info.constprop.17 [i915]] *ERROR* gvt: dup mmio definition offset 20d4
kernel: i915 0000:00:02.0: Direct firmware load for i915/gvt/vid_0x8086_did_0x1912_rid_0x06.golden_hw_state failed with error -2
kernel: i915 0000:00:02.0: MDEV: Registered`

I am ruinning Arch Linux with the latest kernel-4.13.3 on Intel Core i5 6500 (HD Graphics 530, 8086:1912). Tried it on 4.12.13, problem remained the same.

Kernel command line: kvm-intel.nested=1 intel_iommu=on i915.enable_gvt=1
Modules included in initramfs: btrfs kvmgt vfio vfio_iommu_type1 vfio_pci vfio_virqfd vfio_mdev i915

Also I am unable to create i915-GVTg_V5_4 device with 

> error: uuidgen: write error: No space left on device

but  i915-GVTg_V5_8 creates fine.
Created device is not working for me in Qemu 2.10:
1) The VM screen remains blank with Tianocore
2) OS won't boot with BIOS-tried Manjaro Linux and Ubuntu 17.10

**Comment by Unb6rn** [comment]
Update. After upgrading kernel to 4.13.7, i915-GVTg_V5_4 is working fine, but the problems with OVMF are still there. Errors in kernel log are still present. Tried to use GVTg on Windows 10 1709 guest. It installs fine, then, after installing latest Intel driver, both host and guest systems become very laggy and after a minute or two, guest system would BSOD with VIDEO_TDR_FAILURE.

**Comment by popsUlfr** [comment]
With kernel 4.14 those mmio errors are gone.

The BSOD remains though.

**Comment by TerrenceXu** [comment]
Close it and focus on the latest kernel.
