### ISSUE TITLE
The cursor does not match the screen.

### ISSUE THREAD

**Issue by onlylunix** [01org/gvt-linux#71]
VIDEO  https://yadi.sk/i/Ejg_6JJEBIc-Zw

**Comment by ChristophSchmidpeter** [comment]
As a workaround for the time being: Have you tried using the virtio mouse device, or are you doing so already?

**Comment by onlylunix** [comment]
Added device (-device virtio-mouse-pci):

/usr/bin/qemu-system-x86_64 \\
	-cpu host \\
	-m 2048 -smp 2 -M pc \\
	-hda deb9.1-64.img  \\
	-bios /usr/share/qemu/bios.bin -enable-kvm \\
	-net nic,macaddr=00:A1:00:00:00:1A -net tap,script=no -net user \\
	-rtc base=localtime \\
	-vga none \\
	-display gtk,gl=on -no-quit \\
	-machine kernel_irqchip=on \\
	-global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 \\
	-device vfio-pci,sysfsdev=${r}/${id},display=on,x-igd-opregion=on \\
	-device virtio-mouse-pci 

The behavior has not changed. Bug is present.

**Comment by ivanstepanovftw** [comment]
I think its your display manager

**Comment by TerrenceXu** [comment]
Have you tried to add "usb -usbdevice tablet" in your boot up VM command line?

**Comment by onlylunix** [comment]
> Have you tried to add "usb -usbdevice tablet" in your boot up VM command line?

With "-usb -usbdevice tablet" the bug is present the same.

**Comment by onlylunix** [comment]
The issue has been resolved.
