### ISSUE TITLE
[intel-media-driver] Fail to encode with mediated pass-through GPU

### ISSUE THREAD

**Issue by snir911** [01org/gvt-linux#72]
I have a VM with virtual mediated pass-through GPU (Intel GVT-g), when i'm trying to encode h264/h265 on the guest with intel-media-driver using the libva-utils "h264encode" encoding utility it fails with the following error:
"setup_encode:caCreateContext (1306) failed,exit" (returned value 1).

Additional info:
-Fedora 29 both on host and guest, encoding work fine on host.
-It works well with intel-vaapi-driver(i965) (the issue is only with intel-media-driver(iHD))
-vainfo does show these encoding capabilities as available 
-SKL cpu
-I get similar error also with hevcencode (h265 encoding utility)
 [reference](https://github.com/intel/media-driver/issues/520)

**Comment by TerrenceXu** [comment]
We will have a look, what is the kernel version you used in host and guest?

**Comment by snir911** [comment]
host: 4.19.2-301
guest: 4.20.6-200

**Comment by snir911** [comment]
Working on f30
host: 5.1.11
Guest: 5.0.11
