### ISSUE TITLE
[Video] Apex Legends video game works with GVT-g + Dmabuf

### ISSUE THREAD

**Issue by XaeroVincent** [01org/gvt-linux#73]
Hello,

I wanted to share that the Apex Legends game works with a QEMU & GVT-g configuration. The host is Manjaro Linux with kernel 4.20 and the guest is Windows 10 w/ Intel HD 520 passed through, 2 virtual cores, and 4GB RAM shared with the VM. Hopefully future GVT-validated Windows drivers offer better performance for this title.

It would be super interesting to see this game tested with Intel UHD 630, Iris Plus 6x0 and Iris Pro 580, 8GB or more RAM shared, and 4 or more cores shared to the guest.

This is an exciting discovery as the game is currently broken on Linux Wine & Proton due to the Easy Anti Cheat rootkit / kernel-space software used by the game being incompatible with those compatibility layers.

https://www.youtube.com/watch?v=95sLF_tLdWQ

**Comment by TerrenceXu** [comment]
Thanks @XaeroVincent for the good news! Does any issue be found when you running Apex Legends on it?

**Comment by XaeroVincent** [comment]
There are some black box textures on certain character models and the framerate is overall poor with crackling and skipping audio. However, the GVT supported driver is older than the newest Windows BETA driver that announces support for Apex Legends. The BETA Windows driver released 2/14/2019 causes Windows blue screen crash panic with GVT enabled.

**Comment by cxdong** [comment]
As there is a commit from zhenyu for this, I am going to close this issue. Please feel free to reopen or create new one if this issue is seen again.
