### ISSUE TITLE
Direct firmware load failed with error -2 and mdev_supported_types missing (Coffee Lake)

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [01org/gvt-linux#77]
I have built the gvt-staging, but after booting with required kernel parameters (see below) _mdev_supported_types_ does not appear. Dmesg prints the error (see also [DmesgGvtStaging.txt](https://github.com/intel/gvt-linux/files/2942076/DmesgGvtStaging.txt)):

_i915 0000:00:02.0: Direct firmware load for i915/gvt/vid_0x8086_did_0x3e9b_rid_0x00.golden_hw_state failed with error -2_

System: Arch Linux
CPU: Coffee Lake (i7-8750H)
GPU: Optimus (UHD Graphics 630 + Quadro P600)
Driver: bumblebee 3.2.1-20 xf86-video-intel 1:2.99.917+860+g3a2dec17-1 nvidia-dkms 418.43-4
Branch: gvt-staging (built 03.03.19)
Kernel Parameters for dmesg: i915.enable_gvt=1 kvm.ignore_msrs=1 intel_iommu=on ignore_loglevel drm.debug=2 "dyndbg=file gvt +p"

**Comment by CuriousTommy** [comment]
@albionxy I am glad I am not the only one with this issue. I am having a similar problem on my Fedora machine (Dell Precision 5510). When I try the latest gvt-linux kernel, the `mdev_supported_types` directory does not appear.

However, if I use the official Fedora Kernel, I can create the mdev device, but the `iommu_group` directory does not exist.

Edit: You can find my bug report here: #74

**Comment by ChristophSchmidpeter** [comment]
@CuriousTommy: Thank you for your info! Good to know that it is not just some misconfiguration on my system or something.

I can reproduce the issue also with gvt-staging-2019y-01m-10d-11h-40m-01s, which is mentioned to work for Coffee Lake in #14 (always reproducible).
Did anybody get it to work with Coffee Lake (especially on a notebook) for gvt-staging-2019y-01m-10d-11h-40m-01s or newer?

**Comment by CuriousTommy** [comment]
This might be a long shot, but maybe the `vfio_mdev` module is not loaded on your system. Once I loaded it on my machine, I was able to get it working again!

**Comment by TerrenceXu** [comment]
The error your met is not a bug and it will not occurs mdev_supported_types load failed.
@albionxy The first tag support Coffee Lake platform should be "gvt-staging-2019y-02m-22d-16h-20m-42s", you can use a newer tag for a try.

**Comment by ChristophSchmidpeter** [comment]
@CuriousTommy Thank you, your hint was spot on! Adding _kvmgt vfio-iommu-type1 vfio-mdev_ to _MODULES=(...)_ in _/etc/mkinitcpio.conf_ did the trick for me. I guess I've read the respective part in the tutorial over, as this used to be not required, as far as I understand.

**Comment by ChristophSchmidpeter** [comment]
@TerrenceXu: Thank you for the hint. I can boot the gvt-staging (3.3.19) kernel with Windows 10 now. However, a popup saying 'This installation package is not supported by this processor type' shows up when I try to install the Intel installer (tried 25.20.100.6577 and 25.20.100.6519) and 'Error 31' remains. Strangely it says 'Microsoft Basic Display Adapter' instead of 'Intel UHD Graphics 630', which I would have expected to say even before installing the driver. (qemu script I used: [TestGvt.txt](https://github.com/intel/gvt-linux/files/2952016/TestGvt.txt))
What am I missing, or which driver do I need for Windows 10 x64 with Coffee Lake?

**Comment by TerrenceXu** [comment]
@albionxy  You can try to modify "-vga qxl" to "-vga none", since DMA-BUF not support multi monitor display .

**Comment by ChristophSchmidpeter** [comment]
@TerrenceXu: For some reason I can now install the driver, even with _"-vga qxl"_. Not sure why.
So the _mdev_supported_types_ appears now. 

However, the

`i915 0000:00:02.0: Direct firmware load for i915/gvt/vid_0x8086_did_0x3e9b_rid_0x00.golden_hw_state failed with error -2`

error message remains. Either it indicates a real issue, or it is wrong and should be removed (or changed from _error_ to _info_, or something). But in either case, I think it is a bug.

**Comment by TerrenceXu** [comment]
@albionxy , it is not a real issue, and we will remove or change from erro to info, thank you for your reminder!

**Comment by joyqing** [comment]
> The error your met is not a bug and it will not occurs mdev_supported_types load failed.
> @albionxy The first tag support Coffee Lake platform should be "gvt-staging-2019y-02m-22d-16h-20m-42s", you can use a newer tag for a try.

hello Mr Xu, could you please tell me how to use the tag to try. I'm a newbie of IGPU passthrough. I'd like to pass through my i7-8700k UHD630 to VM MacOS. My system is below:
Linux version 5.0.18-1-MANJARO (builduser@development) (gcc version 8.3.0 (GCC)) #1 SMP PREEMPT Wed May 22 17:35:29 UTC 2019
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.0-x86_64 root=UUID=427750eb-168c-4724-af59-14436953be7d rw iommu=pt intel_iommu=on quiet iommu=pt intel_iommu=on i915.enable_gvt=1 default_hugepagesz=1G hugepagesz=1G hugepages=32
kvm_intel             311296  0
kvmgt                  32768  0
mdev                   24576  2 kvmgt,vfio_mdev
kvm                   745472  2 kvmgt,kvm_intel
irqbypass              16384  2 vfio_pci,kvm
vfio                   36864  4 kvmgt,vfio_mdev,vfio_iommu_type1,vfio_pci

I created a VM, passed through AMD rx580 and installed MacOS 10.15. It works fine. Now I want to add UHD630 to the VM but I can't find the folder "mdev_supported_types". Could you please give me some links for newbie to learn? Thank you very much. 

Aaron

**Comment by ChristophSchmidpeter** [comment]
@TerrenceXu 
The error message still appears with linux-5.4.7. Could you please remove/fix the error message, because the error message might confuse people.

**Comment by TerrenceXu** [comment]
You can run "modprobe kvmgt" in your host and try again. :)

**Comment by ChristophSchmidpeter** [comment]
@TerrenceXu I was referring to my previous comment that the error message still appears:

> However, the
> `i915 0000:00:02.0: Direct firmware load for i915/gvt/vid_0x8086_did_0x3e9b_rid_0x00.golden_hw_state failed with error -2`
> error` message remains. Either it indicates a real issue, or it is wrong and should be removed (or changed from error to info, or something). But in either case, I think it is a bug.

and that it would be removed:
> @albionxy , it is not a real issue, and we will remove or change from erro to info, thank you for your reminder!

But I still get this error message with the current kernel. Thus, I wanted to remind that it still needs to be removed.

**Comment by shunlir** [comment]
@TerrenceXu, I also get the error message on kernel 5.4.23 which is lts, if not bug, could the error message be removed or changed to more informational?
>  i915 0000:00:02.0: Direct firmware load for i915/gvt/vid_0x8086_did_0x3e92_rid_0x00.golden_hw_state failed with error -2

**Comment by reedog117** [comment]
I still get this error with kernel `5.4.41-1-pve #1`

**Comment by nikisalli** [comment]
I still get this error in 5.7.4 arch linux kernel

**Comment by zhenyw** [comment]
the golden state firmware load fail is not fatal, if not found, gvt will use hw value instead, it's just an optimization for module load, as it's error message in kernel api, so can not be skipped in gvt

**Comment by mailinglists35** [comment]
this kernel message still appears despite passthrough working

`apr 29 19:35:20 linux kernel: i915 0000:00:02.0: Direct firmware load for i915/gvt/vid_0x8086_did_0x3e92_rid_0x00.golden_hw_state failed with error -2`

ubuntu jammy 22.04LTS kernel 5.15.0-27-generic

**Comment by smsilva98** [comment]
I'm also getting the "golden_hw_state failed with error -2" error, it doesn't stop me from creating and using vgpu's though, what does this error affect?

System: Arch Linux (5.17.5-arch1-1)
CPU: Kabby Lake (i7-8550U)
GPU: UHD Graphics 620 (Gen9)
Driver: mesa
Mkinitcpio Modules: kvmgt vfio vfio-iommu-type1 mdev
Kernel Parameters: intel_iommu=on i915.enable_guc=0 i915.enable_gvt=1

**Comment by ChristophSchmidpeter** [comment]
@smsilva98 It seems to be a superfluous error message, which however may confuse clutters the log. Not being able to reopen the ticket myself, I suggest you open a new ticket (unless @TerrenceXu reopens this one)

**Comment by smsilva98** [comment]
@ChristophSchmidpeter Okay thank you, I opened a new issue at #212
