### ISSUE TITLE
Doesn't work on ubuntu 17.04. firmware doesn't load.

### ISSUE THREAD

**Issue by ghost** [01org/gvt-linux#8]
Processor: i3-6006u/HD 520 iGPU.
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.10.0-37-generic.efi.signed root=UUID=--- ro i915.enable_gvt=1 kvm.ignore_msrs=1 intel_iommu=igfx_off drm.debug=0
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-4.10.0-37-generic.efi.signed root=UUID=--- ro i915.enable_gvt=1 kvm.ignore_msrs=1 intel_iommu=igfx_off drm.debug=0
[    1.935020] i915 0000:00:02.0: Direct firmware load for i915/gvt/vid_0x8086_did_0x1916_rid_0x0007.golden_hw_state failed with error -2
[  122.559509] [drm:intel_vgpu_create [kvmgt]] *ERROR* gvt: failed to create intel vgpu: -28
[  124.670334] [drm:intel_vgpu_create [kvmgt]] *ERROR* gvt: failed to create intel vgpu: -28
[  133.533074] [drm:intel_vgpu_create [kvmgt]] *ERROR* gvt: failed to create intel vgpu: -28
[  301.405430] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 0 len 1 val 0
[  350.323526] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO d40(4B) val ffeff0f1
[  350.323569] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO d48(4B) val ffeff0f1
[  350.831073] WARNING: CPU: 1 PID: 1812 at /build/linux-d6ZFKv/linux-4.10.0/drivers/gpu/drm/i915/gvt/gtt.c:1818 intel_vgpu_emulate_gtt_mmio_write+0x1cb/0x240 [i915]
[  359.351766] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 24e0 len 4 val 4de0
[  359.351809] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 24e4 len 4 val 4de4
[  359.351848] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 24e8 len 4 val 2248
[  359.353215] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 2120(4B) val ffeff0f1
[  359.353256] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 2124(4B) val ffeff0f1
[  359.353452] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO fdc(4B) val ff5fbbe9
[  359.353482] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO fdc len 4 val ff5fbbe9
[  359.353655] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 20d4(4B) val ffeff0f1
[  359.353684] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 20d4 len 4 val ffeff0f5
[  359.361589] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 22040(4B) val 0
[  359.367828] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 4448c(4B) val 0
[  359.367864] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 4448c len 4 val 6
[  359.367903] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 44484(4B) val 0
[  359.367933] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 44484 len 4 val 0
[  359.367963] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 4448c(4B) val 6
[  359.367992] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 4448c len 4 val 66
[  359.368021] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 44484(4B) val 0
[  359.368049] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 44484 len 4 val 0
[  359.368078] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 4448c(4B) val 66
[  359.368138] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 4448c len 4 val 666
[  359.368166] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 44484(4B) val 0
[  359.368237] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 44484 len 4 val 0
[  433.701764] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 0 len 1 val 0
[  508.112245] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 0 len 1 val 0
[  524.070266] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO d40(4B) val ffeff0f1
[  524.070309] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO d48(4B) val ffeff0f1
[  531.857172] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 24e0 len 4 val 4de0
[  531.857216] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 24e4 len 4 val 4de4
[  531.857255] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 24e8 len 4 val 2248
[  531.857942] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 2120(4B) val ffeff0f1
[  531.857982] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 2124(4B) val ffeff0f1
[  531.858209] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO fdc(4B) val ff5fbbe9
[  531.858239] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO fdc len 4 val ff5fbbe9
[  531.858412] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 20d4(4B) val ffeff0f1
[  531.858440] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 20d4 len 4 val ffeff0f5
[  531.865506] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 22040(4B) val 0
[  531.871164] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 4448c(4B) val 0
[  531.871200] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 4448c len 4 val 6
[  531.871239] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 44484(4B) val 0
[  531.871270] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 44484 len 4 val 0
[  531.871301] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 4448c(4B) val 6
[  531.871331] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 4448c len 4 val 66
[  531.871360] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 44484(4B) val 0
[  531.871390] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 44484 len 4 val 0
[  531.871419] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 4448c(4B) val 66
[  531.871448] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 4448c len 4 val 666
[  531.871477] [drm:intel_vgpu_emulate_mmio_read [i915]] *ERROR* gvt: vgpu1: read untracked MMIO 44484(4B) val 0
[  531.871506] [drm:intel_vgpu_emulate_mmio_write [i915]] *ERROR* gvt: vgpu1: write untracked MMIO 44484 len 4 val 0

**Comment by TerrenceXu** [comment]
The firmware at https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
