### ISSUE TITLE
sched_policy.c - Timer is never cancelled

### ISSUE THREAD

**Issue by daramos** [01org/gvt-linux#80]
In `intel_gvt_destroy_vgpu` the `intel_vgpu_clean_sched_policy` function is called before `idr_remove(&gvt->vgpu_idr, vgpu->id);` is executed:

```c
void intel_gvt_destroy_vgpu(struct intel_vgpu *vgpu)
{
	struct intel_gvt *gvt = vgpu->gvt;

	mutex_lock(&vgpu->vgpu_lock);

	WARN(vgpu->active, "vGPU is still active!\n");

	intel_gvt_debugfs_remove_vgpu(vgpu);
------->intel_vgpu_clean_sched_policy(vgpu);<-------

[...]

	mutex_unlock(&vgpu->vgpu_lock);

	mutex_lock(&gvt->lock);
------->idr_remove(&gvt->vgpu_idr, vgpu->id);<-------
	if (idr_is_empty(&gvt->vgpu_idr))
		intel_gvt_clean_irq(gvt);
	intel_gvt_update_vgpu_types(gvt);
	mutex_unlock(&gvt->lock);

	vfree(vgpu);
}
```

`intel_vgpu_clean_sched_policy` calls the `tbs_sched_clean_vgpu` function which makes an assumption that the vgpu id entry for the vgpu being removed has already been freed. 
```c
	/* this vgpu id has been removed */
	if (idr_is_empty(&gvt->vgpu_idr))
		hrtimer_cancel(&sched_data->timer);
```

Because the vgpu id has not yet been removed (which makes this assumption incorrect) the timer is never cancelled once all VGPUs have been destroyed.

**Comment by maximlevitsky** [comment]
I confirm that. I meanwhile added a hack to stop it when the vgpu is destroyed which is wrong when you have more that one vgpu.

**Comment by coxuintel** [comment]
This issue should be fixed by https://github.com/intel/gvt-linux/commit/04d6067f1f19e70a418f92fa3170cf7fe53b7fdf
