### ISSUE TITLE
Libvirt dmabuf example fails to start with "egl: no drm render node available"

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [01org/gvt-linux#81]
With my current host system I can run the Dma_Buf_User_Guide example _3 Usage -> b. GTK_. However, the example _d. Libvirt_ fails to start with the output:
```
qemu-system-x86_64: warning: nic video0 has no peer
qemu-system-x86_64: egl: no drm render node available
```
Interestingly, the dmesg shows many errors similarly to #79 in the following form:
```
kvm [nnnn]: vcpu0, guest rIP: 0xfffffnnnnnnnnnn ignored rdmsr: 0xnnn
```
In contrast to #79, however, the machine does not start at all, whereas with #79 the machine starts and gvt works with BIOS, but not with UEFI.

Files:
------------------
[Win10Bios.txt](https://github.com/intel/gvt-linux/files/2967320/Win10Bios.txt)
[LibvirtOutput.txt](https://github.com/intel/gvt-linux/files/2967304/LibvirtOutput.txt)
[dmesg.txt](https://github.com/intel/gvt-linux/files/2967342/dmesg.txt)

Host System:
------------------
System: Thinkpad P72
OS: Arch Linux
CPU: Coffee Lake (i7-8750H)
GPU: Optimus system with UHD Graphics 630 + Quadro P600
Driver: xf86-video-intel 1:2.99.917+860+g3a2dec17-1 nvidia-dkms 418.43-4
Branch: gvt-staging (built 07.03.19)

**Comment by Ordspilleren** [comment]
Instead of using
```
<qemu:arg value='-set'/>
<qemu:arg value='device.video0.driver=ne2k_pci'/>
```
in the QEMU args, try simply setting the video type to "none":
```
<video>
    <model type='none'/>
</video>
```

**Comment by ChristophSchmidpeter** [comment]
@Ordspilleren Thank you for the info. Removing

```
<qemu:arg value='-set'/>
<qemu:arg value='device.video0.driver=ne2k_pci'/>
```

Solves the
```
qemu-system-x86_64: warning: nic video0 has no peer
```
issue. However, the egl erros remain:

```
qemu-system-x86_64: egl: no drm render node available
qemu-system-x86_64: egl: render node init failed
```

Does anyone know what it indicates, and how to resolve this egl error?

**Comment by ChristophSchmidpeter** [comment]
@TerrenceXu : What does the 'device.video0.driver=ne2k_pci' setting do? And do you know what causes 'egl: no drm render node available'?

**Comment by Ordspilleren** [comment]
> @TerrenceXu : What does the 'device.video0.driver=ne2k_pci' setting do? And do you know what causes 'egl: no drm render node available'?

`device.video0.driver=ne2k_pci` does the same thing as setting the video model type to none, but the latter is the better option. You should also remove
```
<qemu:arg value='-set'/>
    <qemu:arg value='device.hostdev0.display=on'/>
    <qemu:arg value='-display'/>
<qemu:arg value='egl-headless'/>
```
from the QEMU args and set `display='on'` in the hostdev definition.

**Comment by TerrenceXu** [comment]
Thanks @Ordspilleren  for the explanation , you are right. :)
@TitusLabienus , you can try whether you can boot up VM successfully with https://github.com/intel/gvt-linux/wiki/Dma_Buf_User_Guide#a-spicy.
I think it should be the same result as d-libvirt .

**Comment by ChristophSchmidpeter** [comment]
@TerrenceXu Yes I can boot the a-spicy, but not the d-libvirt one (all 3 qemu samples work fine, but the libvirt one not), even when I configure them in a way that the d-libvirt one results in the same `qemu-system-x86_x64 [...]`command line arguments as the a-spicy one.

**Comment by ChristophSchmidpeter** [comment]
Here the files:

[aSpicy.sh.txt](https://github.com/intel/gvt-linux/files/2975754/aSpicy.sh.txt)
[dLibvirt.xml.txt](https://github.com/intel/gvt-linux/files/2975755/dLibvirt.xml.txt)
[dLibvirt.log](https://github.com/intel/gvt-linux/files/2975756/dLibvirt.log)


The aSpicy.sh works, but the dLibvirt.xml does not work.
It just fails with (see dLibvirt.log)

```
qemu-system-x86_64: egl: no drm render node available
qemu-system-x86_64: egl: render node init failed
```

@TerrenceXu : What do I need to do to solve the 'no drm render node' issue?

**Comment by ChristophSchmidpeter** [comment]
What I could imagine is that it us some permissions related issue like here:
[Permission denied when start guest with egl-headless display](https://bugzilla.redhat.com/show_bug.cgi?id=1628892)
It suggests to change some ownerships to qemu:qemu, but it I couldn't get it to work so far.

**Comment by TerrenceXu** [comment]
@TitusLabienus , I cannot find any error configuration in your xml file. Can you try to boot up VM with dLibvirt.log command directly?
BTW, why your boot up VM command without any image file?

**Comment by ChristophSchmidpeter** [comment]
@TerrenceXu: I boot without image for the sake of a minimal / easier reproducible example. Yes, I can boot the dLibvirt.log without any issues. My suspicion is, that it is some permissions issue. Do you operate Libvirt as a normal user, or as root? (I.e. does `$virsh start MyVm` work on your system for non-gvt VMs, or do you have to type `$sudo virsh start MyVm`?) For the letter case, which Polkit and or libvirt.conf, qemu.conf, etc. changes did you have to do to achieve that?

**Comment by TerrenceXu** [comment]
@TitusLabienus, generally we start VM with root account.

**Comment by ChristophSchmidpeter** [comment]
Does anybody else have this issue?

**Comment by ghost** [comment]
@TitusLabienus Yep, running latest Arch and having the same issues. Spicy starts, GTK starts with sudo -E, libvirt throws the same error as yours.

**Comment by ghost** [comment]
It looks like this is a permissions issue. After adding udev rule:
`SUBSYSTEM=="vfio", OWNER="root", GROUP="kvm"`
I am able to run qemu from my regular account (which is in group kvm, of course).
However another issue arises-with that rule libvirt (virt-manager) would not start any machine at all.
Any workarounds? Or should I report it to their bugzilla?

**Comment by Vespasian639** [comment]
I'm having this same issue.  I'm running Ubuntu 19.04 which has libvirt 5.0.0 and QEMU 3.1.0.  Using Dma_Buf_User_Guide example 3d, libvirt fails to start with the same errors as posted by TitusLabienus.

Since the last post was in early May, I'm just wondering, was any workaround discovered?
