### ISSUE TITLE
RDP on Windows 10

### ISSUE THREAD

**Issue by cagnulein** [01org/gvt-linux#82]
Hi, i'm using GVT on a 7th generation and everything works flawless (Windows 10 guest).
On the host i can access to the guest via VNC and even the 3D performance are ok.
But if i try to use RDP (xfreerdp) the 3D is slow like hell. Is it by design? Could i tweak in some way this behaviour?
Thanks

**Comment by TerrenceXu** [comment]
I thinks it RDP remote protocol problem, you can compare the data between "RDP to Windows10 guest" and "RDP to Windows10 native".

**Comment by gnattu** [comment]
You have to modify Group Policy Editor to enable Hardware encoder for RDP. However, CPU usage is still very high on windows10, even if you enabled hardware encoding in Group Policy.
The 3D performance is OK if you give your VM a huge amount of vCores to run AVC Encoding.
Launch the Event Viewer in Windows and navigate to Applications and Services Logs -> Microsoft -> Windows -> RemoteDesktopServices-RdpCoreTS, look for event id 170. If the id is absent then software encoding is used.
I've checked that id 170 present and reports using Intel QSV, but CPU is still very busy(~30% usage by RDP server with 4 vCores) when playing videos.
Using Iris Pro 580.

**Comment by TerrenceXu** [comment]
@gnattu good finding!

**Comment by cagnulein** [comment]
i guess i can close it now
