### ISSUE TITLE
Add CONFIG_UDMABUF to GVTg or DMABUF Wiki

### ISSUE THREAD

**Issue by cagnulein** [01org/gvt-linux#83]
I think you should add CONFIG_UDMABUF to the requirements of the kernel build in the GVTg and/or DMABUF wifi. What do you think?

**Comment by TerrenceXu** [comment]
Hi, CONFIG_UDMABUF is not needed by GVTg dma-buf, it is for userspace dma-buf.

**Comment by cagnulein** [comment]
ok, never mind.
