### ISSUE TITLE
Which of the library dependencies are required if you compile the kernel and qemu on a different computer?

### ISSUE THREAD

**Issue by melyux** [01org/gvt-linux#87]
Say I didn't want all the gunk necessary for compiling the custom kernel and qemu on the host computer. Say I just compile it all in a docker and then only take the binaries to use on the host. Do I still need all of the following for simply running qemu on the host?

`apt-get install git libfdt-dev libpixman-1-dev libssl-dev vim socat libsdl1.2-dev libspice-server-dev autoconf libtool xtightvncviewer tightvncserver x11vnc libsdl1.2-dev uuid-runtime uuid uml-utilities bridge-utils python-dev liblzma-dev libc6-dev libegl1-mesa-dev libepoxy-dev libdrm-dev libgbm-dev libaio-dev libusb-1.0.0-dev`

**Comment by TerrenceXu** [comment]
if you want to make qemu in docker, i think you needn't these libraries in host except some basic tools you needed.
