### ISSUE TITLE
device does not support requested feature x-vga

### ISSUE THREAD

**Issue by l-cd** [01org/gvt-linux#88]
command line:
/usr/bin/qemu-system-x86_64 \
    -m 2048 -smp 2 -M pc \
    -name gvt-g-guest \
    -bios /usr/bin/bios.bin -enable-kvm \
    -k en-us \
    -serial stdio \
	-vga none\
    -vnc :1 \
    -machine kernel_irqchip=on \
    -global PIIX4_PM.disable_s3=1 -global PIIX4_PM.disable_s4=1 \
    -cpu host  -usb -usbdevice tablet  \
    -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/8afd6be6-3e6a-11e9-ac86-571db62e56d6,rombar=0,display=off,x-igd-opregion=on,x-vga=on
--------------------------------------------------------
result:
set vendor id(8086) for devfn(0)
set vendor id(8086) for devfn(8)
set vendor id(8086) for devfn(10)
set vendor id(8086) for devfn(9)
set vendor id(8086) for devfn(a)
set vendor id(8086) for devfn(b)
set vendor id(0) for devfn(18)
qemu-system-x86_64: -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/8afd6be6-3e6a-11e9-ac86-571db62e56d6,rombar=0,display=off,x-igd-opregion=on,x-vga=on: vfio error: 8afd6be6-3e6a-11e9-ac86-571db62e56d6: unexpected VGA info, flags 0x0, size 0x0
device does not support requested feature x-vga
-------------------

How to support x-vga?

**Comment by aamerik-salesforce** [comment]
Hello, did you fix this issue?
