### ISSUE TITLE
ramfb: windows 10 guest reboot upon loading driver

### ISSUE THREAD

**Issue by zhangchn** [01org/gvt-linux#90]
In a dmabuf Windows 10 guest using device [`vfio-pci-nohotplug` with `ramfb=on`](https://patchwork.ozlabs.org/patch/970397/), guest panicked and QEMU rebooted after loading guest GPU driver.

In contrast, `vfio-pci` without `ramfb` parameter booted normally.

**Comment by HouQiming** [comment]
Some of my research on ramfb-related crashes:

Certain hardware / driver combinations write garbage into the ramfb configuration space, which can make QEMU create a software surface with ridiculous dimensions. Could fix by adding proper checks in the ramfb code

During guest driver load, the display switches between ramfb and dmabuf, during which QEMU could call `glTexSubImage2D` on an unpredictable texture (e.g. the eglImage bound to a dmabuf). This crashes the QEMU process on my NUC at a high probability. Adding a `glBindTexture` before `glTexSubImage2D` fixes the crash. Even though calling it on a bad texture is a QEMU bug, the rogue `glTexSubImage2D` shouldn't crash anything. The non-deterministic behavior also seems to indicate a race condition inside the driver.

**Comment by marcel-apf** [comment]
Fixed by @HouQiming's patches (thanks!), already merged in latest QEMU (master branch of the official repository).

**Comment by dingzhc** [comment]
@TerrenceXu should be closed.
