### ISSUE TITLE
Host kernel panic upon loading driver

### ISSUE THREAD

**Issue by nikp123** [01org/gvt-linux#91]
So whenever I try to load the guest driver (be it in Linux or Windows) my host ArchLinux machine freezes i.e. probably kernel panic (5.0.7-zen1-1-zen).

My machine's a Skylake i7-6700HQ w/ HD Graphics 530

I was using libvirt because qemu alone gave me MEMLOCK issues.

Attaching the appropriate [kernel log](https://github.com/intel/gvt-linux/files/3104460/kernellog.txt), [kernel args](https://github.com/intel/gvt-linux/files/3104451/cmdline.txt)
 and [libvirt config](https://github.com/intel/gvt-linux/files/3104467/win10.txt).

**Comment by TerrenceXu** [comment]
Hi， we cannot reproduce this issue with i7-6799HQ and with the same libvirt config as you, can you try to download our latest gvt-staging or gvt-stable-4.17 code for a try?

**Comment by nikp123** [comment]
Sorry for being a bit dumb, but I can't get the kernel to compile for some reason. It just keeps resetting the config once I try to do ``make -j$(nproc)``

**Comment by nikp123** [comment]
@TerrenceXu can confirm its a zen kernel issue. I just compiled the gvt-staging and it works fine
