### ISSUE TITLE
Is Broadwell missing EDID support?

### ISSUE THREAD

**Issue by tinywrkb** [01org/gvt-linux#92]
QEMU 4.0.0, Linux 5.1.0rc6  
Xeon E3-1265L v4

I tried to take advantage of the new EDID feature to set a resolution like I do for QXL but I received the following error message: `xres and yres properties need edid support`

Is [drm/i915/gvt: add VFIO EDID region/vgpu.c#line432](https://github.com/intel/gvt-linux/commit/39c68e87bc50a71bcfe93582d9b0673ef30db418#diff-e6253cef2c51cb94be0e6f7a89361e77R432) means that Broadwell isn't supported yet?

This is my vfio-pci device option:
`-device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/4cc1007d-f58a-42d5-b0de-f007fce9959c,rombar=0,display=on,x-igd-opregion=on,xres=1920,yres=1080`

For reference here's my full qemu command:
`qemu-system-x86_64 -drive file=/home/user/data/vm/qemu/fs/w10rs5-029-test.qcow2,format=qcow2,if=virtio -m 8192 -enable-kvm -M q35 -cpu host,+vmx -smp 4,sockets=1,cores=4,threads=1 -bios /usr/share/qemu/bios.bin -vga none -display gtk,gl=on,zoom-to-fit=on -full-screen -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/4cc1007d-f58a-42d5-b0de-f007fce9959c,rombar=0,display=on,x-igd-opregion=on,xres=1920,yres=1080 -net nic,model=virtio,macaddr=52-54-00-12-34-56 -net user,smb=/home/user/public/vm-share,hostfwd=::9999-:3389,hostfwd=::9000-:9000 -usb -device virtio-balloon -device pvpanic -device virtio-tablet-pci -show-cursor -device virtio-keyboard-pci -device virtio-rng-pci -device virtio-serial -rtc base=localtime -soundhw hda -daemonize
`

**Comment by hyuan3** [comment]
Yes, Broadwell is not suppported.

**Comment by tinywrkb** [comment]
Thank you for answering. I hope this would be rectified.
