### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ivanstepanovftw** [01org/gvt-linux#93]
Is it your team again? Tried to launch csgo_linux64 with no free memory, pc became frozen, OOM killer too. Why, Intel, why?
[crash.log](https://github.com/intel/gvt-linux/files/3122294/crash.log)

**Comment by TerrenceXu** [comment]
It looks not like a GVT issue, please try to use i915.enable_gvt=0 in grub and  try again.

**Comment by cxdong** [comment]
@ivanstepanovftw, I am going to close this issue. Please try if there is still issue on your side by following TerrenceXu's suggestion. And if observe any GVT related issue, please fee free to open a new one. Thanks!
