### ISSUE TITLE
Wrong scaling on Gnome 3

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [01org/gvt-linux#98]
I have switched from Xfce to GNOME 3. Starting a GVT enabled VM results in a too small scaled display output (see screenshot) with GNOME. With other environments like Xfce it works normally.

[dmesg.txt](https://github.com/intel/gvt-linux/files/3172595/dmesg.txt)
[StartVM.sh.txt](https://github.com/intel/gvt-linux/files/3172614/StartVM.sh.txt)

Windowed mode:
![WrongScalingWindowed](https://user-images.githubusercontent.com/3390179/57618567-1b8eff80-7584-11e9-8a8f-79d957c2346e.png)

Fullscreen mode:
![WrongScalingFullscreen](https://user-images.githubusercontent.com/3390179/57618571-1f228680-7584-11e9-93af-f549e478e0d4.png)

Host System:
------------------
System: Thinkpad P72
OS: Arch Linux
CPU: Coffee Lake (i7-8750H)
GPU: Optimus system with UHD Graphics 630 + Quadro P600
Driver: xf86-video-intel 1:2.99.917+863+g6afed33b-1
Kernel: 5.1 vanilla  (linux-mainline 5.1-1)

**Comment by ChristophSchmidpeter** [comment]
Is Wayland supported by GVT? (Xfce uses X11 and GNOME uses Wayland)

**Comment by rugubara** [comment]
I use X11 with Gnome 3 with Thinkpad P52 (3840x2180 on 15"). I also experience this behaviour

**Comment by rugubara** [comment]
I was able to get help in spice-gtk issue tracker https://gitlab.freedesktop.org/spice/spice-gtk/issues/99# 
Works for me ok now.

**Comment by TerrenceXu** [comment]
GVT is support Wayland as host OS, I cannot reproduce this issue on Ubuntu18.04, did you tried Ubuntu environment?

**Comment by franz82** [comment]
Same issue here:

System: Thinkpad X1 Carbon 7th Gen
OS: Arch Linux
CPU: Whiskey Lake (i5-8265U)
GPU: Intel UHD 620
Monitor: 4k 3840x2160
Driver: mesa 19.1.5-1
Kernel: 5.2.11-arch1-2-ARCH
DE: Xfce 4.14 with Window Scaling enabled

![QUK6fXR](https://user-images.githubusercontent.com/2310533/64069295-59a15380-cc47-11e9-8246-618e5ef8c304.png)

**Comment by rugubara** [comment]
@fran82, the issue is in spice-gtk. If you can apply a patch and recompile spice-gtk, it starts to work.

**Comment by franz82** [comment]
> @Fran82, the issue is in spice-gtk. If you can apply a patch and recompile spice-gtk, it starts to work.

Thanks @rugubara I recompiled spice-gtk from last master branch.
How can I set up virt manager so it can use the recent spice-gtk compiled and installed? (in a different path then the spice-gtk package)

**Comment by rugubara** [comment]
Having multiple versions of the package is not a good idea. I suggest you
uninstall the binary package and re-configure/compile/install your master
package to the same prefix that was used for your binary package.
I assume that your master spice-gtk has configured and been installed to
/usr/local, while all other packages are installed to /usr.

I can see that spice-gtk master has switched form autotools to meson. So
you can look up here https://mesonbuild.com/Running-Meson.html#installing
how to change the default /usr/local prefix to whatever prefix you use.

ср, 4 сент. 2019 г. в 00:28, fRANz <notifications@github.com>:

**Comment by franz82** [comment]
Thanks @rugubara, now it is working!

**Comment by ChristophSchmidpeter** [comment]
@rugubara: Thank you. It also works for me now on X11.

Edit: It still happens on X11. See my comment below

**Comment by ChristophSchmidpeter** [comment]
On Wayland however, it still does not work. Therefore, I have created another spice-gtk upstream [issue](https://gitlab.freedesktop.org/spice/spice-gtk/issues/113).

@TerrenceXu: It is only reproducible on Wayland now due to the above mentioned X11 fix. Have you tried to reproduce it on Gnome 3 with Wayland too?

**Comment by ChristophSchmidpeter** [comment]
Unfortunately, it occurs sporadically on X11 still:

![Screenshot from 2020-01-07 18-37-04](https://user-images.githubusercontent.com/3390179/71916982-61d24800-317f-11ea-94c8-56293a47c194.jpeg)

[dmesg.txt](https://github.com/intel/gvt-linux/files/4031808/dmesg.txt)

**Comment by rugubara** [comment]
@TitusLabienus, I noticed that you managed to get UEFI to be displayed in gvt scenario. Can you please share how you did it? I was never able to.

**Comment by ChristophSchmidpeter** [comment]
@rugubara The [Intel GVT-g Arch Linux Wiki Chapter "1.2.1.1.1 Using DMA-BUF with UEFI/OVMF"](https://wiki.archlinux.org/index.php/Intel_GVT-g#Using_DMA-BUF_with_UEFI/OVMF) describes workaround variants to boot with UEFI by overriding the VBios. (Here is my working XML file in case it helps: [Win10Uefi.xml.txt](https://github.com/intel/gvt-linux/files/4093556/Win10Uefi.xml.txt))

I used the third option:
- [Download the VBios](http://120.25.59.132:3000/vbios_gvt_uefi.rom)
- Make sure
`<domain type="kvm">`
is replaced with
`<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">`
- Add
```
    <qemu:arg value='-set'/>
    <qemu:arg value='device.hostdev0.romfile=/your/path/to/vbios_gvt_uefi.rom'/>
```
into to the 
```
  <qemu:commandline>
  [...]
  </qemu:commandline>
</domain>
```
block.

P.S.: [Using RamFB as also described in the wiki](https://wiki.archlinux.org/index.php/Intel_GVT-g#Using_RAMFB_display) is very helpful to install / see stuff outside of GVT/OS.

**Comment by ChristophSchmidpeter** [comment]
@ Developers @TerrenceXu I think it would be helpful for many people, if the RamFB and VBios parts get added to the official installation guide too.

**Comment by rugubara** [comment]
> @rugubara The [Intel GVT-g Arch Linux Wiki Chapter "1.2.1.1.1 Using DMA-BUF with UEFI/OVMF"](https://wiki.archlinux.org/index.php/Intel_GVT-g#Using_DMA-BUF_with_UEFI/OVMF) describes workaround variants to boot with UEFI by overriding the VBios. (Here is my working XML file in case it helps: [Win10Uefi.xml.txt](https://github.com/intel/gvt-linux/files/4093556/Win10Uefi.xml.txt))
> 
> I used the third option:
> 
> * [Download the VBios](http://120.25.59.132:3000/vbios_gvt_uefi.rom)
> * Make sure
>   `<domain type="kvm">`
>   is replaced with
>   `<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">`
> * Add
> 
> ```
>     <qemu:arg value='-set'/>
>     <qemu:arg value='device.hostdev0.romfile=/your/path/to/vbios_gvt_uefi.rom'/>
> ```
> 
> into to the
> 
> ```
>   <qemu:commandline>
>   [...]
>   </qemu:commandline>
> </domain>
> ```
> 
> block.
> 
> P.S.: [Using RamFB as also described in the wiki](https://wiki.archlinux.org/index.php/Intel_GVT-g#Using_RAMFB_display) is very helpful to install / see stuff outside of GVT/OS.

None of the suggested actions succeeded for me. I still can't see any pre-windows driver activation outputs.

**Comment by coxuintel** [comment]
What's your QEMU version? How about manually compile from v4.2.0?

**Comment by TerrenceXu** [comment]
Close it since long time no response.
