### ISSUE TITLE
[GVT-g] Change desktop refresh rate

### ISSUE THREAD

**Issue by FallingSnow** [01org/gvt-linux#99]
Is it possible to change the refresh rate on a gvt-g Windows 10 guest from the default 60Hz to 30Hz. I have numerous applications that need to run in borderless windowed mode and would like to limit them to 30fps.

Host: `Linux Divinity 5.1.0-rc6-mainline #1 SMP PREEMPT Fri Apr 26 10:35:40 PDT 2019 x86_64 GNU/Linux`
Guest: `Windows 10 64bit 1809`

**Comment by TerrenceXu** [comment]
I think it is related to how to connect your guest.
You use dma-buf? or vnc? or other tool?

**Comment by FallingSnow** [comment]
I actually use [parsec](https://parsecgaming.com/) to access it.

**Comment by TinaZhangZW** [comment]
This feature has been supported by upstream QEMU. Let's close the issue.
